/**
 * Sand CLI
 *
 * Multi-modal CLI for SandScript. Docker-style subcommands.
 * REPL is default.
 */

import { VERSION } from '../version.js';
import { SessionManager } from './sessions.js';
import { formatError } from '../fuel/semantic-errors.js';
import { checkSyntax } from '../fuel/syntax-check.js';
import { findStructuralIssues } from '../fuel/structural-checks.js';
import { UncaughtScriptError } from '../runtime/errors.js';


// =============================================================================
// Shared session manager (persists across commands in same process)
// =============================================================================

let sessionManager = null;

async function getSessionManager() {
  if (!sessionManager) {
    sessionManager = new SessionManager();
    await sessionManager.init();
  }
  return sessionManager;
}

// =============================================================================
// Commands
// =============================================================================

async function scriptCommand(args, flags) {
  const code = args[0];
  if (!code) {
    console.error('Usage: sand script "code"');
    Deno.exit(1);
  }

  const sessions = await getSessionManager();
  await rotateIfStuckAndReport(sessions);
  const { session } = await sessions.current();

  let parseResult;
  try {
    parseResult = session.parse(code);
  } catch (parseError) {
    const retrySession = await rotateOnCodeBlockFullAndReport(sessions, parseError);
    if (!retrySession) {
      console.error(parseError.message);
      Deno.exit(1);
    }
    await runParsedScript(retrySession, retrySession.parse(code), sessions, flags);
    return;
  }
  await runParsedScript(session, parseResult, sessions, flags);
}

/**
 * Finish running a script once it has parsed successfully: set the
 * instruction pointer, run to completion, and apply --verbose/--save.
 * Factored out so the normal path and the rotate-and-retry path (see
 * rotateOnCodeBlockFullAndReport) share one run/report tail instead of
 * duplicating it.
 */
async function runParsedScript(session, parseResult, sessions, flags) {
  session.mem.setContextInstructionIndex(0, parseResult.startIndex);

  let result;
  try {
    result = session.run(0, 100000);
  } catch (err) {
    if (err instanceof UncaughtScriptError) {
      sessions.markDirty();
      console.error(err.message);
      Deno.exit(1);
    }
    throw err;
  }
  if (result.status === 'error') {
    console.error(formatError(result.error));
    Deno.exit(1);
  }

  sessions.markDirty();

  // Aspirational: a successful `sand script` prints nothing on this
  // path unless --verbose is passed — exit 0, empty stdout, whether
  // the script was `let x = 1` or something that silently no-ops. A
  // caller (especially a non-interactive one) has no positive
  // confirmation short of a follow-up `sand get`. The fix would mirror
  // a REPL's own convention: print the value of a trailing bare
  // expression statement (not a declaration, which has no value).
  // Needs the parser to track "was the last statement an expression,
  // and what did it evaluate to" — no such plumbing exists yet.

  if (flags.verbose) {
    printScope(session);
  }

  if (flags.save) {
    await sessions.saveCurrentSession();
  }
}

/**
 * If the current session is the anonymous auto-created scratch session
 * (never explicitly named via `session new`/`session use`/`session
 * save`) and it's stuck at `status: 'error'` from a prior run, retire it
 * for a fresh one and report the rotation to stderr. Named sessions are
 * never touched here — a stuck named session is left for the user to
 * deal with explicitly, same as before this existed.
 */
async function rotateIfStuckAndReport(sessions) {
  const result = await sessions.rotateIfStuck();
  if (result.rotated) {
    console.error(`note: previous session hit an error and was retired; now using '${result.name}'`);
  }
}

/**
 * Called only after session.parse() has thrown. If the failure is the
 * code block filling up AND the current session is the anonymous
 * auto-created scratch session, retire it for a fresh one, report the
 * rotation to stderr, and return the new session so the caller can
 * retry the same parse once. Returns null for every other case (wrong
 * error, or a named session) so the caller surfaces the original error
 * exactly as before this existed.
 */
async function rotateOnCodeBlockFullAndReport(sessions, parseError) {
  if (!parseError.message.includes('Out of memory: code block collided with heap')) {
    return null;
  }
  if (!sessions.isCurrentAutoGenerated()) {
    return null;
  }
  const rotated = await sessions.rotate();
  console.error(`note: session was full and was retired; now using '${rotated.name}'`);
  return (await sessions.current()).session;
}

async function getCommand(args, flags) {
  const sessions = await getSessionManager();
  const { session } = await sessions.current();

  if (args.length === 0) {
    // List all variables. Session name goes to stderr (matching the
    // rotation notices' stream) so stdout stays exactly the bare,
    // comma-joined variable list — a script parsing stdout shouldn't
    // have to skip a header line to get at the data.
    console.error(`session: ${sessions.getCurrentName()}`);
    const vars = session.listVars(0);
    if (vars.length === 0) {
      console.log('(no variables)');
    } else {
      console.log(vars.join(', '));
    }
  } else {
    // Get specific variable
    const name = args[0];
    const value = session.get(0, name);
    if (value === undefined) {
      console.error(`undefined: ${name}`);
      Deno.exit(1);
    }
    console.log(JSON.stringify(toJsonSafe(value)));
  }
}

async function stepCommand(args, flags) {
  const sessions = await getSessionManager();
  const { session } = await sessions.current();

  if (args.length > 0 && isNaN(parseInt(args[0]))) {
    // First arg is code to load
    const code = args[0];
    const slot = 0;
    let parseResult;
    try {
      parseResult = session.parse(code);
    } catch (parseError) {
      console.error(parseError.message);
      Deno.exit(1);
    }
    session.mem.setContextInstructionIndex(slot, parseResult.startIndex);

    // fuel=0 means load only - code is ready to run, report as loaded
    console.log('loaded');
    sessions.markDirty();
  } else {
    // Resume execution
    const slot = 0;
    const fuel = args.length > 0 ? parseInt(args[0]) : 10000;
    const result = session.run(slot, fuel);

    const status = result.status === 'error' ? 'runtime_error' : result.status;
    // session.run returns remaining fuel as `result.fuel`; consumed is the
    // budget minus what's left.
    console.log(JSON.stringify({ status, fuelUsed: fuel - result.fuel }));
    sessions.markDirty();
  }
}

async function inspectCommand(args, flags) {
  const sessions = await getSessionManager();
  const { session } = await sessions.current();

  const what = args[0] || 'state';
  const state = session.state(0);

  switch (what) {
    case 'state':
      console.log(`status: ${state.status}`);
      console.log(`instruction: ${state.instruction}/${state.instructionCount}`);
      console.log(`callStack: ${state.callStackDepth}`);
      console.log(`fuel: ${state.fuel}`);
      break;

    case 'scope':
      printScope(session);
      break;

    case 'stack':
      console.log(`pending: [${state.pending.map(v => JSON.stringify(v)).join(', ')}]`);
      console.log(`callStackDepth: ${state.callStackDepth}`);
      break;

    case 'memory': {
      const address = args[1] ? (parseInt(args[1], 16) || parseInt(args[1])) : 0;
      const length = args[2] ? parseInt(args[2]) : 64;
      const bytes = new Uint8Array(session.mem.memory.buffer, address, length);
      const hex = Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join(' ');
      console.log(`@${address} (${length} bytes):`);
      console.log(hex);
      break;
    }

    default:
      console.log(JSON.stringify(state));
  }
}

async function sessionCommand(args, flags) {
  const [subcommand, ...rest] = args;
  const sessions = await getSessionManager();

  switch (subcommand) {
    case 'list': {
      const list = await sessions.listSessions();
      if (list.length === 0) {
        console.log('(no sessions)');
      } else {
        for (const s of list) {
          const marker = s.current ? '* ' : '  ';
          console.log(`${marker}${s.name}`);
        }
      }
      break;
    }

    case 'use': {
      const name = rest[0];
      if (!name) {
        console.error('Usage: sand session use <name>');
        Deno.exit(1);
      }
      const result = await sessions.useSession(name);
      if (result.notFound) {
        console.error(`session not found: ${name}`);
        Deno.exit(1);
      }
      if (result.loadError) {
        console.error(`failed to load session ${name}: ${result.loadError}`);
        Deno.exit(1);
      }
      console.log(`switched to ${result.name}`);
      break;
    }

    case 'new': {
      const name = rest[0];
      const result = await sessions.newSession(name);
      console.log(`created ${result.name}`);
      break;
    }

    case 'save': {
      const result = await sessions.saveCurrentSession();
      console.log(`saved ${result.name}`);
      break;
    }

    case 'save-as': {
      const name = rest[0];
      if (!name) {
        console.error('Usage: sand session save-as <name>');
        Deno.exit(1);
      }
      const result = await sessions.saveCurrentSessionAs(name);
      console.log(`saved as ${result.name}`);
      break;
    }

    case 'rename': {
      const name = rest[0];
      if (!name) {
        console.error('Usage: sand session rename <name>');
        Deno.exit(1);
      }
      const result = await sessions.renameSession(name);
      console.log(`renamed to ${result.name}`);
      break;
    }

    case 'delete': {
      const name = rest[0];
      if (!name) {
        console.error('Usage: sand session delete <name>');
        Deno.exit(1);
      }
      const result = await sessions.deleteSession(name);
      if (result.deleted) {
        console.log(`deleted ${name}`);
      } else {
        console.log(`not found: ${name}`);
      }
      break;
    }

    case 'export': {
      const path = rest[0];
      if (!path) {
        console.error('Usage: sand session export <path>');
        Deno.exit(1);
      }
      const name = sessions.getCurrentName();
      const result = await sessions.exportSession(name, path);
      console.log(`exported to ${result.path}`);
      break;
    }

    default:
      console.error('Usage: sand session <list|use|new|save|save-as|rename|delete|export>');
      Deno.exit(1);
  }
}

// =============================================================================
// REPL
// =============================================================================

async function runRepl() {
  const sessions = await getSessionManager();

  console.log('sand REPL (Ctrl+D or /exit to quit, /help for commands)');

  while (true) {
    const line = prompt('sand>');
    if (line === null) {
      // EOF (Ctrl+D)
      await sessions.saveAll();
      break;
    }

    const trimmed = line.trim();
    if (trimmed === '') continue;

    try {
      if (trimmed.startsWith('/')) {
        // Command mode
        const cmdLine = trimmed.slice(1);

        // Handle REPL-specific commands
        if (cmdLine === 'exit' || cmdLine === 'quit' || cmdLine === 'q') {
          await sessions.saveAll();
          break;
        }

        if (cmdLine === 'help' || cmdLine === 'h' || cmdLine === '?') {
          printReplHelp();
          continue;
        }

        const args = parseCommandLine(cmdLine);
        await runCommand(args);
      } else {
        // Implicit script
        await runCommand(['script', trimmed]);
      }
    } catch (err) {
      console.error(err.message);
    }
  }
}

function printReplHelp() {
  console.log(`
REPL Commands (prefix with /):
  /get [name]           Get variable value (or list all)
  /inspect [what]       Inspect state/scope/stack/memory
  /step ["code"]        Load code without running
  /step [fuel]          Resume with fuel limit
  /session list         List sessions
  /session use <name>   Switch session
  /session new [name]   New session
  /session save         Save current session
  /session save-as <n>  Fork to new name
  /exit, /quit, /q      Exit REPL
  /help, /h, /?         This help

Code runs directly (no / prefix):
  let x = 10
  let y = x * 2
`);
}

async function checkCommand(args, flags) {
  const path = args[0];
  if (!path) {
    console.error('Usage: sand check <file>');
    Deno.exit(1);
  }

  let code;
  try {
    code = await Deno.readTextFile(path);
  } catch (err) {
    console.error(`cannot read ${path}: ${err.message}`);
    Deno.exit(1);
  }

  if (code.startsWith('#!')) {
    const newlineIndex = code.indexOf('\n');
    if (newlineIndex !== -1) {
      code = code.slice(newlineIndex + 1);
    }
  }

  const result = checkSyntax(code);
  if (!result.ok) {
    console.error(formatError(result));
    Deno.exit(1);
  }

  const { findings } = findStructuralIssues(code);
  if (findings.length > 0) {
    for (const finding of findings) {
      console.error(`${finding.rule}: ${finding.message} (line ${finding.line}, col ${finding.column})`);
    }
    Deno.exit(1);
  }
}

// =============================================================================
// File runner
// =============================================================================

async function runFile(path, flags) {
  let code = await Deno.readTextFile(path);

  // Strip shebang if present
  if (code.startsWith('#!')) {
    const newlineIndex = code.indexOf('\n');
    if (newlineIndex !== -1) {
      code = code.slice(newlineIndex + 1);
    }
  }

  const sessions = await getSessionManager();
  await rotateIfStuckAndReport(sessions);
  const { session } = await sessions.current();

  let parseResult;
  try {
    parseResult = session.parse(code);
  } catch (parseError) {
    const retrySession = await rotateOnCodeBlockFullAndReport(sessions, parseError);
    if (!retrySession) {
      console.error(parseError.message);
      Deno.exit(1);
    }
    await runParsedScript(retrySession, retrySession.parse(code), sessions, flags);
    return;
  }
  await runParsedScript(session, parseResult, sessions, flags);
}

// =============================================================================
// Helpers
// =============================================================================

/**
 * Convert a session.get() readback value into something JSON.stringify
 * can serialize losslessly. Unlike formatValue (the human-facing
 * pretty-printer used by --verbose/printScope), this never truncates
 * and never abbreviates — a script consuming `sand get`'s output wants
 * the real data, not a preview.
 *
 * BigInt has no native JSON representation, so it's tagged as
 * {"$bigint": "<decimal digits>"} (a string, since JSON numbers can't
 * hold arbitrary precision) rather than silently coerced to a Number
 * (lossy) or a bare string (indistinguishable from an actual string
 * value). Every SandScript readback shape bottoms out in plain
 * primitives, arrays, and plain {kind: '...'} objects (rational,
 * complex, algebraic, theorem, expression, matrix — see
 * memory-reader.js's unmarshal* functions) with BigInts nested
 * throughout, so recursing through plain arrays/objects reaches them
 * all uniformly — no shape needs special-casing beyond BigInt itself.
 *
 * Throws on anything outside that value space (function, symbol) —
 * session.get() is never expected to return one, so seeing one here
 * means something upstream changed in a way worth knowing loudly,
 * not silently dropping the key.
 */
export function toJsonSafe(value) {
  if (value === null || value === undefined) return null;
  if (typeof value === 'bigint') return { $bigint: value.toString() };
  if (typeof value === 'number' || typeof value === 'string' || typeof value === 'boolean') {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(toJsonSafe);
  }
  if (typeof value === 'object') {
    const out = {};
    for (const key of Object.keys(value)) {
      out[key] = toJsonSafe(value[key]);
    }
    return out;
  }
  throw new TypeError(`toJsonSafe: unsupported value type ${typeof value}`);
}

export function formatValue(value, depth = 0, seen = new WeakSet()) {
  const MAX_DEPTH = 3;
  const MAX_STRING_LEN = 200;
  const MAX_NESTED_STRING_LEN = 50;
  const MAX_ITEMS = 20;

  if (value === null) return 'null';
  if (value === undefined) return 'undefined';

  if (typeof value === 'string') {
    const maxLen = depth === 0 ? MAX_STRING_LEN : MAX_NESTED_STRING_LEN;
    const truncated = value.length > maxLen ? value.slice(0, maxLen) + '...' : value;
    return depth === 0 ? truncated : `"${truncated}"`;
  }

  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }

  if (typeof value === 'function') {
    return value.name ? `[Function: ${value.name}]` : '[Function]';
  }

  if (typeof value === 'object') {
    if (seen.has(value)) return '[Circular]';
    seen.add(value);

    if (depth >= MAX_DEPTH) {
      return Array.isArray(value) ? '[...]' : '{...}';
    }

    if (Array.isArray(value)) {
      if (value.length === 0) return '[]';
      const items = value.slice(0, MAX_ITEMS).map(v => formatValue(v, depth + 1, seen));
      const more = value.length > MAX_ITEMS ? `, ... ${value.length - MAX_ITEMS} more` : '';
      return `[${items.join(', ')}${more}]`;
    }

    const keys = Object.keys(value);
    if (keys.length === 0) return '{  }';
    const items = keys.slice(0, MAX_ITEMS).map(k => `${k}: ${formatValue(value[k], depth + 1, seen)}`);
    const more = keys.length > MAX_ITEMS ? `, ... ${keys.length - MAX_ITEMS} more` : '';
    return `{ ${items.join(', ')}${more} }`;
  }

  return String(value);
}

function printScope(session) {
  const vars = session.listVars(0);
  for (const name of vars) {
    const value = session.get(0, name);
    console.log(`${name} = ${formatValue(value)}`);
  }
}

function parseCommandLine(line) {
  // Simple arg parser: split on spaces, respecting quotes
  const args = [];
  let current = '';
  let inQuote = false;
  let quoteChar = '';

  for (const char of line) {
    if (inQuote) {
      if (char === quoteChar) {
        inQuote = false;
      } else {
        current += char;
      }
    } else {
      if (char === '"' || char === "'") {
        inQuote = true;
        quoteChar = char;
      } else if (char === ' ') {
        if (current) {
          args.push(current);
          current = '';
        }
      } else {
        current += char;
      }
    }
  }

  if (current) {
    args.push(current);
  }

  return args;
}

function parseFlags(args) {
  const flags = {};
  const positional = [];

  for (const arg of args) {
    if (arg === '--verbose' || arg === '-v') {
      flags.verbose = true;
    } else if (arg === '--save') {
      flags.save = true;
    } else if (arg.startsWith('--')) {
      // Unknown flag, ignore for now
    } else if (arg.startsWith('-')) {
      // Unknown short flag, ignore for now
    } else {
      positional.push(arg);
    }
  }

  return { flags, positional };
}

// =============================================================================
// Command dispatch
// =============================================================================

async function runCommand(args) {
  const [command, ...rest] = args;
  const { flags, positional } = parseFlags(rest);

  switch (command) {
    case 'script':
      await scriptCommand(positional, flags);
      break;

    case 'check':
      await checkCommand(positional, flags);
      break;

    case 'get':
      await getCommand(positional, flags);
      break;

    case 'step':
      await stepCommand(positional, flags);
      break;

    case 'inspect':
      await inspectCommand(positional, flags);
      break;

    case 'session':
      await sessionCommand(positional, flags);
      break;

    default:
      // Check if it's a file
      if (command && (command.endsWith('.ss') || command.endsWith('.sand') || await fileExists(command))) {
        await runFile(command, flags);
      } else {
        console.error(`Unknown command: ${command}`);
        console.error('Run "sand --help" for usage');
        Deno.exit(1);
      }
  }
}

async function fileExists(path) {
  try {
    await Deno.stat(path);
    return true;
  } catch {
    return false;
  }
}

// =============================================================================
// Help
// =============================================================================

function printHelp() {
  console.log(`sand - SandScript CLI

Usage:
  sand                              REPL mode (default)
  sand script "code"                Run code
  sand check <file>                 Syntax + structural checks, no run
  sand get [name]                   Get variable (or list all)
  sand step ["code"]                Load code or resume execution
  sand step [fuel]                  Resume with fuel limit
  sand inspect [what]               Inspect state/scope/stack/memory
  sand session <cmd>                Manage sessions
  sand <file.ss>                    Run file

Session commands:
  sand session list                 List all sessions
  sand session use <name>           Switch to session (creates if needed)
  sand session new [name]           Create new session
  sand session save                 Save current session
  sand session save-as <name>       Fork to new name
  sand session rename <name>        Rename current session
  sand session delete <name>        Delete a session
  sand session export <path>        Export to file

Flags:
  --verbose, -v                     Print scope after execution
  --save                            Save session after execution
  --version                         Show version
  --help, -h                        Show this help

Examples:

  Quick calculation (implicit session, auto-persists):
    $ sand script "let income = 85000"
    $ sand script "let tax = income * 0.22"
    $ sand get tax
    18700

  Named session for a project:
    $ sand session new taxes-2024
    $ sand script "let income = 120000"
    $ sand script "let deductions = 15000"
    $ sand script "let taxable = income - deductions"
    $ sand script "let rate = 0.24"
    $ sand script "let owed = taxable * rate"
    $ sand get owed
    25200
    $ sand session save-as taxes-2024-final

  Load and modify a saved session (read-only by default):
    $ sand session use taxes-2024
    $ sand script "let scenario = taxable * 0.30"  # Temporary, not saved
    $ sand get scenario
    31500
    $ sand session save                            # Explicitly save if wanted

  Inspect interpreter state:
    $ sand inspect              # status, instruction pointer, fuel
    $ sand inspect scope        # all variables and values
    $ sand inspect stack        # pending stack (during execution)
    $ sand inspect memory 0x100 # raw memory dump

  Step-by-step debugging:
    $ sand step "let a = 1; let b = 2; let c = a + b"
    loaded
    $ sand inspect
    status: paused, instruction: 0/8, fuel: 0
    $ sand step 3               # execute 3 instructions
    {"status":"paused","fuelUsed":3}
    $ sand step                 # run to completion
    {"status":"done","fuelUsed":...}
    $ sand get c
    3

  Run a file:
    $ sand calc.ss --verbose    # run file, show all variables after

REPL:
  In REPL, code runs directly. Use / to escape to commands.
  Exit with Ctrl+D or /exit.

    $ sand
    sand> let x = 10
    sand> let y = x * 2
    sand> /get y
    20
    sand> /inspect scope
    x = 10
    y = 20
    sand> /session save-as mywork
    sand> /exit
`);
}

function printVersion() {
  console.log(`sand ${VERSION}`);
}

// =============================================================================
// Main
// =============================================================================

// Only run when this is the main module (not when imported)
if (import.meta.main) {
  const args = Deno.args;

  if (args.includes('--version')) {
    printVersion();
  } else if (args.includes('--help') || args.includes('-h')) {
    printHelp();
  } else if (args.length === 0) {
    await runRepl();
  } else {
    await runCommand(args);
    // Auto-save new sessions
    if (sessionManager) {
      await sessionManager.saveAll();
    }
  }
}
