/**
 * Session Manager
 *
 * Manages multiple SandScript sessions with persistence.
 * Sessions are gzipped memory dumps stored in ~/.sandscript/sessions/
 */

import { freshSession, restoreSession, snapshotSession } from '../host-owned-session.js';

// =============================================================================
// Session Name Generation
//
// Three-word names evoking sand, math, and the poetic.
// Examples: "dune-euler-spiral", "grain-fourier-wave", "desert-gauss-curve"
// =============================================================================

// Sand & Desert imagery
const SAND = [
  'dune', 'grain', 'desert', 'oasis', 'mirage', 'drift', 'shore', 'beach',
  'delta', 'sediment', 'silica', 'quartz', 'grit', 'dust', 'erosion', 'ripple',
  'hourglass', 'sandstone', 'mesa', 'canyon', 'arid', 'barren', 'windswept',
  'sunbaked', 'amber', 'ochre', 'golden', 'tawny',
];

// Mathematicians & Thinkers
const MATHEMATICIANS = [
  'euler', 'gauss', 'fourier', 'laplace', 'newton', 'leibniz', 'riemann',
  'cantor', 'godel', 'turing', 'lovelace', 'noether', 'hilbert', 'fermat',
  'pascal', 'descartes', 'archimedes', 'euclid', 'pythagoras', 'fibonacci',
  'mandelbrot', 'ramanujan', 'erdos', 'hypatia', 'poincare', 'kolmogorov',
  'bayes', 'markov',
];

// Mathematical objects & concepts
const MATH_OBJECTS = [
  'spiral', 'wave', 'curve', 'field', 'space', 'series', 'prime', 'root',
  'orbit', 'fractal', 'tensor', 'vector', 'matrix', 'proof', 'theorem',
  'axiom', 'lemma', 'set', 'graph', 'lattice', 'manifold', 'surface',
  'integral', 'limit', 'sum', 'ratio', 'sequence', 'function',
];

/**
 * Pick a random element from an array.
 */
function pick(array) {
  return array[Math.floor(Math.random() * array.length)];
}

/**
 * Generate a session name like "dune-euler-spiral"
 */
function generateName() {
  return `${pick(SAND)}-${pick(MATHEMATICIANS)}-${pick(MATH_OBJECTS)}`;
}

/**
 * Get sessions directory path
 */
function getSessionsDir() {
  const home = Deno.env.get('HOME') || Deno.env.get('USERPROFILE') || '.';
  return `${home}/.sandscript/sessions`;
}

/**
 * Session Manager - handles multiple named sessions with persistence
 *
 * Session entry structure: { session: FuelSession, saved: boolean }
 *
 * Sessions are ephemeral by default. Each MCP connection starts fresh.
 * Use 'save' or 'save-as' to persist sessions to disk.
 * Use 'use' to load a saved session.
 */
export class SessionManager {
  constructor() {
    this.sessions = new Map(); // name -> { session, saved, dirty, fromDisk }
    this.currentName = null;
    this.currentOwned = false; // Whether we own the current session (not read-only)
    // Whether the current session is the anonymous, auto-created scratch
    // session (never given a name by the user via `session new <name>` or
    // `session use <name>`). This is the ONLY session type eligible for
    // auto-rotation when it fills up or gets stuck in an error state —
    // named sessions never rotate silently.
    this.currentAutoGenerated = false;
    this.sessionsDir = getSessionsDir();
    this.ephemeral = false; // MCP mode: don't persist state across connections
  }

  /**
   * Initialize the manager
   * @param {Object} options
   * @param {boolean} options.ephemeral - If true, don't restore state (MCP mode)
   */
  async init(options = {}) {
    try {
      await Deno.mkdir(this.sessionsDir, { recursive: true });
    } catch (err) {
      if (!(err instanceof Deno.errors.AlreadyExists)) {
        throw err;
      }
    }

    if (options.ephemeral) {
      // MCP mode: don't restore state, start fresh each connection
      this.ephemeral = true;
      return;
    }

    // CLI mode: restore previous session state
    await this.loadState();

    if (this.currentName) {
      let loaded = false;
      try {
        loaded = await this.loadSession(this.currentName);
      } catch (error) {
        console.error(
          `warning: session '${this.currentName}' could not be restored ` +
          `(${error.message}); starting without it`);
      }
      if (loaded) {
        // If we owned this session (created it, not explicitly loaded via `use`),
        // mark as not from disk so changes get saved
        if (this.currentOwned) {
          const entry = this.sessions.get(this.currentName);
          entry.fromDisk = false;
        }
      } else {
        // Session file deleted or unrestorable — reset
        this.currentName = null;
        this.currentOwned = false;
      }
    }
  }

  /**
   * Load state file (~/.sandscript/state.json)
   */
  async loadState() {
    const statePath = `${this.sessionsDir}/../state.json`;
    try {
      const data = await Deno.readTextFile(statePath);
      const state = JSON.parse(data);
      this.currentName = state.current || null;
      this.currentOwned = state.owned || false;
      this.currentAutoGenerated = state.autoGenerated || false;
    } catch {
      // State file doesn't exist or is invalid
      this.currentName = null;
      this.currentOwned = false;
      this.currentAutoGenerated = false;
    }
  }

  /**
   * Save state file
   */
  async saveState() {
    const statePath = `${this.sessionsDir}/../state.json`;
    const state = {
      current: this.currentName,
      owned: this.currentOwned,
      autoGenerated: this.currentAutoGenerated,
    };
    await Deno.writeTextFile(statePath, JSON.stringify(state, null, 2) + '\n');
  }

  /**
   * Get or create the current session
   */
  async current() {
    if (!this.currentName) {
      // Create fresh session
      this.currentName = generateName();
      this.currentOwned = true; // We created it, we own it
      this.currentAutoGenerated = true; // Anonymous scratch session — eligible for auto-rotation
      const session = freshSession();
      // Mark dirty so it gets auto-saved in CLI mode
      // fromDisk=false means it will be auto-saved
      this.sessions.set(this.currentName, { session, saved: false, dirty: true, fromDisk: false });
      if (!this.ephemeral) {
        await this.saveState();
      }
    }
    return this.sessions.get(this.currentName);
  }

  /**
   * Roll the current anonymous scratch session out for a fresh one.
   *
   * Only ever called when currentAutoGenerated is true — named sessions
   * (anything reached via `session new <name>` or `session use <name>`)
   * never rotate, on purpose: a user who named a session is accumulating
   * something deliberately, and silently replacing it would destroy that.
   *
   * The old anonymous session is simply dropped, not migrated — it is
   * being rotated out because it is unusable (full code block, or stuck
   * on a context in `status: 'error'`), and named sessions are the
   * mechanism for anything meant to survive.
   *
   * @returns {Promise<{name: string}>} the newly created session's name
   */
  async rotate() {
    this.currentName = generateName();
    this.currentOwned = true;
    this.currentAutoGenerated = true;
    const session = freshSession();
    this.sessions.set(this.currentName, { session, saved: false, dirty: true, fromDisk: false });
    if (!this.ephemeral) {
      await this.saveState();
    }
    return { name: this.currentName };
  }

  /**
   * Check whether the current anonymous scratch session needs rotating
   * before running more code — either because a prior run left it stuck
   * in an error state, or because new code would not fit in its
   * remaining code-block headroom. Named sessions are never rotated;
   * this always returns false for them without checking anything.
   *
   * @returns {Promise<{rotated: boolean, name: string}>}
   */
  async rotateIfStuck() {
    if (!this.currentAutoGenerated || !this.currentName) {
      return { rotated: false, name: this.currentName };
    }
    const entry = this.sessions.get(this.currentName);
    if (!entry) {
      return { rotated: false, name: this.currentName };
    }
    const state = entry.session.state(0);
    if (state.status === 'error') {
      const result = await this.rotate();
      return { rotated: true, name: result.name };
    }
    return { rotated: false, name: this.currentName };
  }

  /**
   * Create a new session and switch to it (discards current)
   */
  async newSession(name) {
    const sessionName = name || generateName();
    const session = freshSession();
    // Mark dirty so it gets auto-saved in CLI mode
    // fromDisk=false means it will be auto-saved
    this.sessions.set(sessionName, { session, saved: false, dirty: true, fromDisk: false });
    this.currentName = sessionName;
    this.currentOwned = true; // We created it, we own it
    this.currentAutoGenerated = false; // Explicit `session new` — never auto-rotates
    if (!this.ephemeral) {
      await this.saveState();
    }
    return { name: sessionName };
  }

  /**
   * Switch to an existing session (discards current)
   * Loaded sessions are read-only by default
   */
  async useSession(name) {
    if (this.sessions.has(name)) {
      // Already loaded - keep as read-only
      this.currentName = name;
      this.currentOwned = false; // Explicitly switched = read-only
      this.currentAutoGenerated = false; // Explicit `session use` — never auto-rotates
      if (!this.ephemeral) {
        await this.saveState();
      }
      return { name };
    }

    // Try to load from disk
    let loaded;
    try {
      loaded = await this.loadSession(name);
    } catch (error) {
      // File exists but could not be restored (corrupt, version
      // cutover, ...). Report the real reason.
      return { name, loadError: error.message };
    }
    if (loaded) {
      this.currentName = name;
      this.currentOwned = false; // Explicitly loaded = read-only
      this.currentAutoGenerated = false; // Explicit `session use` — never auto-rotates
      if (!this.ephemeral) {
        await this.saveState();
      }
      return { name };
    }

    // Session doesn't exist
    return { name, notFound: true };
  }

  /**
   * List all sessions (in memory + on disk)
   * Current session listed first, marked as ephemeral if not saved
   */
  async listSessions() {
    const diskSessions = new Set();

    // Get sessions from disk
    try {
      for await (const entry of Deno.readDir(this.sessionsDir)) {
        if (entry.isFile && entry.name.endsWith('.sand')) {
          diskSessions.add(entry.name.slice(0, -5)); // remove .sand
        }
      }
    } catch {
      // Directory might not exist yet
    }

    const result = [];

    // Current session first (if exists)
    if (this.currentName) {
      const entry = this.sessions.get(this.currentName);
      const isEphemeral = entry && !entry.saved;
      result.push({
        name: this.currentName,
        current: true,
        ephemeral: isEphemeral,
      });
    }

    // Add disk sessions (excluding current)
    for (const name of diskSessions) {
      if (name !== this.currentName) {
        result.push({
          name,
          current: false,
          ephemeral: false,
        });
      }
    }

    return result;
  }


  /**
   * Mark current session as dirty (has unsaved changes)
   * Used by CLI for auto-save tracking
   */
  markDirty() {
    if (this.currentName && this.sessions.has(this.currentName)) {
      const entry = this.sessions.get(this.currentName);
      entry.dirty = true;
    }
  }

  /**
   * Save all dirty NEW sessions to disk (not loaded from disk)
   * Used by CLI for auto-save on exit
   * Loaded sessions require explicit save
   */
  async saveAll() {
    for (const [name, entry] of this.sessions) {
      if (entry.dirty && !entry.fromDisk) {
        await this.saveSession(name);
      }
    }
  }

  /**
   * Save a session to disk (using CompressionStream for gzip)
   */
  async saveSession(name) {
    const entry = this.sessions.get(name);
    if (!entry) return false;

    const { session } = entry;
    // Under the host-owned-memory contract the host slices its own
    // buffers; snapshotSession exposes that for sessions constructed
    // via freshSession / restoreSession.
    const { vatBytes, membraneBytes } = snapshotSession(session);

    // Serialize: u32 vatLen | vat bytes | u32 membraneLen | membrane bytes.
    // Self-describing for the restore path; no separate sidecar file.
    const combined = new Uint8Array(8 + vatBytes.byteLength + membraneBytes.byteLength);
    const view = new DataView(combined.buffer);
    view.setUint32(0, vatBytes.byteLength, true);
    combined.set(vatBytes, 4);
    view.setUint32(4 + vatBytes.byteLength, membraneBytes.byteLength, true);
    combined.set(membraneBytes, 8 + vatBytes.byteLength);

    // Compress using CompressionStream
    const stream = new Blob([combined]).stream().pipeThrough(new CompressionStream('gzip'));
    const compressed = new Uint8Array(await new Response(stream).arrayBuffer());

    // Write to file
    const path = `${this.sessionsDir}/${name}.sand`;
    await Deno.writeFile(path, compressed);

    entry.saved = true;
    entry.dirty = false;
    return true;
  }

  /**
   * Load a session from disk
   */
  async loadSession(name) {
    const path = `${this.sessionsDir}/${name}.sand`;

    let compressed;
    try {
      compressed = await Deno.readFile(path);
    } catch {
      // No session file on disk — the one case that is genuinely
      // "not found".
      return false;
    }

    // Past this point the file exists: any failure (corrupt envelope,
    // snapshot version cutover, ...) is a real load error and
    // propagates to the caller instead of masquerading as "not found".

    // Decompress using DecompressionStream
    const stream = new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'));
    const combined = new Uint8Array(await new Response(stream).arrayBuffer());

    // Length-prefixed [vat][membrane] envelope written by
    // saveSession above.
    const view = new DataView(combined.buffer, combined.byteOffset, combined.byteLength);
    const vatLen      = view.getUint32(0, true);
    const vatBytes    = combined.subarray(4, 4 + vatLen);
    const membraneLen = view.getUint32(4 + vatLen, true);
    const membraneBytes = combined.subarray(8 + vatLen, 8 + vatLen + membraneLen);

    // Restore via the host-owned-memory helper.
    // Mark fromDisk=true so changes are ephemeral (not auto-saved)
    const session = restoreSession(vatBytes, membraneBytes);
    this.sessions.set(name, { session, saved: true, dirty: false, fromDisk: true });
    return true;
  }

  /**
   * Save current session to disk
   */
  async saveCurrentSession() {
    if (!this.currentName) {
      throw new Error('No current session to save');
    }
    const entry = this.sessions.get(this.currentName);
    if (!entry) {
      throw new Error('Current session not found');
    }
    await this.saveSession(this.currentName);
    // After explicit save, it's no longer read-only
    entry.fromDisk = false;
    this.currentOwned = true;
    this.currentAutoGenerated = false; // Explicit `session save` — never auto-rotates
    if (!this.ephemeral) {
      await this.saveState();
    }
    return { name: this.currentName };
  }

  /**
   * Save current session to a new name (fork)
   */
  async saveCurrentSessionAs(newName) {
    if (!this.currentName) {
      throw new Error('No current session to save');
    }
    if (!newName) {
      throw new Error('New name required');
    }

    // Check if name already exists
    const existingPath = `${this.sessionsDir}/${newName}.sand`;
    try {
      await Deno.stat(existingPath);
      throw new Error(`Session "${newName}" already exists`);
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) {
        throw err;
      }
    }

    const entry = this.sessions.get(this.currentName);
    if (!entry) {
      throw new Error('Current session not found');
    }

    // Save to new name (copy from SharedArrayBuffer since Blob doesn't accept shared views)
    const { session } = entry;
    const { vatBytes, membraneBytes } = snapshotSession(session);

    // Same length-prefixed envelope as saveSession: vat then membrane.
    const combined = new Uint8Array(8 + vatBytes.byteLength + membraneBytes.byteLength);
    const view = new DataView(combined.buffer);
    view.setUint32(0, vatBytes.byteLength, true);
    combined.set(vatBytes, 4);
    view.setUint32(4 + vatBytes.byteLength, membraneBytes.byteLength, true);
    combined.set(membraneBytes, 8 + vatBytes.byteLength);

    const stream = new Blob([combined]).stream().pipeThrough(new CompressionStream('gzip'));
    const compressed = new Uint8Array(await new Response(stream).arrayBuffer());
    const path = `${this.sessionsDir}/${newName}.sand`;
    await Deno.writeFile(path, compressed);

    // Switch to the new session (reload it fresh)
    await this.loadSession(newName);
    this.currentName = newName;
    this.currentOwned = true; // Just saved it explicitly, same as saveCurrentSession
    this.currentAutoGenerated = false; // Explicit `session save-as` — never auto-rotates
    if (!this.ephemeral) {
      await this.saveState();
    }

    return { name: newName };
  }

  /**
   * Get current session name
   */
  getCurrentName() {
    return this.currentName;
  }

  /**
   * Whether the current session is the anonymous, auto-created scratch
   * session — the only kind eligible for auto-rotation.
   */
  isCurrentAutoGenerated() {
    return this.currentAutoGenerated;
  }

  /**
   * Rename the current session
   */
  async renameSession(newName) {
    if (!this.currentName) {
      throw new Error('No current session to rename');
    }
    if (!newName) {
      throw new Error('New name required');
    }
    if (newName === this.currentName) {
      return { name: newName };
    }

    // Check if new name already exists
    const existingPath = `${this.sessionsDir}/${newName}.sand`;
    try {
      await Deno.stat(existingPath);
      throw new Error(`Session "${newName}" already exists`);
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) {
        throw err;
      }
    }

    const oldName = this.currentName;
    const entry = this.sessions.get(oldName);

    // Update in-memory map
    this.sessions.delete(oldName);
    this.sessions.set(newName, entry);
    this.currentName = newName;

    // Rename file on disk if it exists (only if saved)
    if (entry.saved) {
      const oldPath = `${this.sessionsDir}/${oldName}.sand`;
      const newPath = `${this.sessionsDir}/${newName}.sand`;
      try {
        await Deno.rename(oldPath, newPath);
      } catch {
        // File might not exist
      }
    }

    if (!this.ephemeral) {
      await this.saveState();
    }

    return { name: newName };
  }

  /**
   * Delete a session
   */
  async deleteSession(name) {
    if (!name) {
      throw new Error('Session name required');
    }

    // Can't delete current session
    if (name === this.currentName) {
      throw new Error('Cannot delete current session');
    }

    // Remove from memory
    this.sessions.delete(name);

    // Remove from disk
    const path = `${this.sessionsDir}/${name}.sand`;
    try {
      await Deno.remove(path);
      return { deleted: true };
    } catch (err) {
      if (err instanceof Deno.errors.NotFound) {
        return { deleted: false };
      }
      throw err;
    }
  }

  /**
   * Export a session to a file
   */
  async exportSession(name, destPath) {
    if (!name) {
      throw new Error('Session name required');
    }
    if (!destPath) {
      throw new Error('Destination path required');
    }

    // Expand ~ to home directory
    if (destPath.startsWith('~/')) {
      const home = Deno.env.get('HOME') || Deno.env.get('USERPROFILE') || '.';
      destPath = `${home}${destPath.slice(1)}`;
    }

    // If session is in memory, save it first
    if (this.sessions.has(name)) {
      await this.saveSession(name);
    }

    // Copy the session file
    const srcPath = `${this.sessionsDir}/${name}.sand`;
    try {
      await Deno.copyFile(srcPath, destPath);
      return { path: destPath };
    } catch (err) {
      if (err instanceof Deno.errors.NotFound) {
        throw new Error(`Session "${name}" not found`);
      }
      throw err;
    }
  }
}
