  ;; Copyright (c) 2018 Microsoft Corporation. All rights reserved.
  ;; Released under Apache 2.0 license as described in the file LICENSE.
  ;; Author: Leonardo de Moura
  ;; Adapted for SandScript by DevBlanket AB, 2026.
  ;; Lean src/kernel/inductive.cpp: mk_rec_infos, mk_rec_rules, check_recursors,
  ;; init_K_target; revision 6a10ac8c22beadecabdbb0919c2b50214762f91d.
  ;; Binder annotation consumption follows Lean src/Lean/Expr.lean,
  ;; consumeTypeAnnotations, at the same revision.
  ;;
  ;; Generation uses de Bruijn telescopes, never assumptions or exported rules.
  ;; State slots: group, parameter count, motive count, minor count, prefix
  ;; domains, family levels, recursor levels, universe context, recursor indices,
  ;; motive sort, shared work. All generated references live in the proof arena.

  (func $proof_rec_bound (param $b i32) (param $n i32) (result i32)
    (call $proof_make_one (local.get $b) (global.get $PROOF_TERM_BOUND) (local.get $n)))

  (func $proof_rec_apply (param $b i32) (param $f i32) (param $x i32) (result i32)
    (if (i32.or (i32.eqz (local.get $f)) (i32.eqz (local.get $x)))
      (then (return (i32.const 0))))
    (call $proof_make_two (local.get $b) (global.get $PROOF_TERM_APPLICATION)
      (local.get $f) (local.get $x)))

  (func $proof_rec_drop_products (param $b i32) (param $t i32) (param $n i32) (result i32)
    (block $done (loop $next
      (br_if $done (i32.eqz (local.get $n)))
      (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 4)))
        (global.get $PROOF_TERM_PRODUCT)) (then (return (i32.const 0))))
      (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 12))))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br $next)))
    (local.get $t))

  ;; Apply variables at absolute binder positions [start,start+count), where
  ;; depth is the complete surrounding telescope length.
  (func $proof_rec_apply_vars
    (param $b i32) (param $t i32) (param $depth i32) (param $start i32) (param $count i32)
    (result i32) (local $i i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $count)))
      (local.set $t (call $proof_rec_apply (local.get $b) (local.get $t)
        (call $proof_rec_bound (local.get $b)
          (i32.sub (i32.sub (local.get $depth) (i32.add (local.get $start) (local.get $i))) (i32.const 1)))))
      (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (local.get $t))

  ;; Lean consumes only head annotations when introducing a telescope local;
  ;; it does not normalize arbitrary aliases or descend beneath other terms.
  ;; This changes generated syntax, not reduction authority: the resulting
  ;; recursor type and rules still pass the ordinary typed checks.
  (func $proof_rec_consume_type_annotations
    (param $b i32) (param $t i32) (result i32)
    (local $head i32) (local $target i32) (local $arity i32)
    (local $tag i32) (local $decl i32) (local $name i32) (local $ctors i32)
    (loop $next
      (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 4)))
        (global.get $PROOF_TERM_APPLICATION)) (then (return (local.get $t))))
      (local.set $head (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))))
      (local.set $target (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 12))))
      (local.set $arity (i32.const 1))
      (if (i32.eq (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 4)))
        (global.get $PROOF_TERM_APPLICATION))
        (then
          (local.set $target (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 12))))
          (local.set $head (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 8))))
          (local.set $arity (i32.const 2))))
      (local.set $tag (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 4))))
      (if (i32.or (i32.lt_u (local.get $tag) (global.get $PROOF_TERM_GLOBAL))
        (i32.gt_u (local.get $tag) (global.get $PROOF_TERM_CONSTRUCTOR)))
        (then (return (local.get $t))))
      (local.set $decl (call $proof_declaration_reference (local.get $b)
        (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 8)))))
      (if (i32.eqz (local.get $decl)) (then (return (local.get $t))))
      (if (i32.eq (local.get $tag) (global.get $PROOF_TERM_CONSTRUCTOR))
        (then
          (local.set $ctors (call $proof_load (local.get $b) (i32.add (local.get $decl) (i32.const 24))))
          (local.set $decl (call $proof_array_get (local.get $b) (local.get $ctors)
            (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 12)))))))
      (local.set $name (call $proof_declaration_name (local.get $b) (local.get $decl)))
      (if (i32.eqz (local.get $name)) (then (return (local.get $t))))
      (if (call $proof_load (local.get $b) (i32.add (local.get $name) (i32.const 8)))
        (then (return (local.get $t))))
      (if (i32.eq (local.get $arity) (i32.const 1))
        (then
          (if (i32.eqz (i32.or
            (call $proof_name_segment_matches (local.get $b) (local.get $name) (i32.const 8)
              (i32.const 0x5074756f) (i32.const 0x6d617261) (i32.const 0))
            (call $proof_name_segment_matches (local.get $b) (local.get $name) (i32.const 12)
              (i32.const 0x696d6573) (i32.const 0x5074754f) (i32.const 0x6d617261))))
            (then (return (local.get $t)))))
        (else
          (if (i32.eqz (i32.or
            (call $proof_name_segment_matches (local.get $b) (local.get $name) (i32.const 8)
              (i32.const 0x5074706f) (i32.const 0x6d617261) (i32.const 0))
            (call $proof_name_segment_matches (local.get $b) (local.get $name) (i32.const 9)
              (i32.const 0x6f747561) (i32.const 0x61726150) (i32.const 0x0000006d))))
            (then (return (local.get $t))))))
      (local.set $t (local.get $target))
      (br $next))
    (local.get $t))

  (func $proof_rec_wrap
    (param $b i32) (param $domains i32) (param $n i32) (param $t i32) (param $tag i32)
    (result i32)
    (block $done (loop $next
      (br_if $done (i32.eqz (local.get $n)))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (local.set $t (call $proof_make_two (local.get $b) (local.get $tag)
        (call $proof_rec_consume_type_annotations (local.get $b)
          (call $proof_array_get (local.get $b) (local.get $domains) (local.get $n))) (local.get $t)))
      (if (i32.eqz (local.get $t)) (then (return (i32.const 0)))) (br $next)))
    (local.get $t))

  (func $proof_rec_group_position (param $b i32) (param $group i32) (param $owner i32)
    (result i32) (local $i i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (call $proof_array_count (local.get $b) (local.get $group))))
      (if (i32.eq (call $proof_array_get (local.get $b) (local.get $group) (local.get $i)) (local.get $owner))
        (then (return (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (i32.const -1))

  (func $proof_find_recursor (param $b i32) (param $owner i32) (result i32)
    (local $ds i32) (local $d i32) (local $group i32) (local $position i32)
    (local $count i32) (local $index i32)
    (local.set $ds (call $proof_load (local.get $b) (i32.const 12)))
    (local.set $count (call $proof_array_count (local.get $b) (local.get $ds)))
    (if (i32.ge_u (local.get $owner) (local.get $count)) (then (return (i32.const -1))))
    (local.set $d (call $proof_array_get (local.get $b) (local.get $ds) (local.get $owner)))
    (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 4)))
      (global.get $PROOF_RECORD_INDUCTIVE_DECLARATION)) (then (return (i32.const -1))))
    (local.set $group (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 28))))
    (local.set $position (call $proof_rec_group_position (local.get $b) (local.get $group) (local.get $owner)))
    (if (i32.lt_s (local.get $position) (i32.const 0)) (then (return (i32.const -1))))
    (local.set $index (i32.add (i32.add
      (call $proof_array_get (local.get $b) (local.get $group) (i32.const 0))
      (call $proof_array_count (local.get $b) (local.get $group))) (local.get $position)))
    (if (i32.ge_u (local.get $index) (local.get $count)) (then (return (i32.const -1))))
    (local.set $d (call $proof_array_get (local.get $b) (local.get $ds) (local.get $index)))
    (if (i32.or
      (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 4)))
        (global.get $PROOF_RECORD_RECURSOR_DECLARATION))
      (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 16))) (local.get $owner)))
      (then (return (i32.const -1))))
    (local.get $index))

  ;; Motive type at prefix depth params+extra. Original family indices remain
  ;; bound while the newly inserted motives/minors shift only the parameters.
  (func $proof_rec_motive
    (param $b i32) (param $s i32) (param $owner i32) (param $extra i32) (param $work i32) (result i32)
    (local $d i32) (local $p i32) (local $n i32) (local $t i32)
    (local $domains i32) (local $i i32) (local $major i32)
    (local.set $d (call $proof_declaration_reference (local.get $b) (local.get $owner)))
    (local.set $p (call $proof_array_get (local.get $b) (local.get $s) (i32.const 1)))
    (local.set $n (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 20))))
    (local.set $t (call $proof_instantiate_term_universes (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 12)))
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 5)) (local.get $work)))
    (local.set $t (call $proof_rec_drop_products (local.get $b) (local.get $t) (local.get $p)))
    (local.set $t (call $proof_shift (local.get $b) (local.get $t) (local.get $extra) (i32.const 0) (i32.const 0)))
    (local.set $domains (call $proof_make_array (local.get $b) (local.get $n)))
    (if (i32.or (i32.eqz (local.get $t)) (i32.eqz (local.get $domains))) (then (return (i32.const 0))))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (call $proof_array_set (local.get $b) (local.get $domains) (local.get $i)
        (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))))
      (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 12))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (local.set $major (call $proof_make_two (local.get $b) (global.get $PROOF_TERM_INDUCTIVE)
      (local.get $owner) (call $proof_array_get (local.get $b) (local.get $s) (i32.const 5))))
    (local.set $major (call $proof_rec_apply_vars (local.get $b) (local.get $major)
      (i32.add (i32.add (local.get $p) (local.get $extra)) (local.get $n)) (i32.const 0) (local.get $p)))
    (local.set $major (call $proof_rec_apply_vars (local.get $b) (local.get $major)
      (local.get $n) (i32.const 0) (local.get $n)))
    (local.set $t (call $proof_make_two (local.get $b) (global.get $PROOF_TERM_PRODUCT)
      (local.get $major) (call $proof_array_get (local.get $b) (local.get $s) (i32.const 9))))
    (call $proof_rec_wrap (local.get $b) (local.get $domains) (local.get $n) (local.get $t)
      (global.get $PROOF_TERM_PRODUCT)))

  ;; Apply the family's motive to the indices of a checked family application
  ;; and its inhabitant. Both input terms live at the supplied prefix depth.
  (func $proof_rec_motive_application
    (param $b i32) (param $s i32) (param $family i32) (param $value i32) (param $depth i32)
    (result i32) (local $head i32) (local $position i32) (local $p i32) (local $i i32) (local $t i32)
    (local.set $head (call $proof_application_head (local.get $b) (local.get $family)))
    (local.set $position (call $proof_rec_group_position (local.get $b)
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 0))
      (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 8)))))
    (if (i32.or (i32.lt_s (local.get $position) (i32.const 0))
      (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 4)))
        (global.get $PROOF_TERM_INDUCTIVE))) (then (return (i32.const 0))))
    (local.set $p (call $proof_array_get (local.get $b) (local.get $s) (i32.const 1)))
    (local.set $t (call $proof_rec_bound (local.get $b)
      (i32.sub (i32.sub (local.get $depth) (i32.add (local.get $p) (local.get $position))) (i32.const 1))))
    (local.set $i (local.get $p))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (call $proof_application_count (local.get $b) (local.get $family))))
      (local.set $t (call $proof_rec_apply (local.get $b) (local.get $t)
        (call $proof_application_argument (local.get $b) (local.get $family) (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (call $proof_rec_apply (local.get $b) (local.get $t) (local.get $value)))

  ;; An induction hypothesis, or its recursive proof, for a strictly positive
  ;; recursive field. Function-valued fields get a Pi/lambda over their domain.
  (func $proof_rec_hypothesis
    (param $b i32) (param $s i32) (param $type i32) (param $value i32)
    (param $depth i32) (param $rhs i32) (result i32)
    (local $n i32) (local $domains i32) (local $i i32) (local $t i32)
    (local $head i32) (local $pos i32) (local $p i32) (local $prefix i32)
    (local.set $n (call $proof_product_count (local.get $b) (local.get $type)))
    (local.set $domains (call $proof_make_array (local.get $b) (local.get $n)))
    (if (i32.eqz (local.get $domains)) (then (return (i32.const 0))))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (call $proof_array_set (local.get $b) (local.get $domains) (local.get $i)
        (call $proof_load (local.get $b) (i32.add (local.get $type) (i32.const 8))))
      (local.set $type (call $proof_load (local.get $b) (i32.add (local.get $type) (i32.const 12))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (local.set $value (call $proof_shift (local.get $b) (local.get $value) (local.get $n) (i32.const 0) (i32.const 0)))
    (local.set $value (call $proof_rec_apply_vars (local.get $b) (local.get $value) (local.get $n) (i32.const 0) (local.get $n)))
    (local.set $depth (i32.add (local.get $depth) (local.get $n)))
    (if (local.get $rhs) (then
      (local.set $head (call $proof_application_head (local.get $b) (local.get $type)))
      (local.set $pos (call $proof_rec_group_position (local.get $b)
        (call $proof_array_get (local.get $b) (local.get $s) (i32.const 0))
        (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 8)))))
      (if (i32.lt_s (local.get $pos) (i32.const 0)) (then (return (i32.const 0))))
      (local.set $t (call $proof_make_two (local.get $b) (global.get $PROOF_TERM_GLOBAL)
        (call $proof_array_get (local.get $b)
          (call $proof_array_get (local.get $b) (local.get $s) (i32.const 8)) (local.get $pos))
        (call $proof_array_get (local.get $b) (local.get $s) (i32.const 6))))
      (local.set $p (call $proof_array_get (local.get $b) (local.get $s) (i32.const 1)))
      (local.set $prefix (i32.add (local.get $p) (i32.add
        (call $proof_array_get (local.get $b) (local.get $s) (i32.const 2))
        (call $proof_array_get (local.get $b) (local.get $s) (i32.const 3)))))
      (local.set $t (call $proof_rec_apply_vars (local.get $b) (local.get $t) (local.get $depth) (i32.const 0) (local.get $prefix)))
      (local.set $i (local.get $p))
      (block $args_done (loop $args_next
        (br_if $args_done (i32.ge_u (local.get $i) (call $proof_application_count (local.get $b) (local.get $type))))
        (local.set $t (call $proof_rec_apply (local.get $b) (local.get $t)
          (call $proof_application_argument (local.get $b) (local.get $type) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $args_next)))
      (local.set $t (call $proof_rec_apply (local.get $b) (local.get $t) (local.get $value))))
    (else (local.set $t (call $proof_rec_motive_application (local.get $b) (local.get $s)
      (local.get $type) (local.get $value) (local.get $depth)))))
    (call $proof_rec_wrap (local.get $b) (local.get $domains) (local.get $n) (local.get $t)
      (if (result i32) (local.get $rhs) (then (global.get $PROOF_TERM_LAMBDA)) (else (global.get $PROOF_TERM_PRODUCT)))))

  ;; mode 0: minor-premise type; 1: computation RHS; 2: required RHS type.
  ;; Prefix contains params, all motives, and either preceding or all minors.
  (func $proof_rec_constructor
    (param $b i32) (param $s i32) (param $owner i32) (param $ordinal i32)
    (param $minor i32) (param $mode i32) (param $work i32) (result i32)
    (local $d i32) (local $ctor i32) (local $t i32) (local $fields i32) (local $domains i32)
    (local $ihs i32) (local $ihcount i32) (local $i i32) (local $p i32) (local $m i32)
    (local $prefix i32) (local $depth i32) (local $domain i32) (local $value i32)
    (local $result i32) (local $ih i32) (local $group i32)
    (local.set $d (call $proof_declaration_reference (local.get $b) (local.get $owner)))
    (local.set $ctor (call $proof_array_get (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 24))) (local.get $ordinal)))
    (local.set $p (call $proof_array_get (local.get $b) (local.get $s) (i32.const 1)))
    (local.set $m (call $proof_array_get (local.get $b) (local.get $s) (i32.const 2)))
    (local.set $group (call $proof_array_get (local.get $b) (local.get $s) (i32.const 0)))
    (local.set $prefix (i32.add (i32.add (local.get $p) (local.get $m))
      (if (result i32) (local.get $mode)
        (then (call $proof_array_get (local.get $b) (local.get $s) (i32.const 3))) (else (local.get $minor)))))
    (local.set $t (call $proof_instantiate_term_universes (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $ctor) (i32.const 8)))
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 5)) (local.get $work)))
    (local.set $t (call $proof_rec_drop_products (local.get $b) (local.get $t) (local.get $p)))
    (local.set $t (call $proof_shift (local.get $b) (local.get $t) (i32.sub (local.get $prefix) (local.get $p)) (i32.const 0) (i32.const 0)))
    (local.set $fields (call $proof_product_count (local.get $b) (local.get $t)))
    (local.set $domains (call $proof_make_array (local.get $b) (local.get $fields)))
    (local.set $ihs (call $proof_make_array (local.get $b) (local.get $fields)))
    (if (i32.or (i32.eqz (local.get $domains)) (i32.eqz (local.get $ihs))) (then (return (i32.const 0))))
    (block $fields_done (loop $fields_next
      (br_if $fields_done (i32.ge_u (local.get $i) (local.get $fields)))
      (call $proof_array_set (local.get $b) (local.get $domains) (local.get $i)
        (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))))
      (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 12))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $fields_next)))
    (local.set $depth (i32.add (local.get $prefix) (local.get $fields)))
    (if (i32.eq (local.get $mode) (i32.const 1))
      (then (local.set $result (call $proof_rec_bound (local.get $b)
        (i32.sub (i32.sub (local.get $depth) (i32.add (i32.add (local.get $p) (local.get $m)) (local.get $minor))) (i32.const 1))))
        (local.set $result (call $proof_rec_apply_vars (local.get $b) (local.get $result)
          (local.get $depth) (local.get $prefix) (local.get $fields))))
      (else
        (local.set $value (call $proof_make_three (local.get $b) (global.get $PROOF_TERM_CONSTRUCTOR)
          (local.get $owner) (local.get $ordinal) (call $proof_array_get (local.get $b) (local.get $s) (i32.const 5))))
        (local.set $value (call $proof_rec_apply_vars (local.get $b) (local.get $value)
          (local.get $depth) (i32.const 0) (local.get $p)))
        (local.set $value (call $proof_rec_apply_vars (local.get $b) (local.get $value)
          (local.get $depth) (local.get $prefix) (local.get $fields)))
        (local.set $result (call $proof_rec_motive_application (local.get $b) (local.get $s)
          (local.get $t) (local.get $value) (local.get $depth)))))
    (local.set $i (i32.const 0))
    (if (i32.ne (local.get $mode) (i32.const 2)) (then
      (block $ih_done (loop $ih_next
        (br_if $ih_done (i32.ge_u (local.get $i) (local.get $fields)))
        (local.set $domain (call $proof_array_get (local.get $b) (local.get $domains) (local.get $i)))
        (if (call $proof_term_contains_mutual (local.get $b) (local.get $domain) (local.get $group)) (then
          (local.set $domain (call $proof_shift (local.get $b) (local.get $domain)
            (i32.sub (local.get $fields) (local.get $i)) (i32.const 0) (i32.const 0)))
          (local.set $value (call $proof_rec_bound (local.get $b)
            (i32.sub (i32.sub (local.get $fields) (local.get $i)) (i32.const 1))))
          (local.set $ih (call $proof_rec_hypothesis (local.get $b) (local.get $s)
            (local.get $domain) (local.get $value) (local.get $depth) (local.get $mode)))
          (if (i32.eqz (local.get $ih)) (then (return (i32.const 0))))
          (if (local.get $mode)
            (then (local.set $result (call $proof_rec_apply (local.get $b) (local.get $result) (local.get $ih))))
            (else (call $proof_array_set (local.get $b) (local.get $ihs) (local.get $ihcount)
              (call $proof_shift (local.get $b) (local.get $ih) (local.get $ihcount) (i32.const 0) (i32.const 0)))))
          (local.set $ihcount (i32.add (local.get $ihcount) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $ih_next)))))
    (if (i32.eqz (local.get $mode)) (then
      (local.set $result (call $proof_shift (local.get $b) (local.get $result) (local.get $ihcount) (i32.const 0) (i32.const 0)))
      (local.set $result (call $proof_rec_wrap (local.get $b) (local.get $ihs) (local.get $ihcount)
        (local.get $result) (global.get $PROOF_TERM_PRODUCT)))))
    (local.set $result (call $proof_rec_wrap (local.get $b) (local.get $domains) (local.get $fields) (local.get $result)
      (if (result i32) (i32.eq (local.get $mode) (i32.const 1))
        (then (global.get $PROOF_TERM_LAMBDA)) (else (global.get $PROOF_TERM_PRODUCT)))))
    (if (local.get $mode) (then
      (local.set $result (call $proof_rec_wrap (local.get $b)
        (call $proof_array_get (local.get $b) (local.get $s) (i32.const 4)) (local.get $prefix) (local.get $result)
        (if (result i32) (i32.eq (local.get $mode) (i32.const 1))
          (then (global.get $PROOF_TERM_LAMBDA)) (else (global.get $PROOF_TERM_PRODUCT)))))))
    (local.get $result))

  (func $proof_rec_universe_context
    (param $b i32) (param $source i32) (param $large i32) (result i32)
    (local $constraints i32) (local $out i32) (local $i i32)
    (local $c i32) (local $copy i32) (local $v i32)
    (if (i32.eqz (local.get $large)) (then (return (local.get $source))))
    (local.set $constraints (call $proof_load (local.get $b) (i32.add (local.get $source) (i32.const 12))))
    (local.set $out (call $proof_make_array (local.get $b)
      (call $proof_array_count (local.get $b) (local.get $constraints))))
    (if (i32.eqz (local.get $out)) (then (return (i32.const 0))))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (call $proof_array_count (local.get $b) (local.get $constraints))))
      (local.set $c (call $proof_array_get (local.get $b) (local.get $constraints) (local.get $i)))
      (local.set $copy (call $proof_allocate_record (local.get $b) (i32.const 7)
        (call $proof_load (local.get $b) (i32.add (local.get $c) (i32.const 4)))))
      (if (i32.eqz (local.get $copy)) (then (return (i32.const 0))))
      (memory.copy (call $abs (i32.add (local.get $b) (i32.add (local.get $copy) (i32.const 8))))
        (call $abs (i32.add (local.get $b) (i32.add (local.get $c) (i32.const 8)))) (i32.const 20))
      (local.set $v (call $proof_load (local.get $b) (i32.add (local.get $copy) (i32.const 8))))
      (if (local.get $v) (then (call $proof_store (local.get $b) (i32.add (local.get $copy) (i32.const 8))
        (i32.add (local.get $v) (i32.const 1)))))
      (local.set $v (call $proof_load (local.get $b) (i32.add (local.get $copy) (i32.const 20))))
      (if (local.get $v) (then (call $proof_store (local.get $b) (i32.add (local.get $copy) (i32.const 20))
        (i32.add (local.get $v) (i32.const 1)))))
      (call $proof_array_set (local.get $b) (local.get $out) (local.get $i) (local.get $copy))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (call $proof_make_two (local.get $b) (global.get $PROOF_RECORD_UNIVERSE_CONTEXT)
      (i32.add (call $proof_load (local.get $b) (i32.add (local.get $source) (i32.const 8))) (i32.const 1))
      (local.get $out)))

  (func $proof_rec_is_k (param $b i32) (param $d i32) (param $work i32) (result i32)
    (local $t i32) (local $ctors i32)
    (if (i32.ne (call $proof_array_count (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 28)))) (i32.const 1))
      (then (return (i32.const 0))))
    (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 12))))
    (local.set $t (call $proof_rec_drop_products (local.get $b) (local.get $t)
      (call $proof_product_count (local.get $b) (local.get $t))))
    (if (i32.eqz (call $proof_universe_is_zero (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))) (local.get $work)))
      (then (return (i32.const 0))))
    (local.set $ctors (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 24))))
    (if (i32.ne (call $proof_array_count (local.get $b) (local.get $ctors)) (i32.const 1))
      (then (return (i32.const 0))))
    (i32.eq (call $proof_product_count (local.get $b)
      (call $proof_load (local.get $b) (i32.add
        (call $proof_array_get (local.get $b) (local.get $ctors) (i32.const 0)) (i32.const 8))))
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 16)))))

  (func $proof_rec_name (param $b i32) (param $owner i32) (result i32)
    (local $prefix i32) (local $name i32)
    (local.set $prefix (call $proof_declaration_name (local.get $b)
      (call $proof_declaration_reference (local.get $b) (local.get $owner))))
    (if (i32.eqz (local.get $prefix)) (then (return (i32.const 0))))
    (local.set $name (call $proof_allocate_record (local.get $b) (i32.const 5)
      (global.get $PROOF_RECORD_NAME_STRING)))
    (if (i32.eqz (local.get $name)) (then (return (i32.const 0))))
    (call $proof_store (local.get $b) (i32.add (local.get $name) (i32.const 8)) (local.get $prefix))
    (call $proof_store (local.get $b) (i32.add (local.get $name) (i32.const 12)) (i32.const 3))
    (call $proof_store (local.get $b) (i32.add (local.get $name) (i32.const 16)) (i32.const 6514034))
    (local.get $name))

  ;; first=-1 regenerates against existing recursor indices, without mutation.
  (func $proof_rec_state
    (param $b i32) (param $group i32) (param $first i32) (param $work i32) (result i32)
    (local $s i32) (local $d i32) (local $p i32) (local $m i32) (local $n i32)
    (local $i i32) (local $j i32) (local $owner i32) (local $t i32) (local $large i32)
    (local $levels i32) (local $rec_levels i32) (local $u i32) (local $uc i32)
    (local $prefix i32) (local $ris i32) (local $minor i32) (local $ri i32)
    (local $saved_scope i32)
    (local.set $m (call $proof_array_count (local.get $b) (local.get $group)))
    (if (i32.eqz (local.get $m)) (then (return (i32.const 0))))
    (local.set $d (call $proof_declaration_reference (local.get $b)
      (call $proof_array_get (local.get $b) (local.get $group) (i32.const 0))))
    (local.set $p (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 16))))
    (local.set $saved_scope (global.get $proof_current_universe_context))
    (global.set $proof_current_universe_context
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 8))))
    (local.set $large (call $proof_inductive_allows_large_elimination (local.get $b) (local.get $d) (local.get $work)))
    (global.set $proof_current_universe_context (local.get $saved_scope))
    (if (global.get $proof_last_error_code) (then (return (i32.const 0))))
    (local.set $uc (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 8))))
    (local.set $u (call $proof_load (local.get $b) (i32.add (local.get $uc) (i32.const 8))))
    (local.set $uc (call $proof_rec_universe_context (local.get $b) (local.get $uc) (local.get $large)))
    (local.set $levels (call $proof_make_array (local.get $b) (local.get $u)))
    (local.set $rec_levels (call $proof_make_array (local.get $b) (i32.add (local.get $u) (local.get $large))))
    (local.set $ris (call $proof_make_array (local.get $b) (local.get $m)))
    (local.set $s (call $proof_make_array (local.get $b) (i32.const 11)))
    (if (i32.or (i32.or (i32.eqz (local.get $uc)) (i32.eqz (local.get $levels)))
      (i32.or (i32.eqz (local.get $s)) (i32.or (i32.eqz (local.get $rec_levels)) (i32.eqz (local.get $ris)))))
      (then (return (i32.const 0))))
    (block $levels_done (loop $levels_next
      (br_if $levels_done (i32.ge_u (local.get $i) (i32.add (local.get $u) (local.get $large))))
      (local.set $t (call $proof_make_universe_parameter (local.get $b) (local.get $i)))
      (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
      (call $proof_array_set (local.get $b) (local.get $rec_levels) (local.get $i) (local.get $t))
      (if (i32.ge_u (local.get $i) (local.get $large)) (then
        (call $proof_array_set (local.get $b) (local.get $levels)
          (i32.sub (local.get $i) (local.get $large)) (local.get $t))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $levels_next)))
    (local.set $i (i32.const 0))
    (block $count_done (loop $count_next
      (br_if $count_done (i32.ge_u (local.get $i) (local.get $m)))
      (local.set $owner (call $proof_array_get (local.get $b) (local.get $group) (local.get $i)))
      (local.set $d (call $proof_declaration_reference (local.get $b) (local.get $owner)))
      (local.set $n (i32.add (local.get $n) (call $proof_array_count (local.get $b)
        (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 24))))))
      (local.set $ri (if (result i32) (i32.eq (local.get $first) (i32.const -1))
        (then (call $proof_find_recursor (local.get $b) (local.get $owner)))
        (else (i32.add (local.get $first) (local.get $i)))))
      (if (i32.lt_s (local.get $ri) (i32.const 0)) (then (return (i32.const 0))))
      (call $proof_array_set (local.get $b) (local.get $ris) (local.get $i) (local.get $ri))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $count_next)))
    (local.set $prefix (call $proof_make_array (local.get $b)
      (i32.add (local.get $p) (i32.add (local.get $m) (local.get $n)))))
    (if (i32.eqz (local.get $prefix)) (then (return (i32.const 0))))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 0) (local.get $group))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 1) (local.get $p))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 2) (local.get $m))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 3) (local.get $n))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 4) (local.get $prefix))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 5) (local.get $levels))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 6) (local.get $rec_levels))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 7) (local.get $uc))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 8) (local.get $ris))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 9)
      (call $proof_make_one (local.get $b) (global.get $PROOF_TERM_SORT)
        (if (result i32) (local.get $large)
          (then (call $proof_array_get (local.get $b) (local.get $rec_levels) (i32.const 0)))
          (else (call $proof_make_universe_zero (local.get $b))))))
    (call $proof_array_set (local.get $b) (local.get $s) (i32.const 10) (local.get $work))
    (local.set $t (call $proof_instantiate_term_universes (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 12))) (local.get $levels) (local.get $work)))
    (local.set $i (i32.const 0))
    (block $params_done (loop $params_next
      (br_if $params_done (i32.ge_u (local.get $i) (local.get $p)))
      (call $proof_array_set (local.get $b) (local.get $prefix) (local.get $i)
        (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))))
      (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 12))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $params_next)))
    (local.set $i (i32.const 0))
    (block $motives_done (loop $motives_next
      (br_if $motives_done (i32.ge_u (local.get $i) (local.get $m)))
      (local.set $t (call $proof_rec_motive (local.get $b) (local.get $s)
        (call $proof_array_get (local.get $b) (local.get $group) (local.get $i)) (local.get $i) (local.get $work)))
      (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
      (call $proof_array_set (local.get $b) (local.get $prefix) (i32.add (local.get $p) (local.get $i)) (local.get $t))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $motives_next)))
    (local.set $i (i32.const 0))
    (block $families_done (loop $families_next
      (br_if $families_done (i32.ge_u (local.get $i) (local.get $m)))
      (local.set $owner (call $proof_array_get (local.get $b) (local.get $group) (local.get $i)))
      (local.set $d (call $proof_declaration_reference (local.get $b) (local.get $owner)))
      (local.set $j (i32.const 0))
      (block $minors_done (loop $minors_next
        (br_if $minors_done (i32.ge_u (local.get $j) (call $proof_array_count (local.get $b)
          (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 24))))))
        (if (i32.eqz (call $proof_work_debit (local.get $b) (local.get $work))) (then (return (i32.const 0))))
        (local.set $t (call $proof_rec_constructor (local.get $b) (local.get $s)
          (local.get $owner) (local.get $j) (local.get $minor) (i32.const 0) (local.get $work)))
        (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
        (call $proof_array_set (local.get $b) (local.get $prefix)
          (i32.add (i32.add (local.get $p) (local.get $m)) (local.get $minor)) (local.get $t))
        (local.set $minor (i32.add (local.get $minor) (i32.const 1)))
        (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $minors_next)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $families_next)))
    (local.get $s))

  (func $proof_rec_type (param $b i32) (param $s i32) (param $owner i32) (param $work i32) (result i32)
    (local $prefix i32) (local $t i32) (local $domains i32) (local $n i32)
    (local $i i32) (local $major i32)
    (local.set $prefix (call $proof_array_count (local.get $b)
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 4))))
    (local.set $t (call $proof_rec_motive (local.get $b) (local.get $s) (local.get $owner)
      (i32.sub (local.get $prefix) (call $proof_array_get (local.get $b) (local.get $s) (i32.const 1))) (local.get $work)))
    (local.set $n (call $proof_product_count (local.get $b) (local.get $t)))
    (local.set $domains (call $proof_make_array (local.get $b) (local.get $n)))
    (if (i32.eqz (local.get $domains)) (then (return (i32.const 0))))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $major (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))))
      (call $proof_array_set (local.get $b) (local.get $domains) (local.get $i) (local.get $major))
      (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 12))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (local.set $major (call $proof_shift (local.get $b) (local.get $major) (i32.const 1) (i32.const 0) (i32.const 0)))
    (local.set $t (call $proof_rec_motive_application (local.get $b) (local.get $s)
      (local.get $major) (call $proof_rec_bound (local.get $b) (i32.const 0)) (i32.add (local.get $prefix) (local.get $n))))
    (local.set $t (call $proof_rec_wrap (local.get $b) (local.get $domains) (local.get $n)
      (local.get $t) (global.get $PROOF_TERM_PRODUCT)))
    (call $proof_rec_wrap (local.get $b)
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 4)) (local.get $prefix)
      (local.get $t) (global.get $PROOF_TERM_PRODUCT)))

  (func $proof_rec_declaration
    (param $b i32) (param $s i32) (param $position i32) (param $work i32) (result i32)
    (local $owner i32) (local $d i32) (local $ctors i32) (local $rules i32)
    (local $i i32) (local $j i32) (local $minor i32) (local $rhs i32)
    (local $rule i32) (local $out i32) (local $type i32) (local $name i32) (local $k i32)
    (local.set $owner (call $proof_array_get (local.get $b)
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 0)) (local.get $position)))
    (local.set $d (call $proof_declaration_reference (local.get $b) (local.get $owner)))
    (local.set $ctors (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 24))))
    (local.set $rules (call $proof_make_array (local.get $b) (call $proof_array_count (local.get $b) (local.get $ctors))))
    (if (i32.eqz (local.get $rules)) (then (return (i32.const 0))))
    (block $prefix_done (loop $prefix_next
      (br_if $prefix_done (i32.ge_u (local.get $j) (local.get $position)))
      (local.set $minor (i32.add (local.get $minor) (call $proof_array_count (local.get $b)
        (call $proof_load (local.get $b) (i32.add (call $proof_declaration_reference (local.get $b)
          (call $proof_array_get (local.get $b)
            (call $proof_array_get (local.get $b) (local.get $s) (i32.const 0)) (local.get $j))) (i32.const 24))))))
      (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $prefix_next)))
    (block $rules_done (loop $rules_next
      (br_if $rules_done (i32.ge_u (local.get $i) (call $proof_array_count (local.get $b) (local.get $ctors))))
      (local.set $rhs (call $proof_rec_constructor (local.get $b) (local.get $s)
        (local.get $owner) (local.get $i) (i32.add (local.get $minor) (local.get $i)) (i32.const 1) (local.get $work)))
      (if (i32.eqz (local.get $rhs)) (then (return (i32.const 0))))
      (local.set $rule (call $proof_allocate_record (local.get $b) (i32.const 6) (global.get $PROOF_RECORD_RECURSOR_RULE)))
      (if (i32.eqz (local.get $rule)) (then (return (i32.const 0))))
      (call $proof_store (local.get $b) (i32.add (local.get $rule) (i32.const 8)) (local.get $owner))
      (call $proof_store (local.get $b) (i32.add (local.get $rule) (i32.const 12)) (local.get $i))
      (call $proof_store (local.get $b) (i32.add (local.get $rule) (i32.const 16))
        (i32.sub (call $proof_product_count (local.get $b) (call $proof_load (local.get $b)
          (i32.add (call $proof_array_get (local.get $b) (local.get $ctors) (local.get $i)) (i32.const 8))))
          (call $proof_array_get (local.get $b) (local.get $s) (i32.const 1))))
      (call $proof_store (local.get $b) (i32.add (local.get $rule) (i32.const 20)) (local.get $rhs))
      (call $proof_array_set (local.get $b) (local.get $rules) (local.get $i) (local.get $rule))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $rules_next)))
    (local.set $type (call $proof_rec_type (local.get $b) (local.get $s) (local.get $owner) (local.get $work)))
    (local.set $name (call $proof_rec_name (local.get $b) (local.get $owner)))
    (local.set $k (call $proof_rec_is_k (local.get $b) (local.get $d) (local.get $work)))
    (if (i32.or (i32.eqz (local.get $type)) (global.get $proof_last_error_code)) (then (return (i32.const 0))))
    (local.set $out (call $proof_allocate_record (local.get $b) (i32.const 13) (global.get $PROOF_RECORD_RECURSOR_DECLARATION)))
    (if (i32.eqz (local.get $out)) (then (return (i32.const 0))))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 8))
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 7)))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 12)) (local.get $type))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 16)) (local.get $owner))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 20))
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 0)))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 24))
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 1)))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 28))
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 20))))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 32))
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 2)))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 36))
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 3)))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 40)) (local.get $rules))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 44)) (local.get $k))
    (call $proof_store (local.get $b) (i32.add (local.get $out) (i32.const 48)) (local.get $name))
    (local.get $out))

  (func $proof_generate_recursors
    (param $b i32) (param $group i32) (param $work i32) (result i32)
    (local $old i32) (local $count i32) (local $m i32) (local $s i32)
    (local $out i32) (local $i i32) (local $d i32)
    (local.set $old (call $proof_load (local.get $b) (i32.const 12)))
    (local.set $count (call $proof_array_count (local.get $b) (local.get $old)))
    (local.set $m (call $proof_array_count (local.get $b) (local.get $group)))
    (local.set $s (call $proof_rec_state (local.get $b) (local.get $group) (local.get $count) (local.get $work)))
    (if (i32.eqz (local.get $s)) (then (return (i32.const 0))))
    (local.set $out (call $proof_make_array (local.get $b) (i32.add (local.get $count) (local.get $m))))
    (if (i32.eqz (local.get $out)) (then (return (i32.const 0))))
    (block $old_done (loop $old_next
      (br_if $old_done (i32.ge_u (local.get $i) (local.get $count)))
      (call $proof_array_set (local.get $b) (local.get $out) (local.get $i)
        (call $proof_array_get (local.get $b) (local.get $old) (local.get $i)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $old_next)))
    (local.set $i (i32.const 0))
    (block $new_done (loop $new_next
      (br_if $new_done (i32.ge_u (local.get $i) (local.get $m)))
      (local.set $d (call $proof_rec_declaration (local.get $b) (local.get $s) (local.get $i) (local.get $work)))
      (if (i32.eqz (local.get $d)) (then (return (i32.const 0))))
      (call $proof_array_set (local.get $b) (local.get $out) (i32.add (local.get $count) (local.get $i)) (local.get $d))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $new_next)))
    ;; Publish only after every member exists; the caller still owns a private
    ;; arena and must compact and independently recheck it before returning.
    (call $proof_store (local.get $b) (i32.const 12) (local.get $out))
    (local.get $out))

  (func $proof_validate_inductive_recursors (param $b i32) (param $work i32) (result i32)
    (local $ds i32) (local $i i32) (local $d i32) (local $group i32)
    (local $m i32) (local $j i32) (local $first i32) (local $owner i32)
    (local.set $ds (call $proof_load (local.get $b) (i32.const 12)))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (call $proof_array_count (local.get $b) (local.get $ds))))
      (if (i32.eqz (call $proof_work_debit (local.get $b) (local.get $work))) (then (return (i32.const 0))))
      (local.set $d (call $proof_array_get (local.get $b) (local.get $ds) (local.get $i)))
      (if (i32.eq (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 4)))
        (global.get $PROOF_RECORD_INDUCTIVE_DECLARATION)) (then
        (local.set $group (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 28))))
        (local.set $m (call $proof_array_count (local.get $b) (local.get $group)))
        (if (i32.eqz (local.get $m)) (then (return (i32.const 0))))
        (local.set $first (call $proof_array_get (local.get $b) (local.get $group) (i32.const 0)))
        (local.set $j (i32.const 0))
        (block $group_done (loop $group_next
          (br_if $group_done (i32.ge_u (local.get $j) (local.get $m)))
          (local.set $owner (call $proof_array_get (local.get $b) (local.get $group) (local.get $j)))
          (if (i32.or (i32.ne (local.get $owner) (i32.add (local.get $first) (local.get $j)))
            (i32.ne (call $proof_find_recursor (local.get $b) (local.get $owner))
              (i32.add (i32.add (local.get $first) (local.get $m)) (local.get $j))))
            (then (return (i32.const 0))))
          (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $group_next)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (i32.const 1))

  (func $proof_validate_recursor_declaration
    (param $b i32) (param $d i32) (param $index i32) (param $work i32) (result i32)
    (local $owner i32) (local $family i32) (local $group i32) (local $position i32)
    (local $s i32) (local $i i32) (local $j i32) (local $m i32) (local $minor i32)
    (local $expected i32) (local $actual i32) (local $rules i32) (local $rule i32)
    (local $empty i32) (local $type i32) (local $saved_scope i32) (local $saved_index i32)
    (local.set $owner (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 16))))
    (if (i32.ge_u (local.get $owner) (local.get $index)) (then (return (i32.const 0))))
    (local.set $family (call $proof_declaration_reference (local.get $b) (local.get $owner)))
    (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $family) (i32.const 4)))
      (global.get $PROOF_RECORD_INDUCTIVE_DECLARATION)) (then (return (i32.const 0))))
    (local.set $group (call $proof_load (local.get $b) (i32.add (local.get $family) (i32.const 28))))
    (local.set $position (call $proof_rec_group_position (local.get $b) (local.get $group) (local.get $owner)))
    (if (i32.or (i32.lt_s (local.get $position) (i32.const 0))
      (i32.ne (call $proof_find_recursor (local.get $b) (local.get $owner)) (local.get $index)))
      (then (return (i32.const 0))))
    (local.set $s (call $proof_rec_state (local.get $b) (local.get $group) (i32.const -1) (local.get $work)))
    (if (i32.eqz (local.get $s)) (then (return (i32.const 0))))
    (local.set $m (call $proof_array_count (local.get $b) (local.get $group)))
    ;; No exported computation rule participates in conversion until ALL
    ;; group members have matched independently generated graphs.
    (block $graphs_done (loop $graphs_next
      (br_if $graphs_done (i32.ge_u (local.get $i) (local.get $m)))
      (local.set $expected (call $proof_rec_declaration (local.get $b) (local.get $s) (local.get $i) (local.get $work)))
      (local.set $actual (call $proof_declaration_reference (local.get $b)
        (call $proof_array_get (local.get $b)
          (call $proof_array_get (local.get $b) (local.get $s) (i32.const 8)) (local.get $i))))
      (if (i32.or (i32.eqz (local.get $expected))
        (i32.eqz (call $proof_wire_graph_equal (local.get $b) (local.get $expected) (local.get $actual) (local.get $work))))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $graphs_next)))
    (local.set $saved_scope (global.get $proof_current_universe_context))
    (local.set $saved_index (global.get $proof_current_declaration_index))
    (global.set $proof_current_universe_context
      (call $proof_array_get (local.get $b) (local.get $s) (i32.const 7)))
    (local.set $empty (call $proof_make_array (local.get $b) (i32.const 0)))
    (if (i32.eqz (local.get $empty)) (then
      (global.set $proof_current_universe_context (local.get $saved_scope))
      (global.set $proof_current_declaration_index (local.get $saved_index))
      (return (i32.const 0))))
    (local.set $i (i32.const 0))
    (block $checked_done (loop $checked_next
      (br_if $checked_done (i32.ge_u (local.get $i) (local.get $m)))
      (global.set $proof_current_declaration_index (call $proof_array_get (local.get $b)
        (call $proof_array_get (local.get $b) (local.get $s) (i32.const 8)) (local.get $i)))
      (local.set $actual (call $proof_declaration_reference (local.get $b) (global.get $proof_current_declaration_index)))
      (local.set $type (call $proof_infer_term (local.get $b)
        (call $proof_load (local.get $b) (i32.add (local.get $actual) (i32.const 12)))
        (local.get $empty) (i32.const 0) (i32.const 0) (local.get $work)))
      (if (local.get $type) (then
        (local.set $type (call $proof_weak_head_normalize (local.get $b) (local.get $type)
          (local.get $empty) (i32.const 0) (i32.const 0) (local.get $work)))))
      (if (i32.or (i32.eqz (local.get $type))
        (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $type) (i32.const 4))) (global.get $PROOF_TERM_SORT)))
        (then (br $checked_done)))
      (local.set $rules (call $proof_load (local.get $b) (i32.add (local.get $actual) (i32.const 40))))
      (local.set $j (i32.const 0))
      (block $rhs_done (loop $rhs_next
        (br_if $rhs_done (i32.ge_u (local.get $j) (call $proof_array_count (local.get $b) (local.get $rules))))
        (local.set $rule (call $proof_array_get (local.get $b) (local.get $rules) (local.get $j)))
        (local.set $expected (call $proof_rec_constructor (local.get $b) (local.get $s)
          (call $proof_load (local.get $b) (i32.add (local.get $actual) (i32.const 16)))
          (local.get $j) (local.get $minor) (i32.const 2) (local.get $work)))
        (if (i32.or (i32.eqz (local.get $expected))
          (i32.eqz (call $proof_check_term (local.get $b)
            (call $proof_load (local.get $b) (i32.add (local.get $rule) (i32.const 20)))
            (local.get $expected) (local.get $empty) (i32.const 0) (i32.const 0) (local.get $work))))
          (then (br $checked_done)))
        (local.set $minor (i32.add (local.get $minor) (i32.const 1)))
        (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $rhs_next)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $checked_next)))
    (global.set $proof_current_universe_context (local.get $saved_scope))
    (global.set $proof_current_declaration_index (local.get $saved_index))
    (i32.eq (local.get $i) (local.get $m)))

  (func $proof_infer_recursor
    (param $b i32) (param $term i32) (param $context i32)
    (param $rdefs i32) (param $rsize i32) (param $work i32) (result i32)
    (local $index i32) (local $d i32) (local $levels i32)
    (if (i32.eqz (call $proof_work_debit (local.get $b) (local.get $work))) (then (return (i32.const 0))))
    (local.set $index (call $proof_load (local.get $b) (i32.add (local.get $term) (i32.const 8))))
    (if (i32.ge_u (local.get $index) (call $proof_array_count (local.get $b)
      (call $proof_load (local.get $b) (i32.const 12)))) (then (return (i32.const 0))))
    (local.set $d (call $proof_declaration_reference (local.get $b) (local.get $index)))
    (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 4)))
      (global.get $PROOF_RECORD_RECURSOR_DECLARATION)) (then (return (i32.const 0))))
    (local.set $levels (call $proof_load (local.get $b) (i32.add (local.get $term) (i32.const 12))))
    (if (i32.eqz (call $proof_check_universe_arguments (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 8))) (local.get $levels) (local.get $work)))
      (then (return (i32.const 0))))
    (call $proof_instantiate_term_universes (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 12))) (local.get $levels) (local.get $work)))

  ;; Copyright (c) 2018 Microsoft Corporation. All rights reserved.
  ;; Released under Apache 2.0 license as described in the file LICENSE.
  ;; Author: Leonardo de Moura
  ;; Adapted for SandScript by DevBlanket AB, 2026.
  ;; Lean src/kernel/inductive.h: inductive_reduce_rec, to_cnstr_when_K,
  ;; to_cnstr_when_structure; revision 6a10ac8c22beadecabdbb0919c2b50214762f91d.
  (func $proof_reduce_recursor
    (param $b i32) (param $term i32) (param $context i32)
    (param $rdefs i32) (param $rsize i32) (param $work i32) (result i32)
    (local $head i32) (local $d i32) (local $index i32) (local $owner i32)
    (local $p i32) (local $prefix i32) (local $major_index i32) (local $argc i32)
    (local $major i32) (local $ctor i32) (local $type i32) (local $type_head i32)
    (local $family i32) (local $candidate i32) (local $candidate_type i32)
    (local $fields i32) (local $i i32) (local $rules i32) (local $rule i32)
    (local $ordinal i32) (local $out i32) (local $level i32)
    (local $literal_tag i32)
    (local.set $head (call $proof_application_head (local.get $b) (local.get $term)))
    (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 4)))
      (global.get $PROOF_TERM_GLOBAL)) (then (return (local.get $term))))
    (local.set $index (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 8))))
    (if (i32.ge_u (local.get $index) (call $proof_array_count (local.get $b)
      (call $proof_load (local.get $b) (i32.const 12)))) (then (return (local.get $term))))
    (local.set $d (call $proof_declaration_reference (local.get $b) (local.get $index)))
    (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 4)))
      (global.get $PROOF_RECORD_RECURSOR_DECLARATION)) (then (return (local.get $term))))
    (if (i32.eqz (call $proof_work_debit (local.get $b) (local.get $work))) (then (return (i32.const 0))))
    (local.set $p (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 24))))
    (local.set $prefix (i32.add (local.get $p)
      (i32.add (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 32)))
        (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 36))))))
    (local.set $major_index (i32.add (local.get $prefix)
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 28)))))
    (local.set $argc (call $proof_application_count (local.get $b) (local.get $term)))
    (if (i32.le_u (local.get $argc) (local.get $major_index)) (then (return (local.get $term))))
    (local.set $owner (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 16))))
    (local.set $major (call $proof_weak_head_normalize (local.get $b)
      (call $proof_application_argument (local.get $b) (local.get $term) (local.get $major_index))
      (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
    (if (i32.eqz (local.get $major)) (then (return (i32.const 0))))
    (local.set $literal_tag
      (call $proof_load (local.get $b) (i32.add (local.get $major) (i32.const 4))))
    (local.set $major (call $proof_expand_literal (local.get $b) (local.get $major)
      (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
    (if (i32.eqz (local.get $major)) (then (return (i32.const 0))))
    ;; Nat's lazy successor view must not be folded straight back to a
    ;; literal by the accelerator. String.ofList needs its ordinary WHNF.
    (if (i32.eq (local.get $literal_tag) (global.get $PROOF_TERM_STRING_LITERAL))
      (then
        (local.set $major (call $proof_weak_head_normalize (local.get $b) (local.get $major)
          (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
        (if (i32.eqz (local.get $major)) (then (return (i32.const 0))))))
    (local.set $ctor (call $proof_application_head (local.get $b) (local.get $major)))
    (local.set $family (call $proof_declaration_reference (local.get $b) (local.get $owner)))
    (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $ctor) (i32.const 4)))
      (global.get $PROOF_TERM_CONSTRUCTOR)) (then
      (if (i32.eqz (i32.or
        (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 44)))
        (call $proof_is_nonrecursive_structure (local.get $b) (local.get $family))))
        (then (return (local.get $term))))
      (local.set $type (call $proof_infer_term (local.get $b) (local.get $major)
        (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
      (if (i32.eqz (local.get $type)) (then (return (i32.const 0))))
      (local.set $type (call $proof_weak_head_normalize (local.get $b) (local.get $type)
        (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
      (if (i32.eqz (local.get $type)) (then (return (i32.const 0))))
      (local.set $type_head (call $proof_application_head (local.get $b) (local.get $type)))
      (if (i32.or
        (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $type_head) (i32.const 4)))
          (global.get $PROOF_TERM_INDUCTIVE))
        (i32.or (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $type_head) (i32.const 8))) (local.get $owner))
          (i32.ne (call $proof_application_count (local.get $b) (local.get $type))
            (i32.add (local.get $p) (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 28)))))))
        (then (return (local.get $term))))
      (local.set $candidate (call $proof_make_three (local.get $b) (global.get $PROOF_TERM_CONSTRUCTOR)
        (local.get $owner) (i32.const 0)
        (call $proof_load (local.get $b) (i32.add (local.get $type_head) (i32.const 12)))))
      (local.set $i (i32.const 0))
      (block $params_done (loop $params_next
        (br_if $params_done (i32.ge_u (local.get $i) (local.get $p)))
        (local.set $candidate (call $proof_rec_apply (local.get $b) (local.get $candidate)
          (call $proof_application_argument (local.get $b) (local.get $type) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $params_next)))
      (if (i32.eqz (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 44)))) (then
        ;; Structure expansion never reveals hidden data from a proposition.
        (local.set $level (call $proof_infer_term (local.get $b) (local.get $type)
          (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
        (if (i32.eqz (local.get $level)) (then (return (i32.const 0))))
        (local.set $level (call $proof_weak_head_normalize (local.get $b) (local.get $level)
          (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
        (if (i32.eqz (local.get $level)) (then (return (i32.const 0))))
        (if (i32.or (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $level) (i32.const 4)))
          (global.get $PROOF_TERM_SORT))
          (call $proof_universe_is_zero (local.get $b)
            (call $proof_load (local.get $b) (i32.add (local.get $level) (i32.const 8))) (local.get $work)))
          (then (return (local.get $term))))
        (local.set $fields (i32.sub (call $proof_product_count (local.get $b)
          (call $proof_load (local.get $b) (i32.add (call $proof_array_get (local.get $b)
            (call $proof_load (local.get $b) (i32.add (local.get $family) (i32.const 24))) (i32.const 0)) (i32.const 8))))
          (local.get $p)))
        (local.set $i (i32.const 0))
        (block $fields_done (loop $fields_next
          (br_if $fields_done (i32.ge_u (local.get $i) (local.get $fields)))
          (local.set $candidate (call $proof_rec_apply (local.get $b) (local.get $candidate)
            (call $proof_make_three (local.get $b) (global.get $PROOF_TERM_PROJECTION)
              (local.get $owner) (local.get $i) (local.get $major))))
          (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $fields_next)))))
      (local.set $candidate_type (call $proof_infer_term (local.get $b) (local.get $candidate)
        (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
      (if (i32.eqz (local.get $candidate_type)) (then (return (i32.const 0))))
      ;; This guard is essential for K at nonuniform indices.
      (if (i32.eqz (call $proof_convertible (local.get $b) (local.get $type) (local.get $candidate_type)
        (local.get $context) (local.get $rdefs) (local.get $rsize) (local.get $work)))
        (then
          (if (global.get $proof_last_error_code) (then (return (i32.const 0))))
          (return (local.get $term))))
      (local.set $major (local.get $candidate))
      (local.set $ctor (call $proof_application_head (local.get $b) (local.get $major)))))
    (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $ctor) (i32.const 8))) (local.get $owner))
      (then (return (local.get $term))))
    (local.set $ordinal (call $proof_load (local.get $b) (i32.add (local.get $ctor) (i32.const 12))))
    (local.set $rules (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 40))))
    (if (i32.ge_u (local.get $ordinal) (call $proof_array_count (local.get $b) (local.get $rules)))
      (then (return (local.get $term))))
    (local.set $rule (call $proof_array_get (local.get $b) (local.get $rules) (local.get $ordinal)))
    (local.set $fields (call $proof_load (local.get $b) (i32.add (local.get $rule) (i32.const 16))))
    (if (i32.or
      (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $rule) (i32.const 8))) (local.get $owner))
      (i32.or (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $rule) (i32.const 12))) (local.get $ordinal))
        (i32.ne (call $proof_application_count (local.get $b) (local.get $major)) (i32.add (local.get $p) (local.get $fields)))))
      (then (return (local.get $term))))
    (local.set $out (call $proof_instantiate_term_universes (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $rule) (i32.const 20)))
      (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 12))) (local.get $work)))
    (local.set $i (i32.const 0))
    (block $prefix_done (loop $prefix_next
      (br_if $prefix_done (i32.ge_u (local.get $i) (local.get $prefix)))
      (local.set $out (call $proof_rec_apply (local.get $b) (local.get $out)
        (call $proof_application_argument (local.get $b) (local.get $term) (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $prefix_next)))
    (local.set $i (i32.const 0))
    (block $ctor_fields_done (loop $ctor_fields_next
      (br_if $ctor_fields_done (i32.ge_u (local.get $i) (local.get $fields)))
      (local.set $out (call $proof_rec_apply (local.get $b) (local.get $out)
        (call $proof_application_argument (local.get $b) (local.get $major) (i32.add (local.get $p) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $ctor_fields_next)))
    (local.set $i (i32.add (local.get $major_index) (i32.const 1)))
    (block $trailing_done (loop $trailing_next
      (br_if $trailing_done (i32.ge_u (local.get $i) (local.get $argc)))
      (local.set $out (call $proof_rec_apply (local.get $b) (local.get $out)
        (call $proof_application_argument (local.get $b) (local.get $term) (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $trailing_next)))
    (local.get $out))

  ;; Copyright (c) 2018 Microsoft Corporation. All rights reserved.
  ;; Released under Apache 2.0 license as described in the file LICENSE.
  ;; Author: Leonardo de Moura
  ;; Adapted for SandScript by DevBlanket AB, 2026.
  ;; Lean src/kernel/inductive.cpp: check_uniform_ind_occs, check_positivity,
  ;; check_inductive_types, check_constructors;
  ;; revision 6a10ac8c22beadecabdbb0919c2b50214762f91d.
  (func $proof_inductive_uniform
    (param $b i32) (param $t i32) (param $group i32) (param $p i32)
    (param $levels i32) (param $depth i32) (param $work i32) (result i32)
    (local $head i32) (local $tag i32) (local $i i32) (local $n i32)
    (local $arg i32) (local $child_depth i32)
    (if (i32.eqz (local.get $t)) (then (return (i32.const 1))))
    (if (i32.eqz (call $proof_work_debit (local.get $b) (local.get $work))) (then (return (i32.const 0))))
    (local.set $head (call $proof_application_head (local.get $b) (local.get $t)))
    (if (i32.and
      (i32.eq (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 4))) (global.get $PROOF_TERM_INDUCTIVE))
      (call $proof_array_contains (local.get $b) (local.get $group)
        (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 8)))))
      (then
        (local.set $n (call $proof_application_count (local.get $b) (local.get $t)))
        (if (i32.or (i32.lt_u (local.get $n) (local.get $p))
          (i32.or (i32.lt_u (local.get $depth) (local.get $p))
            (i32.eqz (call $proof_universe_arrays_equal (local.get $b) (local.get $levels)
              (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 12))) (local.get $work)))))
          (then (return (i32.const 0))))
        (block $args_done (loop $args_next
          (br_if $args_done (i32.ge_u (local.get $i) (local.get $n)))
          (local.set $arg (call $proof_application_argument (local.get $b) (local.get $t) (local.get $i)))
          (if (i32.lt_u (local.get $i) (local.get $p))
            (then (if (i32.or
              (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $arg) (i32.const 4))) (global.get $PROOF_TERM_BOUND))
              (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $arg) (i32.const 8)))
                (i32.sub (i32.sub (local.get $depth) (local.get $i)) (i32.const 1))))
              (then (return (i32.const 0))))))
          (if (i32.eqz (call $proof_inductive_uniform (local.get $b) (local.get $arg)
            (local.get $group) (local.get $p) (local.get $levels) (local.get $depth) (local.get $work)))
            (then (return (i32.const 0))))
          (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $args_next)))
        (return (i32.const 1))))
    (local.set $tag (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 4))))
    (local.set $n (call $proof_load (local.get $b) (local.get $t)))
    (local.set $i (i32.const 2))
    (block $children_done (loop $children_next
      (br_if $children_done (i32.ge_u (local.get $i) (local.get $n)))
      (if (call $proof_record_edge_kind (local.get $b) (local.get $t) (local.get $i)) (then
        (local.set $child_depth (local.get $depth))
        (if (i32.or
          (i32.and (i32.eq (local.get $i) (i32.const 3))
            (i32.or (i32.eq (local.get $tag) (global.get $PROOF_TERM_PRODUCT))
              (i32.eq (local.get $tag) (global.get $PROOF_TERM_LAMBDA))))
          (i32.and (i32.eq (local.get $i) (i32.const 4))
            (i32.eq (local.get $tag) (global.get $PROOF_TERM_LOCAL_DEFINITION))))
          (then (local.set $child_depth (i32.add (local.get $depth) (i32.const 1)))))
        (if (i32.eqz (call $proof_inductive_uniform (local.get $b)
          (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.mul (local.get $i) (i32.const 4))))
          (local.get $group) (local.get $p) (local.get $levels) (local.get $child_depth) (local.get $work)))
          (then (return (i32.const 0))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $children_next)))
    (i32.const 1))

  (func $proof_inductive_positive
    (param $b i32) (param $type i32) (param $group i32) (param $context i32) (param $work i32)
    (result i32) (local $head i32) (local $i i32) (local $domain i32)
    (if (i32.eqz (call $proof_term_contains_mutual (local.get $b) (local.get $type) (local.get $group)))
      (then (return (i32.const 1))))
    (local.set $type (call $proof_weak_head_normalize (local.get $b) (local.get $type)
      (local.get $context) (i32.const 0) (i32.const 0) (local.get $work)))
    (if (i32.eqz (local.get $type)) (then (return (i32.const 0))))
    (if (i32.eq (call $proof_load (local.get $b) (i32.add (local.get $type) (i32.const 4)))
      (global.get $PROOF_TERM_PRODUCT)) (then
      (local.set $domain (call $proof_load (local.get $b) (i32.add (local.get $type) (i32.const 8))))
      (if (call $proof_term_contains_mutual (local.get $b) (local.get $domain) (local.get $group))
        (then (return (i32.const 0))))
      (local.set $context (call $proof_context_extend (local.get $b) (local.get $context) (local.get $domain)))
      (if (i32.eqz (local.get $context)) (then (return (i32.const 0))))
      (return (call $proof_inductive_positive (local.get $b)
        (call $proof_load (local.get $b) (i32.add (local.get $type) (i32.const 12)))
        (local.get $group) (local.get $context) (local.get $work)))))
    (local.set $head (call $proof_application_head (local.get $b) (local.get $type)))
    (if (i32.or
      (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 4))) (global.get $PROOF_TERM_INDUCTIVE))
      (i32.eqz (call $proof_array_contains (local.get $b) (local.get $group)
        (call $proof_load (local.get $b) (i32.add (local.get $head) (i32.const 8))))))
      (then (return (i32.const 0))))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (call $proof_application_count (local.get $b) (local.get $type))))
      (if (call $proof_term_contains_mutual (local.get $b)
        (call $proof_application_argument (local.get $b) (local.get $type) (local.get $i)) (local.get $group))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (i32.const 1))

  (func $proof_validate_inductive_formation
    (param $b i32) (param $d i32) (param $work i32) (result i32)
    (local $group i32) (local $p i32) (local $t i32) (local $family_type i32)
    (local $sort i32) (local $level i32) (local $levels i32) (local $u i32)
    (local $i i32) (local $j i32) (local $other i32) (local $context i32)
    (local $ctors i32) (local $domain i32) (local $domain_type i32) (local $parameter_type i32)
    (local.set $group (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 28))))
    (local.set $p (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 16))))
    (local.set $family_type (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 12))))
    (local.set $sort (call $proof_rec_drop_products (local.get $b) (local.get $family_type)
      (call $proof_product_count (local.get $b) (local.get $family_type))))
    (local.set $level (call $proof_load (local.get $b) (i32.add (local.get $sort) (i32.const 8))))
    (local.set $u (call $proof_load (local.get $b) (i32.add
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 8))) (i32.const 8))))
    (local.set $levels (call $proof_make_array (local.get $b) (local.get $u)))
    (if (i32.eqz (local.get $levels)) (then (return (i32.const 0))))
    (block $levels_done (loop $levels_next
      (br_if $levels_done (i32.ge_u (local.get $i) (local.get $u)))
      (local.set $t (call $proof_make_universe_parameter (local.get $b) (local.get $i)))
      (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
      (call $proof_array_set (local.get $b) (local.get $levels) (local.get $i) (local.get $t))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $levels_next)))
    (local.set $i (i32.const 0))
    (block $mutual_done (loop $mutual_next
      (br_if $mutual_done (i32.ge_u (local.get $i) (call $proof_array_count (local.get $b) (local.get $group))))
      (local.set $other (call $proof_declaration_reference (local.get $b)
        (call $proof_array_get (local.get $b) (local.get $group) (local.get $i))))
      (if (i32.or
        (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $other) (i32.const 16))) (local.get $p))
        (i32.eqz (call $proof_wire_graph_equal (local.get $b)
          (call $proof_load (local.get $b) (i32.add (local.get $other) (i32.const 8)))
          (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 8))) (local.get $work))))
        (then (return (i32.const 0))))
      (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $other) (i32.const 12))))
      (local.set $parameter_type (local.get $family_type))
      (local.set $context (call $proof_make_array (local.get $b) (i32.const 0)))
      (local.set $j (i32.const 0))
      (block $params_done (loop $params_next
        (br_if $params_done (i32.ge_u (local.get $j) (local.get $p)))
        (local.set $domain (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))))
        (if (i32.eqz (call $proof_convertible (local.get $b) (local.get $domain)
          (call $proof_load (local.get $b) (i32.add (local.get $parameter_type) (i32.const 8)))
          (local.get $context) (i32.const 0) (i32.const 0) (local.get $work))) (then (return (i32.const 0))))
        (local.set $context (call $proof_context_extend (local.get $b) (local.get $context) (local.get $domain)))
        (local.set $parameter_type (call $proof_load (local.get $b) (i32.add (local.get $parameter_type) (i32.const 12))))
        (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 12))))
        (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $params_next)))
      (local.set $t (call $proof_rec_drop_products (local.get $b) (local.get $t)
        (call $proof_product_count (local.get $b) (local.get $t))))
      (if (i32.eqz (call $proof_universe_equal (local.get $b) (local.get $level)
        (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))) (local.get $work)))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $mutual_next)))
    (local.set $ctors (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 24))))
    (local.set $i (i32.const 0))
    (block $ctors_done (loop $ctors_next
      (br_if $ctors_done (i32.ge_u (local.get $i) (call $proof_array_count (local.get $b) (local.get $ctors))))
      (local.set $t (call $proof_load (local.get $b) (i32.add
        (call $proof_array_get (local.get $b) (local.get $ctors) (local.get $i)) (i32.const 8))))
      ;; This precedes all WHNF calls: beta reduction cannot hide bad uses.
      (if (i32.eqz (call $proof_inductive_uniform (local.get $b) (local.get $t)
        (local.get $group) (local.get $p) (local.get $levels) (i32.const 0) (local.get $work)))
        (then (return (i32.const 0))))
      (local.set $context (call $proof_make_array (local.get $b) (i32.const 0)))
      (local.set $parameter_type (local.get $family_type))
      (local.set $j (i32.const 0))
      (block $fields_done (loop $fields_next
        (br_if $fields_done (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 4)))
          (global.get $PROOF_TERM_PRODUCT)))
        (local.set $domain (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 8))))
        (if (i32.lt_u (local.get $j) (local.get $p)) (then
          (if (i32.eqz (call $proof_convertible (local.get $b) (local.get $domain)
            (call $proof_load (local.get $b) (i32.add (local.get $parameter_type) (i32.const 8)))
            (local.get $context) (i32.const 0) (i32.const 0) (local.get $work))) (then (return (i32.const 0))))
          (local.set $parameter_type (call $proof_load (local.get $b) (i32.add (local.get $parameter_type) (i32.const 12)))))
        (else
          (local.set $domain_type (call $proof_infer_term (local.get $b) (local.get $domain)
            (local.get $context) (i32.const 0) (i32.const 0) (local.get $work)))
          (if (i32.eqz (local.get $domain_type)) (then (return (i32.const 0))))
          (local.set $domain_type (call $proof_weak_head_normalize (local.get $b) (local.get $domain_type)
            (local.get $context) (i32.const 0) (i32.const 0) (local.get $work)))
          (if (i32.eqz (local.get $domain_type)) (then (return (i32.const 0))))
          (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $domain_type) (i32.const 4)))
            (global.get $PROOF_TERM_SORT)) (then (return (i32.const 0))))
          (if (i32.eqz (i32.or (call $proof_universe_is_zero (local.get $b) (local.get $level) (local.get $work))
            (call $proof_universe_less_equal (local.get $b)
              (call $proof_load (local.get $b) (i32.add (local.get $domain_type) (i32.const 8))) (local.get $level) (local.get $work))))
            (then (return (i32.const 0))))
          (if (i32.eqz (call $proof_inductive_positive (local.get $b) (local.get $domain)
            (local.get $group) (local.get $context) (local.get $work))) (then (return (i32.const 0))))))
        (local.set $context (call $proof_context_extend (local.get $b) (local.get $context) (local.get $domain)))
        (if (i32.eqz (local.get $context)) (then (return (i32.const 0))))
        (local.set $t (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 12))))
        (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $fields_next)))
      (if (i32.lt_u (local.get $j) (local.get $p)) (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $ctors_next)))
    (i32.const 1))

  ;; Check the new family's formation in a private builder arena before its
  ;; recursors exist. This is not an artifact acceptance entry point: callers
  ;; must generate the complete package and pass the ordinary artifact checker.
  (func $proof_check_inductive_input
    (param $b i32) (param $length i32) (param $d i32) (param $index i32) (param $work i32)
    (result i32) (local $empty i32) (local $t i32) (local $ctors i32) (local $i i32)
    (if (call $proof_validate_artifact (local.get $b) (local.get $length)) (then (return (i32.const 0))))
    (if (i32.eqz (call $proof_names_unique (local.get $b) (local.get $work))) (then (return (i32.const 0))))
    (global.set $proof_current_declaration_index (local.get $index))
    (global.set $proof_current_universe_context
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 8))))
    (if (i32.eqz (call $proof_universe_context_consistent (local.get $b) (global.get $proof_current_universe_context)))
      (then (return (i32.const 0))))
    (local.set $empty (call $proof_make_array (local.get $b) (i32.const 0)))
    (if (i32.eqz (local.get $empty)) (then (return (i32.const 0))))
    (local.set $t (call $proof_infer_term (local.get $b)
      (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 12)))
      (local.get $empty) (i32.const 0) (i32.const 0) (local.get $work)))
    (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
    (local.set $t (call $proof_weak_head_normalize (local.get $b) (local.get $t)
      (local.get $empty) (i32.const 0) (i32.const 0) (local.get $work)))
    (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
    (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 4))) (global.get $PROOF_TERM_SORT))
      (then (return (i32.const 0))))
    (if (i32.eqz (call $proof_validate_inductive_declaration (local.get $b) (local.get $d) (local.get $index) (local.get $work)))
      (then (return (i32.const 0))))
    (local.set $ctors (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 24))))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (call $proof_array_count (local.get $b) (local.get $ctors))))
      (local.set $t (call $proof_infer_term (local.get $b)
        (call $proof_load (local.get $b) (i32.add
          (call $proof_array_get (local.get $b) (local.get $ctors) (local.get $i)) (i32.const 8)))
        (local.get $empty) (i32.const 0) (i32.const 0) (local.get $work)))
      (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
      (local.set $t (call $proof_weak_head_normalize (local.get $b) (local.get $t)
        (local.get $empty) (i32.const 0) (i32.const 0) (local.get $work)))
      (if (i32.eqz (local.get $t)) (then (return (i32.const 0))))
      (if (i32.ne (call $proof_load (local.get $b) (i32.add (local.get $t) (i32.const 4))) (global.get $PROOF_TERM_SORT))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (i32.const 1))

  ;; Generalizing a builder's family universes changes the independently
  ;; bound recursor universe telescope. Rebuild only the new suffix; imported
  ;; declarations retain their exact references and every declaration index
  ;; stays fixed. Failure leaves the artifact header and all old arrays intact.
  (func $proof_regenerate_new_recursors
    (param $b i32) (param $first_new i32) (param $work i32) (result i32)
    (local $old i32) (local $out i32) (local $count i32) (local $i i32)
    (local $d i32) (local $group i32) (local $s i32) (local $j i32)
    (local $m i32) (local $owner i32) (local $index i32) (local $generated i32)
    (local.set $old (call $proof_load (local.get $b) (i32.const 12)))
    (local.set $count (call $proof_array_count (local.get $b) (local.get $old)))
    (if (i32.gt_u (local.get $first_new) (local.get $count))
      (then (return (i32.const 0))))
    (local.set $i (local.get $first_new))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $count)))
      (if (i32.eqz (call $proof_work_debit (local.get $b) (local.get $work)))
        (then (return (i32.const 0))))
      (local.set $d (call $proof_array_get (local.get $b) (local.get $old) (local.get $i)))
      (if (i32.eq
        (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 4)))
        (global.get $PROOF_RECORD_INDUCTIVE_DECLARATION)) (then
        (local.set $group
          (call $proof_load (local.get $b) (i32.add (local.get $d) (i32.const 28))))
        (if (i32.eq
          (call $proof_array_get (local.get $b) (local.get $group) (i32.const 0))
          (local.get $i)) (then
          (local.set $s
            (call $proof_rec_state (local.get $b) (local.get $group) (i32.const -1) (local.get $work)))
          (if (i32.eqz (local.get $s)) (then (return (i32.const 0))))
          (if (i32.eqz (local.get $out)) (then
            (local.set $out (call $proof_make_array (local.get $b) (local.get $count)))
            (if (i32.eqz (local.get $out)) (then (return (i32.const 0))))
            (call $proof_copy_bytes (local.get $b)
              (i32.add (local.get $out) (i32.const 12))
              (i32.add (local.get $old) (i32.const 12))
              (i32.mul (local.get $count) (i32.const 4)))))
          (local.set $m (call $proof_array_count (local.get $b) (local.get $group)))
          (local.set $j (i32.const 0))
          (block $members_done (loop $members_next
            (br_if $members_done (i32.ge_u (local.get $j) (local.get $m)))
            (local.set $owner (call $proof_array_get (local.get $b) (local.get $group) (local.get $j)))
            (local.set $index (call $proof_find_recursor (local.get $b) (local.get $owner)))
            (if (i32.or
              (i32.lt_u (local.get $owner) (local.get $first_new))
              (i32.or (i32.lt_s (local.get $index) (i32.const 0))
                (i32.lt_u (local.get $index) (local.get $first_new))))
              (then (return (i32.const 0))))
            (local.set $generated
              (call $proof_rec_declaration (local.get $b) (local.get $s) (local.get $j) (local.get $work)))
            (if (i32.eqz (local.get $generated)) (then (return (i32.const 0))))
            (call $proof_array_set (local.get $b) (local.get $out) (local.get $index) (local.get $generated))
            (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $members_next)))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (if (i32.eqz (local.get $out)) (then (return (local.get $old))))
    (call $proof_store (local.get $b) (i32.const 12) (local.get $out))
    (local.get $out))
