  ;; Elaboration phases: 45 stages owned scalar/name descriptors, 46 advances
  ;; pure frames, 47 hands the private result to compaction and durable checking.
  ;; No original pending input is changed before the shared publication phase.
  (global $PROOF_PH_ELABORATION_PREPARE i32 (i32.const 45))
  (global $PROOF_PH_ELABORATION_WORK i32 (i32.const 46))
  (global $PROOF_PH_ELABORATION_RESULT i32 (i32.const 47))

  (func $is_proof_elaboration_method (param $method i32) (result i32)
    (i32.or (i32.eq (local.get $method) (i32.const 0x271))
      (i32.or (i32.eq (local.get $method) (i32.const 0x275))
        (i32.eq (local.get $method) (i32.const 0x276)))))

  ;; Shared checked composition: phase35/bit26 owns this private root graph.
  ;; aux HEADER31/DATA0 = metadata, left, right, output handle, progress.
  ;; progress HEADER24/DATA0 = stage, record offset, field index, shape, options.
  ;; shape masks0 = left records length, right copied length, right delta,
  ;;                selected declaration count, actual artifact length.
  ;; options HEADER0/DATA8 = returnPhase|sequence<<8, declaration index,
  ;;                       DFS stack count, stack buffer DATA, chosen-left.
  ;; Stack frames are scalar triples: left ref, right ref, next field (0=enter).
  ;; The old identity check allows depth0..511 and tests identity/null before
  ;; rejecting depth512, hence space for513 frames. No partial output is ever
  ;; installed in state.word1. Transfer may temporarily wrap aux in word2.
  (func $proof_native_compose_begin
    (param $state i32) (param $left i32) (param $right i32)
    (param $sequence i32) (param $return_phase i32) (result i32)
    (local $owner i32) (local $a i32) (local $b i32)
    (local $ac i32) (local $bc i32) (local $chosen i32) (local $count i32)
    (local $alen i32) (local $blen i32) (local $delta i32) (local $same i32)
    (local $length i32) (local $capacity i32) (local $buffer i32) (local $handle i32)
    (local $stack i32) (local $shape i32) (local $options i32) (local $progress i32)
    (local $aux i32) (local $size i64) (local $allocation i64)
    (local.set $owner (call $proof_native_scope_union (local.get $left) (local.get $right)))
    (if (i32.eq (local.get $owner) (i32.const -1))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
    (local.set $a (call $proof_native_handle_artifact_base (local.get $left)))
    (local.set $b (call $proof_native_handle_artifact_base (local.get $right)))
    (local.set $ac (call $proof_array_count (local.get $a) (call $proof_load (local.get $a) (i32.const 12))))
    (local.set $bc (call $proof_array_count (local.get $b) (call $proof_load (local.get $b) (i32.const 12))))
    (local.set $chosen (i32.ge_u (local.get $ac) (local.get $bc)))
    (local.set $count (select (local.get $ac) (local.get $bc) (local.get $chosen)))
    (local.set $alen (call $proof_native_term_records_length (local.get $left)))
    (local.set $same (i32.eq (call $proof_native_handle_buffer (local.get $left))
      (call $proof_native_handle_buffer (local.get $right))))
    (if (i32.eqz (local.get $same)) (then
      (local.set $blen (call $proof_native_term_records_length (local.get $right)))
      (local.set $delta (local.get $alen))))
    (local.set $size (i64.add (i64.const 44)
      (i64.add (i64.mul (i64.extend_i32_u (local.get $sequence)) (i64.const 4))
        (i64.add (i64.extend_i32_u (local.get $alen))
          (i64.add (i64.extend_i32_u (local.get $blen))
            (i64.mul (i64.extend_i32_u (local.get $count)) (i64.const 4)))))))
    (if (i64.gt_u (local.get $size) (i64.const 0xffffffff))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
    (local.set $length (i32.wrap_i64 (local.get $size)))
    (local.set $size (i64.add (local.get $size) (i64.extend_i32_u (global.get $PROOF_WORK_RECORD_SIZE))))
    (if (i64.gt_u (local.get $size) (i64.const 0xffffffff))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
    (local.set $capacity (i32.wrap_i64 (local.get $size)))
    (local.set $allocation (i64.add (call $arraybuffer_size_i64 (local.get $capacity))
      (i64.add (i64.const 24)
        (i64.extend_i32_u (i32.mul (global.get $NATIVE_CONTINUATION_STATE_SIZE) (i32.const 6))))))
    (if (i32.and (i32.eqz (local.get $same))
        (i32.and (i32.ne (local.get $ac) (i32.const 0)) (i32.ne (local.get $bc) (i32.const 0))))
      (then
        (local.set $stack (i32.const 6156))
        (local.set $allocation (i64.add (local.get $allocation) (call $arraybuffer_size_i64 (local.get $stack))))))
    (if (i64.gt_u (local.get $allocation) (i64.const 0xffffffff))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
    (if (call $check_heap_overflow (i32.wrap_i64 (local.get $allocation))) (then (return (i32.const 2))))
    (local.set $buffer (call $allocate_arraybuffer_uninitialized (local.get $capacity)))
    (local.set $handle (call $proof_native_allocate_buffer_handle (local.get $buffer)
      (i32.add (i32.const 16) (i32.add (local.get $alen) (local.get $blen)))
      (global.get $PROOF_HANDLE_TERM) (local.get $owner)))
    ;; Frames are initialized completely when pushed; the unused stack is never read.
    (if (local.get $stack) (then (local.set $stack (call $allocate_arraybuffer_uninitialized (local.get $stack)))))
    (local.set $shape (call $allocate_native_continuation_state (i32.const 0) (i32.const 0)
      (local.get $alen) (local.get $blen) (local.get $delta) (local.get $count) (local.get $length)))
    (local.set $options (call $allocate_native_continuation_state (i32.const 0) (i32.const 8)
      (i32.or (local.get $return_phase) (i32.shl (local.get $sequence) (i32.const 8)))
      (i32.const 0) (i32.const 0) (local.get $stack) (local.get $chosen)))
    (local.set $progress (call $allocate_native_continuation_state (i32.const 24) (i32.const 0)
      (i32.const 0) (i32.add (i32.const 16) (local.get $alen)) (i32.const 2)
      (local.get $shape) (local.get $options)))
    (local.set $aux (call $allocate_native_continuation_state (i32.const 31) (i32.const 0)
      (call $native_continuation_state_get (local.get $state) (i32.const 2))
      (local.get $left) (local.get $right) (local.get $handle) (local.get $progress)))
    (call $native_continuation_state_set (local.get $state) (i32.const 2) (local.get $aux))
    (call $native_continuation_state_set (local.get $state) (i32.const 0)
      (i32.or (call $native_continuation_state_get (local.get $state) (i32.const 0)) (i32.const 0x04000000)))
    ;; The fixed header is private until stage3 writes its canonical contents.
    (memory.fill (call $abs (i32.add (local.get $buffer) (i32.const 4))) (i32.const 0) (i32.const 16))
    (call $proof_native_transfer_range_begin (local.get $state)
      (call $proof_native_handle_buffer (local.get $left)) (local.get $buffer)
      (i32.const 16) (i32.const 16) (local.get $alen)
      (i32.sub (local.get $capacity) (i32.add (i32.const 16) (local.get $alen))) (i32.const 35)))

  (func $proof_native_compose_step (param $state i32) (result i32)
    (local $aux i32) (local $progress i32) (local $shape i32) (local $options i32)
    (local $left i32) (local $right i32) (local $handle i32) (local $buffer i32)
    (local $base i32) (local $a i32) (local $b i32) (local $root i32) (local $decls i32)
    (local $stage i32) (local $offset i32) (local $field i32) (local $words i32)
    (local $delta i32) (local $sequence i32) (local $index i32) (local $count i32)
    (local $stack i32) (local $depth i32) (local $frame i32) (local $x i32) (local $y i32)
    (local $meta i32) (local $length i32)
    (local.set $aux (call $native_continuation_state_get (local.get $state) (i32.const 2)))
    (local.set $progress (call $native_continuation_state_get (local.get $aux) (i32.const 4)))
    (local.set $shape (call $native_continuation_state_get (local.get $progress) (i32.const 3)))
    (local.set $options (call $native_continuation_state_get (local.get $progress) (i32.const 4)))
    (local.set $left (call $native_continuation_state_get (local.get $aux) (i32.const 1)))
    (local.set $right (call $native_continuation_state_get (local.get $aux) (i32.const 2)))
    (local.set $handle (call $native_continuation_state_get (local.get $aux) (i32.const 3)))
    (local.set $buffer (call $proof_native_handle_buffer (local.get $handle)))
    (local.set $base (i32.add (local.get $buffer) (i32.const 4)))
    (local.set $root (call $proof_native_handle_root (local.get $handle)))
    (local.set $sequence (i32.and (i32.shr_u
      (call $native_continuation_state_get (local.get $options) (i32.const 0)) (i32.const 8)) (i32.const 1)))
    (local.set $decls (i32.add (local.get $root) (i32.add (i32.const 16) (i32.shl (local.get $sequence) (i32.const 2)))))
    (local.set $delta (call $native_continuation_state_get (local.get $shape) (i32.const 2)))
    (local.set $stage (call $native_continuation_state_get (local.get $progress) (i32.const 0)))
    (if (i32.eqz (local.get $stage)) (then
      (local.set $length (call $native_continuation_state_get (local.get $shape) (i32.const 1)))
      (if (i32.eqz (local.get $length)) (then
        (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 2))
        (return (i32.const 5))))
      (if (call $check_heap_overflow (i32.mul (global.get $NATIVE_CONTINUATION_STATE_SIZE) (i32.const 2)))
        (then (return (i32.const 2))))
      (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 1))
      (return (call $proof_native_transfer_range_begin (local.get $state)
        (call $proof_native_handle_buffer (local.get $right)) (local.get $buffer)
        (i32.const 16) (i32.add (i32.const 16) (local.get $delta))
        (local.get $length) (i32.const 0) (i32.const 35)))))
    (if (i32.eq (local.get $stage) (i32.const 1)) (then
      (local.set $offset (call $native_continuation_state_get (local.get $progress) (i32.const 1)))
      (if (i32.ge_u (local.get $offset) (local.get $root)) (then
        (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 2))
        (return (i32.const 5))))
      (local.set $field (call $native_continuation_state_get (local.get $progress) (i32.const 2)))
      (local.set $words (call $proof_load (local.get $base) (local.get $offset)))
      (if (i32.lt_u (local.get $field) (local.get $words))
        (then
          (if (call $proof_record_edge_kind (local.get $base) (local.get $offset) (local.get $field)) (then
            (local.set $index (i32.add (local.get $offset) (i32.shl (local.get $field) (i32.const 2))))
            (call $proof_store (local.get $base) (local.get $index)
              (call $proof_native_relocated_reference (call $proof_load (local.get $base) (local.get $index))
                (local.get $delta) (i32.const 0)))))
          (call $native_continuation_state_set (local.get $progress) (i32.const 2) (i32.add (local.get $field) (i32.const 1))))
        (else
          (call $native_continuation_state_set (local.get $progress) (i32.const 1)
            (i32.add (local.get $offset) (i32.shl (local.get $words) (i32.const 2))))
          (call $native_continuation_state_set (local.get $progress) (i32.const 2) (i32.const 2))))
      (return (i32.const 5))))
    (if (i32.eq (local.get $stage) (i32.const 2)) (then
      (local.set $index (call $native_continuation_state_get (local.get $options) (i32.const 1)))
      (local.set $count (call $native_continuation_state_get (local.get $shape) (i32.const 3)))
      (if (i32.ge_u (local.get $index) (local.get $count)) (then
        (call $native_continuation_state_set (local.get $options) (i32.const 1) (i32.const 0))
        (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 3))
        (return (i32.const 5))))
      (if (call $native_continuation_state_get (local.get $options) (i32.const 4))
        (then (local.set $a (call $proof_native_handle_artifact_base (local.get $left))) (local.set $delta (i32.const 0)))
        (else (local.set $a (call $proof_native_handle_artifact_base (local.get $right)))))
      (call $proof_store (local.get $base) (i32.add (local.get $decls) (i32.add (i32.const 12) (i32.shl (local.get $index) (i32.const 2))))
        (i32.add (call $proof_array_get (local.get $a) (call $proof_load (local.get $a) (i32.const 12)) (local.get $index))
          (local.get $delta)))
      (call $native_continuation_state_set (local.get $options) (i32.const 1) (i32.add (local.get $index) (i32.const 1)))
      (return (i32.const 5))))
    (if (i32.eq (local.get $stage) (i32.const 3)) (then
      (local.set $count (call $native_continuation_state_get (local.get $shape) (i32.const 3)))
      (call $proof_store (local.get $base) (local.get $root) (i32.add (i32.const 4) (local.get $sequence)))
      (call $proof_store (local.get $base) (i32.add (local.get $root) (i32.const 4))
        (select (global.get $PROOF_TERM_LOCAL_DEFINITION) (global.get $PROOF_TERM_APPLICATION) (local.get $sequence)))
      (call $proof_store (local.get $base) (i32.add (local.get $root) (i32.const 8)) (call $proof_native_handle_root (local.get $left)))
      (call $proof_store (local.get $base) (i32.add (local.get $root) (i32.const 12))
        (i32.add (call $proof_native_handle_root (local.get $right)) (local.get $delta)))
      ;; A sequence's trailing index is the zero already written by the transfer.
      (call $proof_store (local.get $base) (local.get $decls) (i32.add (local.get $count) (i32.const 3)))
      (call $proof_store (local.get $base) (i32.add (local.get $decls) (i32.const 4)) (global.get $PROOF_RECORD_ARRAY))
      (call $proof_store (local.get $base) (i32.add (local.get $decls) (i32.const 8)) (local.get $count))
      (call $proof_native_initialize_artifact_header (local.get $base)
        (call $native_continuation_state_get (local.get $shape) (i32.const 4)) (local.get $decls))
      (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 4))
      (return (i32.const 5))))
    (local.set $stack (call $native_continuation_state_get (local.get $options) (i32.const 3)))
    (if (i32.eq (local.get $stage) (i32.const 4)) (then
      (if (i32.eqz (local.get $stack)) (then
        (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 6))
        (return (i32.const 5))))
      (local.set $a (call $proof_native_handle_artifact_base (local.get $left)))
      (local.set $b (call $proof_native_handle_artifact_base (local.get $right)))
      (local.set $x (call $proof_load (local.get $a) (i32.const 12)))
      (local.set $y (call $proof_load (local.get $b) (i32.const 12)))
      (local.set $index (call $native_continuation_state_get (local.get $options) (i32.const 1)))
      (if (i32.or (i32.ge_u (local.get $index) (call $proof_array_count (local.get $a) (local.get $x)))
          (i32.ge_u (local.get $index) (call $proof_array_count (local.get $b) (local.get $y)))) (then
        (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 6))
        (return (i32.const 5))))
      (local.set $frame (i32.add (local.get $stack) (i32.const 4)))
      (call $proof_store (local.get $frame) (i32.const 0) (call $proof_array_get (local.get $a) (local.get $x) (local.get $index)))
      (call $proof_store (local.get $frame) (i32.const 4)
        (i32.add (call $proof_array_get (local.get $b) (local.get $y) (local.get $index)) (local.get $delta)))
      (call $proof_store (local.get $frame) (i32.const 8) (i32.const 0))
      (call $native_continuation_state_set (local.get $options) (i32.const 1) (i32.add (local.get $index) (i32.const 1)))
      (call $native_continuation_state_set (local.get $options) (i32.const 2) (i32.const 1))
      (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 5))
      (return (i32.const 5))))
    (if (i32.eq (local.get $stage) (i32.const 5)) (then
      (local.set $depth (call $native_continuation_state_get (local.get $options) (i32.const 2)))
      (if (i32.eqz (local.get $depth)) (then
        (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 4))
        (return (i32.const 5))))
      (local.set $frame (i32.add (i32.add (local.get $stack) (i32.const 4))
        (i32.mul (i32.sub (local.get $depth) (i32.const 1)) (i32.const 12))))
      (local.set $x (call $proof_load (local.get $frame) (i32.const 0)))
      (local.set $y (call $proof_load (local.get $frame) (i32.const 4)))
      (local.set $field (call $proof_load (local.get $frame) (i32.const 8)))
      (if (i32.eqz (local.get $field)) (then
        (if (i32.eq (local.get $x) (local.get $y)) (then
          (call $native_continuation_state_set (local.get $options) (i32.const 2) (i32.sub (local.get $depth) (i32.const 1)))
          (return (i32.const 5))))
        (if (i32.or (i32.eqz (local.get $x)) (i32.eqz (local.get $y)))
          (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
        (if (i32.gt_u (local.get $depth) (i32.const 512)) (then
          (global.set $proof_last_error_code (i32.const 29))
          (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
        (if (i32.or
            (i32.ne (call $proof_load (local.get $base) (local.get $x)) (call $proof_load (local.get $base) (local.get $y)))
            (i32.ne (call $proof_load (local.get $base) (i32.add (local.get $x) (i32.const 4)))
              (call $proof_load (local.get $base) (i32.add (local.get $y) (i32.const 4)))))
          (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
        (call $proof_store (local.get $frame) (i32.const 8) (i32.const 2))
        (return (i32.const 5))))
      (if (i32.ge_u (local.get $field) (call $proof_load (local.get $base) (local.get $x))) (then
        (call $native_continuation_state_set (local.get $options) (i32.const 2) (i32.sub (local.get $depth) (i32.const 1)))
        (return (i32.const 5))))
      (local.set $a (call $proof_load (local.get $base) (i32.add (local.get $x) (i32.shl (local.get $field) (i32.const 2)))))
      (local.set $b (call $proof_load (local.get $base) (i32.add (local.get $y) (i32.shl (local.get $field) (i32.const 2)))))
      (if (call $proof_record_edge_kind (local.get $base) (local.get $x) (local.get $field))
        (then
          (call $proof_store (local.get $frame) (i32.const 12) (local.get $a))
          (call $proof_store (local.get $frame) (i32.const 16) (local.get $b))
          (call $proof_store (local.get $frame) (i32.const 20) (i32.const 0))
          (call $native_continuation_state_set (local.get $options) (i32.const 2) (i32.add (local.get $depth) (i32.const 1))))
        (else (if (i32.ne (local.get $a) (local.get $b))
          (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))))
      (call $proof_store (local.get $frame) (i32.const 8) (i32.add (local.get $field) (i32.const 1)))
      (return (i32.const 5))))
    (local.set $length (call $native_continuation_state_get (local.get $shape) (i32.const 4)))
    (local.set $meta (call $native_continuation_state_get (local.get $aux) (i32.const 0)))
    (call $native_continuation_state_set (local.get $state) (i32.const 2) (local.get $meta))
    (call $native_continuation_state_set (local.get $state) (i32.const 1) (local.get $handle))
    (call $native_continuation_state_set (local.get $state) (i32.const 3) (i32.const 0))
    (call $native_continuation_state_set (local.get $state) (i32.const 4) (i32.const 0))
    (call $native_continuation_state_set (local.get $meta) (i32.const 3) (local.get $length))
    (call $native_continuation_state_set (local.get $state) (i32.const 0)
      (i32.and (call $native_continuation_state_get (local.get $state) (i32.const 0)) (i32.const 0xfbffffff)))
    (call $proof_native_phase (local.get $state)
      (i32.and (call $native_continuation_state_get (local.get $options) (i32.const 0)) (i32.const 255)))
    (global.set $proof_current_artifact_length (local.get $length))
    (global.set $proof_current_declaration_index (i32.const -1))
    (global.set $proof_current_universe_context (i32.const 0))
    (global.set $proof_scratch_cursor (local.get $length))
    (global.set $proof_scratch_limit (i32.load (call $abs (local.get $buffer))))
    (i32.const 5))

  (func $proof_native_elaboration_compose
    (param $state i32) (param $left i32) (param $right i32) (param $sequence i32) (result i32)
    (call $proof_native_compose_begin (local.get $state) (local.get $left)
      (local.get $right) (local.get $sequence) (i32.const 45)))

  ;; Builder metadata extensions remain rooted through meta.word4 throughout.
  (func $proof_native_elaboration_start_checked
    (param $state i32) (param $source_handle i32) (param $expected_handle i32) (result i32)
    (if (i32.or (i32.eqz (call $proof_native_term_handle_valid (local.get $source_handle)))
                (i32.eqz (call $proof_native_term_handle_valid (local.get $expected_handle))))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
    (call $proof_native_elaboration_compose (local.get $state) (local.get $source_handle)
      (local.get $expected_handle) (i32.const 0)))

  (func $proof_native_elaboration_prepare
    (param $state i32) (param $method i32) (param $argc i32) (param $args i32) (result i32)
    (local $required i32) (local $left i32) (local $right i32) (local $right_slot i32)
    (local $index i32) (local $slot i32) (local $sequence i32)
    (local.set $required (select (i32.const 2) (select (i32.const 5) (i32.const 7)
      (i32.eq (local.get $method) (i32.const 0x275))) (i32.eq (local.get $method) (i32.const 0x271))))
    (if (i32.or (i32.lt_u (local.get $argc) (local.get $required))
      (i32.and (i32.ne (local.get $method) (i32.const 0x271)) (i32.ne (local.get $argc) (local.get $required))))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_MISSING_ARGUMENT)))))
    (local.set $right_slot (i32.add (local.get $args) (i32.mul (global.get $VALUE_SIZE)
      (select (i32.const 4) (i32.const 1) (i32.eq (local.get $method) (i32.const 0x275))))))
    (if (i32.or (i32.ne (call $value_type (local.get $args)) (global.get $TYPE_THEOREM))
                (i32.ne (call $value_type (local.get $right_slot)) (global.get $TYPE_THEOREM)))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
    (local.set $left (call $value_data_lo (local.get $args)))
    (local.set $right (call $value_data_lo (local.get $right_slot)))
    (local.set $sequence (i32.ne (local.get $method) (i32.const 0x271)))
    (if (i32.or (i32.eqz (call $proof_native_term_handle_valid (local.get $left)))
      (i32.eqz (if (result i32) (local.get $sequence)
        (then (call $proof_native_sequence_handle_valid (local.get $right)))
        (else (call $proof_native_term_handle_valid (local.get $right))))))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
    (if (local.get $sequence) (then
      (block $done (loop $next
        (br_if $done (i32.ge_u (local.get $index) (i32.const 3)))
        (local.set $slot (i32.add (local.get $args) (i32.mul (global.get $VALUE_SIZE)
          (i32.add (local.get $index) (select (i32.const 1) (i32.const 2)
            (i32.eq (local.get $method) (i32.const 0x275)))))))
        (if (i32.ne (call $value_type (local.get $slot)) (global.get $TYPE_ARRAY))
          (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
        (local.set $index (i32.add (local.get $index) (i32.const 1))) (br $next)))))
    (call $proof_native_elaboration_compose (local.get $state) (local.get $left) (local.get $right) (local.get $sequence)))

  ;; Only this helper derives pending-array element addresses. They are never
  ;; stored in pure frames or the artifact descriptor.
  (func $proof_native_elaboration_input_array
    (param $method i32) (param $args i32) (param $index i32) (result i32)
    (call $value_data_lo (i32.add (local.get $args) (i32.mul (global.get $VALUE_SIZE)
      (i32.add (local.get $index) (select (i32.const 1) (i32.const 2)
        (i32.eq (local.get $method) (i32.const 0x275))))))))

  (func $proof_native_elaboration_transition
    (param $state i32) (param $method i32) (param $args i32) (result i32)
    (local $phase i32) (local $meta i32) (local $handle i32) (local $base i32)
    (local $capacity i32) (local $used i32) (local $driver i32) (local $work i32)
    (local $status i32) (local $root i32) (local $context i32) (local $error i32)
    (local $index i32) (local $element i32) (local $byte i32) (local $array i32)
    (local $target i32) (local $count i32) (local $slot i32) (local $value i32)
    (local $name i32) (local $length i32) (local $required i32) (local $sequence i32)
    (local $required64 i64)
    (local.set $phase (i32.and (call $native_continuation_state_get (local.get $state) (i32.const 0)) (i32.const 255)))
    (local.set $meta (call $native_continuation_state_get (local.get $state) (i32.const 2)))
    (local.set $handle (call $native_continuation_state_get (local.get $state) (i32.const 1)))
    (local.set $base (call $proof_native_handle_artifact_base (local.get $handle)))
    (local.set $capacity (i32.load (call $abs (call $proof_native_handle_buffer (local.get $handle)))))
    (local.set $used (call $native_continuation_state_get (local.get $meta) (i32.const 3)))
    (local.set $driver (call $native_continuation_state_get (local.get $state) (i32.const 3)))
    (local.set $work (call $native_continuation_state_get (local.get $state) (i32.const 4)))
    (if (i32.eq (local.get $phase) (i32.const 47)) (then
      (local.set $root (call $native_continuation_state_get (local.get $meta) (i32.const 1)))
      (if (call $is_proof_builder_method (local.get $method))
        (then (return (call $proof_native_builder_elaboration_result (local.get $state) (local.get $root) (local.get $used)))))
      (call $native_continuation_state_set (local.get $state) (i32.const 3) (i32.const 0))
      (call $native_continuation_state_set (local.get $state) (i32.const 4) (i32.const 0))
      (call $proof_native_phase (local.get $state) (i32.const 35))
      (return (i32.const 5))))
    (if (i32.eq (local.get $phase) (i32.const 46)) (then
      (if (i32.eq (call $proof_load (local.get $base) (i32.add (local.get $work) (i32.const 28))) (i32.const 3)) (then
        (local.set $status (call $proof_native_op_grow (local.get $state) (i32.const 0)))
        (if (i32.eq (local.get $status) (i32.const 5)) (then (return (i32.const 5))))
        (if (i32.eqz (local.get $status)) (then (return (i32.const 2))))
        (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
      (call $proof_work_resume (local.get $base) (local.get $work) (local.get $capacity))
      (global.set $proof_last_error_offset (call $proof_native_op_error_offset (local.get $meta)))
      (local.set $status (call $proof_work_step (local.get $base) (local.get $work)))
      (call $proof_work_save (local.get $base) (local.get $work))
      (call $native_continuation_state_set (local.get $meta) (i32.const 3) (global.get $proof_scratch_cursor))
      (call $proof_native_op_set_error_offset (local.get $meta) (global.get $proof_last_error_offset))
      (if (i32.or (i32.eqz (local.get $status)) (i32.eq (local.get $status) (i32.const 3))) (then (return (i32.const 5))))
      (local.set $error (global.get $proof_last_error_code))
      (local.set $root (call $proof_load (local.get $base) (i32.add (local.get $work) (i32.const 12))))
      (if (i32.or (local.get $error) (i32.eqz (local.get $root)))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
      (call $native_continuation_state_set (local.get $meta) (i32.const 1) (local.get $root))
      (call $proof_native_phase (local.get $state) (i32.const 47))
      (return (i32.const 5))))
    (global.set $proof_current_artifact_length (local.get $used))
    (global.set $proof_current_declaration_index (i32.const -1))
    (global.set $proof_current_universe_context (i32.const 0))
    (global.set $proof_scratch_cursor (local.get $used))
    (global.set $proof_scratch_limit (local.get $capacity))
    (global.set $proof_last_error_code (i32.const 0))
    (global.set $proof_last_error_offset (i32.const 0))
    (global.set $proof_last_inferred_type (i32.const 0))
    (global.set $proof_last_expected_type (i32.const 0))
    (local.set $sequence (i32.or (i32.eq (local.get $method) (i32.const 0x275)) (i32.eq (local.get $method) (i32.const 0x276))))
    (local.set $required64 (i64.const 65536))
    ;; Array allocation is one staging transition; reserve its full size before
    ;; writing anything so growth never replays a name byte or a proof step.
    (if (i32.and (i32.ne (local.get $driver) (i32.const 0)) (local.get $sequence)) (then
      (local.set $index (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 1)))
      (if (i32.lt_u (local.get $index) (i32.const 3)) (then
        (local.set $array (call $proof_native_elaboration_input_array (local.get $method) (local.get $args) (local.get $index)))
        (local.set $count (i32.load (call $abs (i32.add (local.get $array) (i32.const 8)))))
        (local.set $target (call $proof_array_get (local.get $base) (local.get $driver) (i32.add (local.get $index) (i32.const 5))))
        (if (i32.eqz (local.get $target))
          (then (local.set $required64 (i64.add (i64.mul (i64.extend_i32_u (local.get $count)) (i64.const 4)) (i64.const 65536)))))
        (local.set $element (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 2)))
        (if (i32.and (i32.lt_u (local.get $element) (local.get $count))
          (i32.and (i32.eq (local.get $method) (i32.const 0x275)) (i32.ne (local.get $index) (i32.const 1)))) (then
          (local.set $slot (call $proof_native_array_value_address (local.get $array) (local.get $element)))
          (if (i32.ne (call $value_type (local.get $slot)) (global.get $TYPE_STRING))
            (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
          (local.set $name (call $value_data_lo (local.get $slot)))
          (local.set $length (call $read_string_len (local.get $name)))
          (local.set $required64 (i64.add (i64.mul (i64.extend_i32_u (local.get $length)) (i64.const 4)) (local.get $required64)))))))))
    (if (i64.gt_u (i64.add (i64.extend_i32_u (local.get $used)) (local.get $required64)) (i64.const 0xffffffff))
      (then
        (global.set $proof_last_error_code (i32.const 20))
        (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
    (local.set $required (i32.wrap_i64 (local.get $required64)))
    (if (i32.lt_u (i32.sub (local.get $capacity) (local.get $used)) (local.get $required)) (then
      (local.set $status (call $proof_native_op_grow (local.get $state) (i32.add (local.get $used) (local.get $required))))
      (if (i32.eqz (local.get $status)) (then (return (i32.const 2))))
      (if (i32.lt_s (local.get $status) (i32.const 0))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
      (return (i32.const 5))))
    (if (i32.eqz (local.get $driver)) (then
      (local.set $driver (call $proof_make_array (local.get $base) (i32.const 13)))
      (call $native_continuation_state_set (local.get $state) (i32.const 3) (local.get $driver))
      (call $native_continuation_state_set (local.get $meta) (i32.const 3) (global.get $proof_scratch_cursor))
      (return (i32.const 5))))
    (if (i32.and (local.get $sequence) (i32.lt_u (local.get $index) (i32.const 3))) (then
      (if (i32.eqz (local.get $target)) (then
        (local.set $target (call $proof_make_array (local.get $base) (local.get $count)))
        (call $proof_array_set (local.get $base) (local.get $driver) (i32.add (local.get $index) (i32.const 5)) (local.get $target))
        (call $native_continuation_state_set (local.get $meta) (i32.const 3) (global.get $proof_scratch_cursor))
        (return (i32.const 5))))
      (if (i32.ge_u (local.get $element) (local.get $count)) (then
        (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 1) (i32.add (local.get $index) (i32.const 1)))
        (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 2) (i32.const 0))
        (return (i32.const 5))))
      (local.set $slot (call $proof_native_array_value_address (local.get $array) (local.get $element)))
      (if (i32.and (i32.eq (local.get $method) (i32.const 0x275)) (i32.ne (local.get $index) (i32.const 1))) (then
        (local.set $value (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 4)))
        (if (i32.eqz (local.get $value)) (then
          (local.set $value (call $proof_make_array (local.get $base) (local.get $length)))
          (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 4) (local.get $value))
          (call $native_continuation_state_set (local.get $meta) (i32.const 3) (global.get $proof_scratch_cursor))
          (return (i32.const 5))))
        (local.set $byte (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 3)))
        (if (i32.lt_u (local.get $byte) (local.get $length)) (then
          (call $proof_array_set (local.get $base) (local.get $value) (local.get $byte)
            (i32.load8_u (i32.add (call $string_id_to_abs (local.get $name)) (i32.add (i32.const 4) (local.get $byte)))))
          (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 3) (i32.add (local.get $byte) (i32.const 1)))
          (return (i32.const 5))))
        (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 3) (i32.const 0))
        (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 4) (i32.const 0)))
      (else
        (if (i32.eq (local.get $method) (i32.const 0x275)) (then
          (if (i32.ne (call $value_type (local.get $slot)) (global.get $TYPE_BOOLEAN))
            (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
          (local.set $value (call $value_data_lo (local.get $slot))))
        (else
          (local.set $value (call $proof_native_nonnegative_integer_argument (local.get $slot)))
          (if (i32.lt_s (local.get $value) (i32.const 0))
            (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))))))
      (call $proof_array_set (local.get $base) (local.get $target) (local.get $element) (local.get $value))
      (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 2) (i32.add (local.get $element) (i32.const 1)))
      (return (i32.const 5))))
    (local.set $root (call $proof_native_handle_root (local.get $handle)))
    (local.set $context (call $proof_make_array (local.get $base) (i32.const 0)))
    (local.set $work (call $proof_work_create (local.get $base) (global.get $proof_operation_remaining)))
    (if (i32.eq (local.get $method) (i32.const 0x271))
      (then (local.set $status (call $proof_work_start_proof_elaboration_unify_result (local.get $base) (local.get $root) (local.get $work)))))
    (if (i32.eq (local.get $method) (i32.const 0x275)) (then
      (local.set $status (call $proof_work_start_proof_elaboration_apply (local.get $base) (local.get $root)
        (call $proof_load (local.get $base) (i32.add (local.get $root) (i32.const 8)))
        (call $proof_load (local.get $base) (i32.add (local.get $root) (i32.const 12)))
        (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 5))
        (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 6))
        (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 7))
        (call $proof_array_count (local.get $base) (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 5)))
        (call $proof_array_count (local.get $base) (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 7)))
        (local.get $work)))))
    (if (i32.eq (local.get $method) (i32.const 0x276)) (then
      (local.set $index (call $proof_native_nonnegative_integer_argument (i32.add (local.get $args) (i32.mul (global.get $VALUE_SIZE) (i32.const 5)))))
      (local.set $value (call $proof_native_nonnegative_integer_argument (i32.add (local.get $args) (i32.mul (global.get $VALUE_SIZE) (i32.const 6)))))
      (if (i32.or (i32.or (i32.lt_s (local.get $index) (i32.const 1)) (i32.gt_u (local.get $index) (i32.const 32)))
        (i32.or (i32.lt_s (local.get $value) (i32.const 1)) (i32.gt_u (local.get $value) (i32.const 4096))))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
      (local.set $status (call $proof_work_start_proof_elaboration_resolve_root (local.get $base) (local.get $root)
        (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 5))
        (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 6))
        (call $proof_array_get (local.get $base) (local.get $driver) (i32.const 7))
        (local.get $index) (local.get $value) (local.get $work)))))
    (if (i32.eqz (call $is_proof_elaboration_method (local.get $method))) (then
      (local.set $status (call $proof_work_start_proof_native_elaborate_checked_term (local.get $base)
        (call $proof_load (local.get $base) (i32.add (local.get $root) (i32.const 8)))
        (call $proof_load (local.get $base) (i32.add (local.get $root) (i32.const 12)))
        (local.get $context) (i32.const 0) (i32.const 0) (local.get $work)))))
    (if (i32.eqz (local.get $status))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
    (call $proof_work_save (local.get $base) (local.get $work))
    (call $native_continuation_state_set (local.get $state) (i32.const 4) (local.get $work))
    (call $native_continuation_state_set (local.get $meta) (i32.const 3) (global.get $proof_scratch_cursor))
    (call $proof_native_phase (local.get $state) (i32.const 46))
    (i32.const 5))
