  ;; Persistent State native boundary. Inputs remain pending-stack roots until
  ;; the generic bridge commits the checked immutable result. Only owned byte
  ;; composition happens here; all identity, tactic, and typed checks use CPS.
  (global $PROOF_PH_STATE_START i32 (i32.const 42))
  (global $PROOF_PH_STATE_WORK i32 (i32.const 43))
  (global $PROOF_PH_STATE_COMPACT i32 (i32.const 44))

  (func $is_proof_state_method (param $method i32) (result i32)
    (i32.or (i32.eq (local.get $method) (i32.const 0x286))
      (i32.or (i32.and (i32.ge_u (local.get $method) (i32.const 0x28a))
                       (i32.le_u (local.get $method) (i32.const 0x293)))
        (i32.and (i32.ge_u (local.get $method) (i32.const 0x2d0))
                 (i32.le_u (local.get $method) (i32.const 0x2e8))))))

  (func $proof_native_state_returns_state (param $method i32) (result i32)
    (i32.and (call $is_proof_state_method (local.get $method))
      (i32.and (i32.ne (local.get $method) (i32.const 0x28c))
               (i32.ne (local.get $method) (i32.const 0x2e8)))))

  ;; Returns the required term argument position, or -1 for a state-only tactic.
  (func $proof_native_state_term_position (param $method i32) (result i32)
    (if (i32.eq (local.get $method) (i32.const 0x286)) (then (return (i32.const 1))))
    (if (i32.eq (local.get $method) (i32.const 0x2dd)) (then (return (i32.const 3))))
    (if (i32.or
      (i32.or (i32.eq (local.get $method) (i32.const 0x28a)) (i32.eq (local.get $method) (i32.const 0x28d)))
      (i32.or (i32.or (i32.eq (local.get $method) (i32.const 0x292)) (i32.eq (local.get $method) (i32.const 0x2d2)))
        (i32.or (i32.or (i32.eq (local.get $method) (i32.const 0x2d8)) (i32.eq (local.get $method) (i32.const 0x2db)))
          (i32.or (i32.eq (local.get $method) (i32.const 0x2dc))
            (i32.or (i32.eq (local.get $method) (i32.const 0x2e2)) (i32.eq (local.get $method) (i32.const 0x2e8)))))))
      (then (return (i32.const 2))))
    (i32.const -1))

  (func $proof_native_state_has_extra (param $method i32) (result i32)
    (i32.or
      (i32.and (i32.ge_u (local.get $method) (i32.const 0x28f)) (i32.le_u (local.get $method) (i32.const 0x291)))
      (i32.or (i32.or (i32.eq (local.get $method) (i32.const 0x2d3)) (i32.eq (local.get $method) (i32.const 0x2d4)))
        (i32.or (i32.or (i32.eq (local.get $method) (i32.const 0x2d6)) (i32.eq (local.get $method) (i32.const 0x2d7)))
          (i32.or (i32.eq (local.get $method) (i32.const 0x2dd))
            (i32.or (i32.or (i32.eq (local.get $method) (i32.const 0x2e3)) (i32.eq (local.get $method) (i32.const 0x2e4)))
              (i32.eq (local.get $method) (i32.const 0x2e7))))))))

  (func $proof_native_state_prepare
    (param $state i32) (param $method i32) (param $argc i32) (param $args i32) (result i32)
    (local $left i32) (local $right i32) (local $position i32) (local $slot i32)
    (local $index i32) (local $extra i32) (local $reverse i32) (local $owner i32)
    (local $a i32) (local $b i32) (local $alen i32) (local $blen i32) (local $delta i32)
    (local $ad i32) (local $bd i32) (local $count i32) (local $chosen i32)
    (local $length i32) (local $handle i32) (local $root i32)
    (local $decls i32) (local $meta i32) (local $buffer i32)
    (local $same i32) (local $ext i32) (local $shape i32) (local $options i32) (local $progress i32)
    (if (i32.eqz (local.get $argc))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_MISSING_ARGUMENT)))))
    (if (i32.ne (call $value_type (local.get $args)) (global.get $TYPE_THEOREM))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
    (local.set $left (call $value_data_lo (local.get $args)))
    (if (i32.eqz (if (result i32) (i32.eq (local.get $method) (i32.const 0x286))
      (then (call $proof_native_environment_handle_valid (local.get $left)))
      (else (call $proof_native_state_handle_valid (local.get $left)))))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
    (local.set $right (local.get $left))
    (local.set $position (call $proof_native_state_term_position (local.get $method)))
    (if (i32.ge_s (local.get $position) (i32.const 0)) (then
      (if (i32.le_u (local.get $argc) (local.get $position))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_MISSING_ARGUMENT)))))
      (local.set $slot (i32.add (local.get $args) (i32.mul (local.get $position) (global.get $VALUE_SIZE))))
      (if (i32.ne (call $value_type (local.get $slot)) (global.get $TYPE_THEOREM))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
      (local.set $right (call $value_data_lo (local.get $slot)))
      (if (i32.eqz (call $proof_native_term_handle_valid (local.get $right)))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))))
    (if (i32.and (i32.ne (local.get $method) (i32.const 0x286)) (i32.ne (local.get $method) (i32.const 0x28c))) (then
      (local.set $index (call $proof_native_state_goal_index_argument (local.get $args) (local.get $argc) (i32.const 1)))
      (if (i32.lt_s (local.get $index) (i32.const 0))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))))
    (if (call $proof_native_state_has_extra (local.get $method)) (then
      (if (i32.and (i32.eq (local.get $method) (i32.const 0x28f)) (i32.lt_u (local.get $argc) (i32.const 3)))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_MISSING_ARGUMENT)))))
      (local.set $extra (call $proof_native_state_goal_index_argument (local.get $args) (local.get $argc) (i32.const 2)))
      (if (i32.lt_s (local.get $extra) (i32.const 0))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))))
    (if (i32.and (i32.eq (local.get $method) (i32.const 0x2d3)) (i32.ge_u (local.get $argc) (i32.const 4)))
      (then (local.set $reverse (call $is_truthy (i32.add (local.get $args) (i32.mul (i32.const 3) (global.get $VALUE_SIZE)))))))
    (local.set $owner (call $proof_native_scope_union (local.get $left) (local.get $right)))
    (if (i32.eq (local.get $owner) (i32.const -1))
      (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_NOT_AN_OBJECT)))))
    (local.set $alen (call $proof_native_handle_artifact_length (local.get $left)))
    (local.set $blen (call $proof_native_handle_artifact_length (local.get $right)))
    (local.set $a (call $proof_native_handle_artifact_base (local.get $left)))
    (local.set $b (call $proof_native_handle_artifact_base (local.get $right)))
    (local.set $ad (call $proof_load (local.get $a) (i32.const 12)))
    (local.set $bd (call $proof_load (local.get $b) (i32.const 12)))
    (local.set $count (call $proof_array_count (local.get $a) (local.get $ad)))
    (local.set $chosen (i32.ge_u (local.get $count) (call $proof_array_count (local.get $b) (local.get $bd))))
    (if (i32.eqz (local.get $chosen)) (then (local.set $count (call $proof_array_count (local.get $b) (local.get $bd)))))
    ;; Keep both declaration arrays for artifact-local prefix checks. Shared
    ;; input buffers need only one owned copy, even when their roots differ.
    (local.set $same (i32.eq (local.get $a) (local.get $b)))
    (if (local.get $same)
      (then (local.set $root (local.get $alen)))
      (else
        (local.set $delta (i32.sub (local.get $alen) (i32.const 16)))
        (local.set $root (i32.add (local.get $delta) (local.get $blen)))))
    (local.set $decls (i32.add (local.get $root) (i32.const 16)))
    (local.set $length (i32.add (local.get $decls) (i32.add (i32.const 12) (i32.shl (local.get $count) (i32.const 2)))))
    (if (i32.or (i32.lt_u (local.get $length) (local.get $alen)) (i32.gt_u (local.get $length) (i32.const 0x3ffeffff)))
      (then (global.set $proof_last_error_code (i32.const 20))
        (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
    ;; Reserve all roots and the initial transfer atomically. No input buffer is
    ;; ever used as a destination; the new arena remains private until checked.
    (if (call $check_heap_overflow
      (i32.add (call $estimate_arraybuffer_size (i32.add (local.get $length) (i32.const 65536)))
        (i32.add (i32.const 24) (i32.mul (global.get $NATIVE_CONTINUATION_STATE_SIZE) (i32.const 6)))))
      (then (return (i32.const 2))))
    (local.set $buffer (call $allocate_arraybuffer_uninitialized (i32.add (local.get $length) (i32.const 65536))))
    (local.set $handle (call $proof_native_allocate_buffer_handle (local.get $buffer) (local.get $root)
      (global.get $PROOF_HANDLE_TERM) (local.get $owner)))
    (local.set $shape (call $allocate_native_continuation_state (i32.const 0) (i32.const 0)
      (local.get $alen) (local.get $blen) (local.get $delta) (local.get $ad) (i32.add (local.get $bd) (local.get $delta))))
    (local.set $options (call $allocate_native_continuation_state (i32.const 0) (i32.const 0)
      (local.get $length) (local.get $count)
      (select (local.get $ad) (i32.add (local.get $bd) (local.get $delta)) (local.get $chosen))
      (local.get $index) (local.get $extra)))
    (local.set $progress (call $allocate_native_continuation_state (i32.const 0) (i32.const 0)
      (i32.const 0) (local.get $alen) (i32.const 2) (local.get $reverse) (i32.const 0)))
    (local.set $ext (call $allocate_native_continuation_state (i32.const 31) (i32.const 0)
      (local.get $left) (local.get $right) (local.get $shape) (local.get $options) (local.get $progress)))
    (local.set $meta (call $proof_native_op_metadata (local.get $state)))
    (i32.store (call $abs (i32.add (local.get $meta) (global.get $GC_HEADER_SIZE))) (i32.const 16))
    (call $native_continuation_state_set (local.get $meta) (i32.const 4) (local.get $ext))
    (call $native_continuation_state_set (local.get $state) (i32.const 1) (local.get $handle))
    ;; The shared engine copies the left prefix, then initializes the entire
    ;; remaining capacity in bounded steps before phase42 reads the arena.
    (call $proof_native_transfer_begin (local.get $state)
      (call $proof_native_handle_buffer (local.get $left)) (local.get $buffer)
      (i32.const 0) (local.get $alen) (i32.const 42)))

  ;; During preparation metadata.word4 is a HEADER (mask16), not errorOffset.
  ;; Its extension has header mask31/data mask0:
  ;;   left handle, right handle, shape, options, progress.
  ;; The three scalar records have masks0:
  ;;   shape    = left length, right length, delta, left decls, rebased right decls
  ;;   options  = final length, declaration count, chosen decls, goal index, extra
  ;;   progress = stage, record offset, field index, reverse, reserved
  ;; Phase42 with state.word3==0 drives preparation; stages0/1/2/3 are
  ;; right-copy, per-field relocation, declaration-copy, constant-size finish.
  ;; Phase39 is exclusively the shared transfer engine. All cursors are scalar
  ;; artifact-relative values; no interior heap pointer survives a yield.
  (func $proof_native_state_prepare_step (param $state i32) (param $method i32) (result i32)
    (local $meta i32) (local $ext i32) (local $shape i32) (local $options i32) (local $progress i32)
    (local $handle i32) (local $buffer i32) (local $base i32) (local $root i32) (local $decls i32)
    (local $stage i32) (local $delta i32) (local $offset i32) (local $field i32) (local $words i32)
    (local $length i32) (local $driver i32)
    (local.set $meta (call $proof_native_op_metadata (local.get $state)))
    (local.set $ext (call $native_continuation_state_get (local.get $meta) (i32.const 4)))
    (local.set $shape (call $native_continuation_state_get (local.get $ext) (i32.const 2)))
    (local.set $options (call $native_continuation_state_get (local.get $ext) (i32.const 3)))
    (local.set $progress (call $native_continuation_state_get (local.get $ext) (i32.const 4)))
    (local.set $handle (call $native_continuation_state_get (local.get $state) (i32.const 1)))
    (local.set $buffer (call $proof_native_handle_buffer (local.get $handle)))
    (local.set $base (i32.add (local.get $buffer) (i32.const 4)))
    (local.set $root (call $proof_native_handle_root (local.get $handle)))
    (local.set $decls (i32.add (local.get $root) (i32.const 16)))
    (local.set $delta (call $native_continuation_state_get (local.get $shape) (i32.const 2)))
    (local.set $stage (call $native_continuation_state_get (local.get $progress) (i32.const 0)))
    (if (i32.eqz (local.get $stage)) (then
      (if (i32.eqz (local.get $delta)) (then
        (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 2))
        (return (i32.const 5))))
      (if (call $check_heap_overflow (i32.mul (global.get $NATIVE_CONTINUATION_STATE_SIZE) (i32.const 2)))
        (then (return (i32.const 2))))
      (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 1))
      (return (call $proof_native_transfer_range_begin (local.get $state)
        (call $proof_native_handle_buffer (call $native_continuation_state_get (local.get $ext) (i32.const 1)))
        (local.get $buffer) (i32.const 16)
        (call $native_continuation_state_get (local.get $shape) (i32.const 0))
        (i32.sub (call $native_continuation_state_get (local.get $shape) (i32.const 1)) (i32.const 16))
        (i32.const 0) (i32.const 42)))))
    (if (i32.eq (local.get $stage) (i32.const 1)) (then
      (local.set $offset (call $native_continuation_state_get (local.get $progress) (i32.const 1)))
      (if (i32.ge_u (local.get $offset) (local.get $root)) (then
        (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 2))
        (return (i32.const 5))))
      (local.set $field (call $native_continuation_state_get (local.get $progress) (i32.const 2)))
      (local.set $words (call $proof_load (local.get $base) (local.get $offset)))
      ;; Exactly one edge classification/rebase or one record advance per step,
      ;; including arrays with input-sized numbers of declaration references.
      (if (i32.lt_u (local.get $field) (local.get $words))
        (then
          (if (call $proof_record_edge_kind (local.get $base) (local.get $offset) (local.get $field)) (then
            (call $proof_store (local.get $base) (i32.add (local.get $offset) (i32.shl (local.get $field) (i32.const 2)))
              (call $proof_native_relocated_reference
                (call $proof_load (local.get $base) (i32.add (local.get $offset) (i32.shl (local.get $field) (i32.const 2))))
                (local.get $delta) (i32.const 0)))))
          (call $native_continuation_state_set (local.get $progress) (i32.const 2) (i32.add (local.get $field) (i32.const 1))))
        (else
          (call $native_continuation_state_set (local.get $progress) (i32.const 1)
            (i32.add (local.get $offset) (i32.shl (local.get $words) (i32.const 2))))
          (call $native_continuation_state_set (local.get $progress) (i32.const 2) (i32.const 2))))
      (return (i32.const 5))))
    (if (i32.eq (local.get $stage) (i32.const 2)) (then
      (if (call $check_heap_overflow (i32.mul (global.get $NATIVE_CONTINUATION_STATE_SIZE) (i32.const 2)))
        (then (return (i32.const 2))))
      (call $native_continuation_state_set (local.get $progress) (i32.const 0) (i32.const 3))
      (return (call $proof_native_transfer_range_begin (local.get $state) (local.get $buffer) (local.get $buffer)
        (call $native_continuation_state_get (local.get $options) (i32.const 2)) (local.get $decls)
        (i32.add (i32.const 12) (i32.shl (call $native_continuation_state_get (local.get $options) (i32.const 1)) (i32.const 2)))
        (i32.const 0) (i32.const 42)))))
    (local.set $length (call $native_continuation_state_get (local.get $options) (i32.const 0)))
    (call $proof_store (local.get $base) (local.get $root) (i32.const 4))
    (call $proof_store (local.get $base) (i32.add (local.get $root) (i32.const 4)) (global.get $PROOF_TERM_APPLICATION))
    (call $proof_store (local.get $base) (i32.add (local.get $root) (i32.const 8))
      (call $proof_native_handle_root (call $native_continuation_state_get (local.get $ext) (i32.const 0))))
    (call $proof_store (local.get $base) (i32.add (local.get $root) (i32.const 12))
      (i32.add (call $proof_native_handle_root (call $native_continuation_state_get (local.get $ext) (i32.const 1))) (local.get $delta)))
    (call $proof_native_initialize_artifact_header (local.get $base) (local.get $length) (local.get $decls))
    (global.set $proof_current_artifact_length (local.get $length))
    (global.set $proof_current_declaration_index (i32.const -1))
    (global.set $proof_current_universe_context (i32.const 0))
    (global.set $proof_scratch_cursor (local.get $length))
    (global.set $proof_scratch_limit (i32.add (local.get $length) (i32.const 65536)))
    (global.set $proof_last_error_code (i32.const 0))
    (global.set $proof_last_error_offset (i32.const 0))
    (local.set $driver (call $proof_make_array (local.get $base) (i32.const 8)))
    (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 0)
      (call $native_continuation_state_get (local.get $shape) (i32.const 3)))
    (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 1)
      (call $native_continuation_state_get (local.get $shape) (i32.const 4)))
    (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 2)
      (call $proof_load (local.get $base) (i32.add (local.get $root) (i32.const 8))))
    (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 3)
      (call $proof_load (local.get $base) (i32.add (local.get $root) (i32.const 12))))
    (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 4) (local.get $method))
    (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 5)
      (call $native_continuation_state_get (local.get $options) (i32.const 3)))
    (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 6)
      (call $native_continuation_state_get (local.get $options) (i32.const 4)))
    (call $proof_array_set (local.get $base) (local.get $driver) (i32.const 7)
      (call $native_continuation_state_get (local.get $progress) (i32.const 3)))
    (call $native_continuation_state_set (local.get $state) (i32.const 3) (local.get $driver))
    (call $native_continuation_state_set (local.get $meta) (i32.const 3) (global.get $proof_scratch_cursor))
    (call $native_continuation_state_set (local.get $meta) (i32.const 4) (i32.const 0))
    (i32.store (call $abs (i32.add (local.get $meta) (global.get $GC_HEADER_SIZE))) (i32.const 0))
    (i32.const 5))

  (func $proof_native_state_transition (param $state i32) (param $method i32) (result i32)
    (local $phase i32) (local $meta i32) (local $handle i32) (local $base i32)
    (local $capacity i32) (local $length i32) (local $work i32) (local $driver i32)
    (local $status i32) (local $root i32)
    (local.set $phase (i32.and (call $native_continuation_state_get (local.get $state) (i32.const 0)) (i32.const 255)))
    (if (i32.and (i32.eq (local.get $phase) (i32.const 42))
      (i32.eqz (call $native_continuation_state_get (local.get $state) (i32.const 3))))
      (then (return (call $proof_native_state_prepare_step (local.get $state) (local.get $method)))))
    (local.set $meta (call $native_continuation_state_get (local.get $state) (i32.const 2)))
    (local.set $handle (call $native_continuation_state_get (local.get $state) (i32.const 1)))
    (local.set $base (call $proof_native_handle_artifact_base (local.get $handle)))
    (local.set $length (call $proof_native_handle_artifact_length (local.get $handle)))
    (local.set $capacity (i32.load (call $abs (call $proof_native_handle_buffer (local.get $handle)))))
    (local.set $driver (call $native_continuation_state_get (local.get $state) (i32.const 3)))
    (local.set $work (call $native_continuation_state_get (local.get $state) (i32.const 4)))
    (if (i32.eq (local.get $phase) (i32.const 42)) (then
      (global.set $proof_scratch_cursor (call $native_continuation_state_get (local.get $meta) (i32.const 3)))
      (global.set $proof_scratch_limit (local.get $capacity))
      (global.set $proof_current_artifact_length (local.get $length))
      (global.set $proof_current_declaration_index (i32.const -1))
      (global.set $proof_current_universe_context (i32.const 0))
      (global.set $proof_last_error_code (i32.const 0))
      (global.set $proof_last_error_offset (i32.const 0))
      (global.set $proof_last_inferred_type (i32.const 0))
      (global.set $proof_last_expected_type (i32.const 0))
      (local.set $work (call $proof_work_create (local.get $base) (global.get $proof_operation_remaining)))
      (if (i32.eqz (call $proof_work_start_proof_pipeline_state_entry (local.get $base) (local.get $driver) (local.get $work)))
        (then (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
      (call $proof_work_save (local.get $base) (local.get $work))
      (call $native_continuation_state_set (local.get $state) (i32.const 4) (local.get $work))
      (call $native_continuation_state_set (local.get $meta) (i32.const 3) (global.get $proof_scratch_cursor))
      (call $proof_native_phase (local.get $state) (i32.const 43))
      (return (i32.const 5))))
    (if (i32.eq (local.get $phase) (i32.const 43)) (then
      (if (i32.eq (call $proof_load (local.get $base) (i32.add (local.get $work) (i32.const 28))) (i32.const 3)) (then
        (local.set $status (call $proof_native_op_grow (local.get $state) (i32.const 0)))
        (if (i32.eq (local.get $status) (i32.const 5)) (then (return (i32.const 5))))
        (if (i32.eqz (local.get $status)) (then (return (i32.const 2))))
        (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
      (call $proof_work_resume (local.get $base) (local.get $work) (local.get $capacity))
      (global.set $proof_last_error_offset (call $proof_native_op_error_offset (local.get $meta)))
      (local.set $status (call $proof_work_step (local.get $base) (local.get $work)))
      (call $proof_work_save (local.get $base) (local.get $work))
      (call $native_continuation_state_set (local.get $meta) (i32.const 3) (global.get $proof_scratch_cursor))
      (call $proof_native_op_set_error_offset (local.get $meta) (global.get $proof_last_error_offset))
      (if (i32.or (i32.eqz (local.get $status)) (i32.eq (local.get $status) (i32.const 3))) (then (return (i32.const 5))))
      (local.set $root (call $proof_load (local.get $base) (i32.add (local.get $work) (i32.const 12))))
      (if (i32.or (global.get $proof_last_error_code) (i32.le_s (local.get $root) (i32.const 0))) (then
        (if (i32.eqz (global.get $proof_last_error_code)) (then (global.set $proof_last_error_code (i32.const 42))))
        (return (call $proof_native_op_fail (local.get $state) (global.get $BUILTIN_MSG_INVALID_INDEX)))))
      (call $native_continuation_state_set (local.get $meta) (i32.const 1) (local.get $root))
      (call $proof_native_phase (local.get $state) (i32.const 44))
      (return (i32.const 5))))
    ;; A live old work root distinguishes compaction entry from its completed
    ;; return. The shared compactor clears old arena-relative work on publication.
    (if (local.get $work) (then
      (return (call $proof_native_core_prepare_begin (local.get $state) (local.get $handle)
        (call $native_continuation_state_get (local.get $meta) (i32.const 1))
        (call $native_continuation_state_get (local.get $meta) (i32.const 3))
        (i32.const -1) (i32.const 44)))))
    (if (call $proof_native_state_returns_state (local.get $method))
      (then (i32.store (call $abs (i32.add (local.get $handle) (i32.const 16))) (global.get $PROOF_HANDLE_PROOF_STATE))))
    (call $proof_native_phase (local.get $state) (i32.const 33))
    (i32.const 5))
