;; Test-only direct caller. Build-time fixture insertion is the only preprocessing.
;; No scheduler, codec, compiler phase loop, or arena policy lives here. Resource
;; retries below copy the helper-declared live prefix and allocate returned bytes.
(module
  (import "env" "memory" (memory 1 16384 shared))
  (import "schema" "initialize_work_budget" (func $budget_init (param i32 i32 i64 i32) (result i32)))
  (import "schema" "compile_direct" (func $compile_direct (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32 i32)))
  (import "schema" "validate_direct" (func $validate_direct (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32 i32)))
  (import "schema" "render_error_direct" (func $render_direct (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32 i32)))
  (import "schema" "validate_program" (func $load (param i32 i32) (result i32)))
  (import "schema" "program_total_bytes" (func $program_size (param i32) (result i32)))
  (import "schema" "program_route_count" (func $program_routes (param i32) (result i32)))
  (import "schema" "validation_result" (func $verdict (param i32) (result i32)))
  (import "schema" "validation_work_charged" (func $validation_work (param i32) (result i64)))
  (import "schema" "error_stored" (func $error_stored (param i32) (result i32)))
  (import "schema" "error_record" (func $error_record (param i32 i32) (result i32)))
  (import "schema" "route_count" (func $route_count (param i32) (result i32)))
  (import "schema" "route_result" (func $route_result (param i32 i32) (result i32)))
  (import "schema" "error_count" (func $error_count (param i32) (result i32)))
  (import "schema" "render_failure_direct" (func $render_failure (param i32 i32 i32 i32 i32) (result i32 i32)))
  (import "schema" "format_number" (func $format_number (param f64 i32 i32 i32 i32) (result i32 i32 i64 i32)))
  (import "schema" "parse_number_utf16" (func $parse_number_utf16 (param i32 i32 i32 i32) (result i32 f64 i64 i32)))
  (import "schema" "format_number_hex" (func $format_number_hex (param f64 i32 i32) (result i32 i32 i64 i32)))

  (global $heap (mut i32) (i32.const 4096))
  (global $limit (mut i32) (i32.const 1073741824))
  (global $failure (mut i32) (i32.const 0))
  (global $status (mut i32) (i32.const 0))
  (global $expected (mut i32) (i32.const 0))
  (global $required (mut i32) (i32.const 0))
  (global $b (mut i32) (i32.const 0))
  (global $s (mut i32) (i32.const 0))
  (global $cap (mut i32) (i32.const 0))
  (global $p (mut i32) (i32.const 0))
  (global $pn (mut i32) (i32.const 0))
  (global $d (mut i32) (i32.const 0))
  (global $dn (mut i32) (i32.const 0))
  (global $input (mut i32) (i32.const 0))
  (global $inbytes (mut i32) (i32.const 0))
  (global $options (mut i32) (i32.const 0))
  (global $grant (mut i32) (i32.const 0))
  (global $mode (mut i32) (i32.const 0))
  (global $arena (mut i32) (i32.const 16384))
  (global $errors (mut i32) (i32.const 8))
  (global $shortages (mut i32) (i32.const 0))
  (global $first_work (mut i64) (i64.const 0))
  (global $last_work (mut i64) (i64.const 0))
  (global $relocate (mut i32) (i32.const 0))
  (global $out (mut i32) (i32.const 0))
  (global $outcap (mut i32) (i32.const 0))
  (global $outlen (mut i32) (i32.const 0))

  ;; @FIXTURES@

  (func $check (param $ok i32) (param $code i32)
    (if (i32.and (i32.eqz (local.get $ok)) (i32.eqz (global.get $failure)))
      (then (global.set $failure (local.get $code)))))
  (func $expect (param $status i32)
    (global.set $expected (local.get $status))
    (call $check (i32.eq (global.get $status) (local.get $status)) (i32.add (i32.const 100) (local.get $status))))
  (func $work (result i64) (i64.load offset=24 (global.get $b)))
  (func $cont (result i32) (i32.add (global.get $s) (i32.load offset=32 (global.get $s))))
  (func $alloc (param $bytes i32) (result i32)
    (local $end i64) (local $p i32) (local $pages i32)
    (local.set $p (global.get $heap))
    (local.set $end (i64.and (i64.add (i64.add (i64.extend_i32_u (local.get $p))
      (i64.extend_i32_u (local.get $bytes))) (i64.const 7)) (i64.const -8)))
    (if (i64.gt_u (local.get $end) (i64.extend_i32_u (global.get $limit))) (then (return (i32.const 0))))
    (local.set $pages (i32.wrap_i64 (i64.shr_u (i64.add (local.get $end) (i64.const 65535)) (i64.const 16))))
    (if (i32.gt_u (local.get $pages) (memory.size))
      (then (if (i32.eq (memory.grow (i32.sub (local.get $pages) (memory.size))) (i32.const -1))
        (then (return (i32.const 0))))))
    (global.set $heap (i32.wrap_i64 (local.get $end)))
    (memory.fill (local.get $p) (i32.const 0) (local.get $bytes))
    (local.get $p))
  (func $copy (param $p i32) (param $n i32) (result i32) (local $q i32)
    (local.set $q (call $alloc (local.get $n)))
    (if (i32.eqz (local.get $q)) (then (unreachable)))
    (memory.copy (local.get $q) (local.get $p) (local.get $n)) (local.get $q))
  (func $same (param $a i32) (param $b i32) (param $n i32) (result i32) (local $i i32)
    (block $done (loop $bytes
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $a) (local.get $i)))
        (i32.load8_u (i32.add (local.get $b) (local.get $i)))) (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $bytes))) (i32.const 1))
  (func $expect_program (param $fixture i32)
    (call $check (i32.eq (global.get $pn) (call $fixture_size (local.get $fixture))) (i32.const 220))
    (call $check (call $same (global.get $p) (call $fixture (local.get $fixture)) (global.get $pn)) (i32.const 221)))
  (func $new_budget (param $allowance i64)
    (global.set $b (call $alloc (i32.const 48)))
    (call $check (i32.eqz (call $budget_init (global.get $b) (i32.const 48) (local.get $allowance) (i32.const 0))) (i32.const 201)))
  (func $new_scratch
    (global.set $cap (i32.const 64))
    (global.set $s (call $alloc (global.get $cap)))
    (global.set $shortages (i32.const 0))
    (global.set $first_work (i64.const 0)) (global.set $last_work (i64.const 0)))
  (func $grow_scratch (result i32) (local $next i32) (local $live i32)
    (call $check (i32.gt_u (global.get $required) (global.get $cap)) (i32.const 202))
    (global.set $shortages (i32.add (global.get $shortages) (i32.const 1)))
    (if (i32.eq (global.get $shortages) (i32.const 1)) (then (global.set $first_work (call $work))))
    (global.set $last_work (call $work))
    (local.set $next (call $alloc (global.get $required)))
    (if (i32.eqz (local.get $next)) (then (return (i32.const 0))))
    (if (i32.ge_u (global.get $cap) (i32.const 64))
      (then
        (local.set $live (i32.load offset=24 (global.get $s)))
        (call $check (i32.le_u (local.get $live) (global.get $cap)) (i32.const 203))
        (memory.copy (local.get $next) (global.get $s) (local.get $live))))
    ;; The retired owner is poisoned, never silently left as a valid alias.
    (memory.fill (global.get $s) (i32.const 193) (global.get $cap))
    (global.set $s (local.get $next)) (global.set $cap (global.get $required)) (i32.const 1))
  (func $compile_call (param $init i32)
    (call $compile_direct (global.get $input) (global.get $inbytes) (global.get $options)
      (global.get $s) (global.get $cap) (global.get $b) (local.get $init) (global.get $grant))
    (global.set $required) (global.set $status))
  (func $compile_resources (param $init i32) (local $before i64) (local $need i32) (local $next i32)
    (loop $resources
      (call $compile_call (local.get $init))
      (if (i32.ne (global.get $status) (i32.const 7)) (then (return)))
      (local.set $before (call $work)) (local.set $need (global.get $required))
      (if (i32.ge_u (global.get $cap) (i32.const 64))
        (then
          (call $compile_call (i32.const 0))
          (call $check (i32.and (i32.eq (global.get $status) (i32.const 7))
            (i32.eq (global.get $required) (local.get $need))) (i32.const 204))
          (call $check (i64.eq (call $work) (local.get $before)) (i32.const 205))))
      (local.set $init (i32.lt_u (global.get $cap) (i32.const 64)))
      (if (i32.eqz (call $grow_scratch)) (then (return)))
      (if (global.get $relocate) (then
        (local.set $next (call $copy (global.get $input) (global.get $inbytes)))
        (memory.fill (global.get $input) (i32.const 193) (global.get $inbytes))
        (global.set $input (local.get $next))))
      (br $resources)))
  (func $compile (param $fixture i32) (param $options i32) (param $allowance i64) (param $grant i32)
    (local $borrowed i32)
    (global.set $input (call $fixture (local.get $fixture)))
    (global.set $inbytes (call $fixture_size (local.get $fixture)))
    (global.set $options (local.get $options)) (global.set $grant (local.get $grant))
    (call $new_budget (local.get $allowance)) (call $new_scratch)
    (call $compile_resources (i32.const 1))
    (if (i32.eqz (global.get $status)) (then
      (local.set $borrowed (i32.add (global.get $s) (i32.load offset=32 (global.get $s))))
      ;; Match the facade's exported owner span, including its measured reserve;
      ;; TOTAL_BYTES may be smaller, but both callers copy RESULT_CAPACITY.
      (global.set $pn (i32.load offset=36 (global.get $s)))
      (call $check (i32.le_u (call $program_size (local.get $borrowed)) (global.get $pn)) (i32.const 206))
      (global.set $p (call $copy (local.get $borrowed) (global.get $pn)))
      (call $check (call $same (global.get $p) (local.get $borrowed) (global.get $pn)) (i32.const 207))
      (call $check (i32.eqz (call $load (global.get $p) (global.get $pn))) (i32.const 208)))))
  (func $validate_call (param $init i32)
    (call $validate_direct (global.get $p) (global.get $pn) (global.get $d) (global.get $dn)
      (global.get $mode) (i32.const 256) (select (global.get $errors) (i32.const 0) (i32.and (global.get $mode) (i32.const 1)))
      (global.get $arena) (global.get $s) (global.get $cap) (global.get $b) (local.get $init) (global.get $grant))
    (global.set $required) (global.set $status))
  (func $validate_resources (param $init i32) (local $before i64) (local $need i32) (local $next i32)
    (loop $resources
      (call $validate_call (local.get $init))
      (if (i32.ne (global.get $status) (i32.const 7)) (then (return)))
      (local.set $before (call $work)) (local.set $need (global.get $required))
      (call $validate_call (i32.const 0))
      (call $check (i32.and (i32.eq (global.get $status) (i32.const 7))
        (i32.eq (global.get $required) (local.get $need))) (i32.const 209))
      (call $check (i64.eq (call $work) (local.get $before)) (i32.const 210))
      (if (i32.eqz (call $grow_scratch)) (then (return)))
      (if (global.get $relocate) (then
        (local.set $next (call $copy (global.get $p) (global.get $pn)))
        (memory.fill (global.get $p) (i32.const 193) (global.get $pn)) (global.set $p (local.get $next))
        (local.set $next (call $copy (global.get $d) (global.get $dn)))
        (memory.fill (global.get $d) (i32.const 193) (global.get $dn)) (global.set $d (local.get $next))))
      (local.set $init (i32.const 0)) (br $resources)))
  (func $validate (param $fixture i32) (param $allowance i64) (param $grant i32) (param $mode i32) (param $arena i32)
    (global.set $d (call $fixture (local.get $fixture))) (global.set $dn (call $fixture_size (local.get $fixture)))
    (global.set $mode (local.get $mode)) (global.set $arena (local.get $arena)) (global.set $grant (local.get $grant))
    (call $new_budget (local.get $allowance)) (call $new_scratch) (call $validate_resources (i32.const 1)))
  (func $render_call
    (call $render_direct (global.get $p) (global.get $pn) (global.get $s) (global.get $cap)
      (i32.const 0) (global.get $out) (global.get $outcap) (global.get $b))
    (global.set $outlen) (global.set $status))
  (func $render (local $before i64)
    (global.set $outcap (i32.const 8192)) (global.set $out (call $alloc (global.get $outcap)))
    (loop $resources
      (local.set $before (call $work)) (call $render_call)
      (if (i32.ne (global.get $status) (i32.const 7)) (then (return)))
      (call $check (i64.gt_u (call $work) (local.get $before)) (i32.const 211))
      (global.set $last_work (call $work))
      (call $check (i32.gt_u (global.get $outlen) (global.get $outcap)) (i32.const 212))
      (memory.fill (global.get $out) (i32.const 193) (global.get $outcap))
      (global.set $outcap (global.get $outlen)) (global.set $out (call $alloc (global.get $outcap)))
      (br $resources)))
  ;; Locate literal fixture bytes in a declared returned record, not a codec.
  (func $find (param $fixture i32) (param $start i32) (result i32)
    (local $needle i32) (local $n i32) (local $i i32)
    (local.set $needle (call $fixture (local.get $fixture))) (local.set $n (call $fixture_size (local.get $fixture)))
    (local.set $i (local.get $start))
    (block $done (loop $scan
      (br_if $done (i32.gt_u (i32.add (local.get $i) (local.get $n)) (global.get $outlen)))
      (if (call $same (i32.add (global.get $out) (local.get $i)) (local.get $needle) (local.get $n))
        (then (return (i32.add (local.get $i) (local.get $n)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $scan)))
    (call $check (i32.const 0) (i32.add (i32.const 300) (local.get $fixture))) (i32.const 0))
  (func $diagnostic (local $cursor i32) (local $record i32)
    (call $check (i32.eq (i32.load8_u (global.get $out)) (i32.const 133)) (i32.const 350))
    (call $check (i32.eq (call $error_stored (call $cont)) (i32.const 1)) (i32.const 351))
    (local.set $record (call $error_record (call $cont) (i32.const 0)))
    (call $check (i32.eq (i32.load16_u offset=2 (local.get $record)) (i32.const 4)) (i32.const 352))
    (call $check (i32.eqz (i32.load offset=12 (local.get $record))) (i32.const 353))
    (local.set $cursor (call $find (global.get $F_instanceField) (i32.const 1)))
    (call $check (i32.eq (i32.load8_u (i32.add (global.get $out) (local.get $cursor))) (i32.const 160)) (i32.const 354))
    (local.set $cursor (call $find (global.get $F_schemaField) (local.get $cursor)))
    (local.set $cursor (call $find (global.get $F_schemaPath) (local.get $cursor)))
    (local.set $cursor (call $find (global.get $F_keywordField) (local.get $cursor)))
    (local.set $cursor (call $find (global.get $F_keyword) (local.get $cursor)))
    (local.set $cursor (call $find (global.get $F_paramsField) (local.get $cursor)))
    (local.set $cursor (call $find (global.get $F_paramName) (local.get $cursor)))
    (local.set $cursor (call $find (global.get $F_missingText) (local.get $cursor)))
    (local.set $cursor (call $find (global.get $F_messageField) (local.get $cursor)))
    (local.set $cursor (call $find (global.get $F_messageText) (local.get $cursor)))
    (call $check (i32.eq (local.get $cursor) (global.get $outlen)) (i32.const 355)))

  (func $set_results (param $diagnostics i32) (local $i i32) (local $r i32) (local $next i32)
    (call $check (i32.eq (call $route_count (call $cont)) (i32.const 4)) (i32.const 400))
    (loop $routes
      (local.set $r (call $route_result (call $cont) (local.get $i)))
      ;; match() is the ordered sequence [0,2,3]. test(doc,index) reads this
      ;; same indexed record; duplicates must not collapse or reorder.
      (call $check (i32.eq (i32.load (local.get $r)) (i32.ne (local.get $i) (i32.const 1))) (i32.add (i32.const 401) (local.get $i)))
      (if (local.get $diagnostics) (then
        (call $check (i32.eq (i32.load offset=4 (local.get $r)) (local.get $next)) (i32.const 405))
        (call $check (i32.eq (i32.load offset=8 (local.get $r)) (i32.eq (local.get $i) (i32.const 1))) (i32.const 406))
        (local.set $next (i32.add (local.get $next) (i32.load offset=8 (local.get $r))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $routes (i32.lt_u (local.get $i) (i32.const 4)))))

  (func $scenario (param $id i32)
    (local $x i32) (local $y i32) (local $z i32) (local $n i32)
    (local $i i32) (local $pc i32) (local $end i32) (local $found i32)
    (local $cost i64) (local $debt i64) (local $source_work i64)
    (if (i32.eqz (local.get $id)) (then
      (call $compile (global.get $F_route) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $expect_program (global.get $F_standaloneRouteProgram))
      (local.set $x (global.get $p)) (local.set $n (global.get $pn))
      (memory.fill (global.get $s) (i32.const 193) (global.get $cap))
      (memory.fill (global.get $input) (i32.const 193) (global.get $inbytes))
      (call $check (i32.eqz (call $load (local.get $x) (local.get $n))) (i32.const 410))
      (call $validate (global.get $F_good) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 2))
      (call $check (i32.eq (call $verdict (call $cont)) (i32.const 2)) (i32.const 411))
      (call $validate (global.get $F_bad) (i64.const -2) (i32.const 0) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 3))
      (call $check (i32.eq (call $error_stored (call $cont)) (i32.const 1)) (i32.const 412))
      (return)))
    (if (i32.eq (local.get $id) (i32.const 1)) (then
      (call $compile (global.get $F_set) (i32.const 16) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $expect_program (global.get $F_standaloneSetProgram))
      (call $check (i32.eq (call $program_routes (global.get $p)) (i32.const 4)) (i32.const 413))
      (call $validate (global.get $F_good) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 2))
      (call $set_results (i32.const 0))
      (call $validate (global.get $F_good) (i64.const -2) (i32.const 1) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 2))
      (call $set_results (i32.const 1))
      (call $check (i32.eq (i32.load16_u (call $error_record (call $cont) (i32.const 0))) (i32.const 64)) (i32.const 414))
      (call $render) (call $expect (i32.const 0))
      (call $check (i32.eq (i32.load8_u (global.get $out)) (i32.const 133)) (i32.const 415))
      (call $check (i32.eq (call $find (global.get $F_falseMessage) (i32.const 1)) (global.get $outlen)) (i32.const 416)) (return)))
    (if (i32.eq (local.get $id) (i32.const 2)) (then
      (call $compile (global.get $F_bundle) (i32.const 0) (i64.const -2) (i32.const 1)) (call $expect (i32.const 0))
      (call $expect_program (global.get $F_standaloneBundleProgram))
      (call $validate (global.get $F_string) (i64.const -2) (i32.const 1) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 2))
      (call $validate (global.get $F_one) (i64.const -2) (i32.const 1) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 3)) (return)))
    (if (i32.eq (local.get $id) (i32.const 3)) (then
      (call $compile (global.get $F_regex) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (local.set $x (global.get $p)) (local.set $n (global.get $pn)) (local.set $cost (call $work))
      (call $compile (global.get $F_regex) (i32.const 0) (i64.const -2) (i32.const 1)) (call $expect (i32.const 0))
      (call $check (i32.eq (local.get $n) (global.get $pn)) (i32.const 420))
      (call $check (call $same (local.get $x) (global.get $p) (local.get $n)) (i32.const 421))
      (call $check (i64.eq (local.get $cost) (call $work)) (i32.const 422))
      (call $validate (global.get $F_regexDoc) (i64.const -2) (i32.const 0) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 2))
      (local.set $cost (call $work))
      (call $validate (global.get $F_regexDoc) (i64.const -2) (i32.const 1) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 2))
      (call $check (i64.eq (local.get $cost) (call $work)) (i32.const 423)) (return)))
    (if (i32.eq (local.get $id) (i32.const 4)) (then
      (call $compile (global.get $F_chain) (i32.const 0) (i64.const 1) (i32.const 0)) (call $expect (i32.const 11))
      (call $check (i32.eq (i32.load offset=32 (global.get $b)) (i32.const 2)) (i32.const 424)) (return)))
    (if (i32.eq (local.get $id) (i32.const 5)) (then
      (call $compile (global.get $F_chain) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $validate (global.get $F_nil) (i64.const 10000) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 11))
      (call $check (i32.eq (i32.load offset=32 (global.get $b)) (i32.const 6)) (i32.const 425)) (return)))
    (if (i32.eq (local.get $id) (i32.const 6)) (then
      (call $compile (global.get $F_items) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $validate (global.get $F_large) (i64.const 1000) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 11))
      (call $check (i64.ge_u (call $work) (i64.const 1000)) (i32.const 426)) (return)))
    (if (i32.or (i32.eq (local.get $id) (i32.const 7)) (i32.eq (local.get $id) (i32.const 8))) (then
      (call $compile (global.get $F_route) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (local.set $cost (call $work)) (local.set $x (global.get $p)) (local.set $n (global.get $pn))
      (call $compile (global.get $F_route) (i32.const 0)
        (i64.sub (local.get $cost) (i64.extend_i32_u (i32.eq (local.get $id) (i32.const 8)))) (i32.const 0))
      (if (i32.eq (local.get $id) (i32.const 7)) (then
        (call $expect (i32.const 0))
        (call $check (i64.eq (call $work) (local.get $cost)) (i32.const 430))
        (call $check (i32.eq (global.get $pn) (local.get $n)) (i32.const 431))
        (call $check (call $same (global.get $p) (local.get $x) (local.get $n)) (i32.const 432)))
        (else (call $expect (i32.const 11))))
      (return)))
    (if (i32.or (i32.eq (local.get $id) (i32.const 9)) (i32.eq (local.get $id) (i32.const 10))) (then
      (call $compile (global.get $F_atomicSet) (i32.const 16) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $validate (global.get $F_good) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 2))
      (local.set $cost (call $work))
      (call $validate (global.get $F_good)
        (i64.sub (local.get $cost) (i64.extend_i32_u (i32.eq (local.get $id) (i32.const 10))))
        (i32.const 0) (i32.const 0) (i32.const 16384))
      (call $expect (select (i32.const 2) (i32.const 11) (i32.eq (local.get $id) (i32.const 9))))
      (call $check (i64.eq (call $work) (local.get $cost)) (i32.const 433))
      (call $check (i32.eq (i32.load offset=36 (global.get $b)) (i32.const 2)) (i32.const 434)) (return)))
    (if (i32.eq (local.get $id) (i32.const 11)) (then
      (call $compile (global.get $F_truth) (i32.const 0) (i64.const 0) (i32.const 0)) (call $expect (i32.const 11))
      (call $check (i64.eqz (call $work)) (i32.const 440))
      (local.set $x (call $copy (global.get $b) (i32.const 48)))
      (call $compile_call (i32.const 1)) (call $expect (i32.const 11))
      (call $check (call $same (local.get $x) (global.get $b) (i32.const 48)) (i32.const 441)) (return)))
    (if (i32.eq (local.get $id) (i32.const 12)) (then
      (global.set $input (call $fixture (global.get $F_truth))) (global.set $inbytes (i32.const 1))
      (call $new_budget (i64.const -2)) (call $new_scratch)
      ;; Adversarial restored record, exactly as the accepted overflow fixture:
      ;; seed history only before an operation; never alter a live source meter.
      (i64.store offset=24 (global.get $b) (i64.const -3))
      (call $compile_resources (i32.const 1)) (call $expect (i32.const 11))
      (call $check (i64.eq (call $work) (i64.const -1)) (i32.const 442))
      (call $check (i32.eq (i32.load offset=44 (global.get $b)) (i32.const 1)) (i32.const 443))
      (local.set $x (call $copy (global.get $b) (i32.const 48)))
      (call $compile_call (i32.const 1)) (call $expect (i32.const 11))
      (call $check (call $same (local.get $x) (global.get $b) (i32.const 48)) (i32.const 444)) (return)))
    (if (i32.eq (local.get $id) (i32.const 13)) (then
      (call $compile (global.get $F_regex) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (local.set $x (global.get $p)) (local.set $n (global.get $pn)) (local.set $cost (call $work))
      (global.set $input (call $fixture (global.get $F_regex))) (global.set $inbytes (call $fixture_size (global.get $F_regex)))
      (call $new_budget (i64.const -2)) (call $new_scratch)
      (global.set $cap (i32.const 8)) (global.set $grant (i32.const 1)) (global.set $relocate (i32.const 1))
      (i64.store (global.get $s) (i64.const 0x1234567812345678))
      (call $compile_call (i32.const 1)) (call $expect (i32.const 7))
      (call $check (i64.eq (i64.load (global.get $s)) (i64.const 0x1234567812345678)) (i32.const 450))
      (call $compile_resources (i32.const 1)) (call $expect (i32.const 0))
      (local.set $y (i32.add (global.get $s) (i32.load offset=32 (global.get $s))))
      (call $check (i32.eq (i32.load offset=36 (global.get $s)) (local.get $n)) (i32.const 451))
      (call $check (call $same (local.get $x) (local.get $y) (local.get $n)) (i32.const 452))
      (call $check (i64.eq (call $work) (local.get $cost)) (i32.const 453))
      (call $check (i32.ge_u (global.get $shortages) (i32.const 3)) (i32.const 454)) (return)))
    (if (i32.eq (local.get $id) (i32.const 14)) (then
      (call $compile (global.get $F_bundle) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $validate (global.get $F_string) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 2))
      (local.set $cost (call $work)) (global.set $relocate (i32.const 1))
      (call $validate (global.get $F_string) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 2))
      (call $check (i64.gt_u (global.get $first_work) (i64.const 0)) (i32.const 455))
      (call $check (i64.eq (call $work) (local.get $cost)) (i32.const 456))
      (call $check (i32.eq (i32.load offset=8 (call $cont)) (global.get $p)) (i32.const 457))
      (call $check (i32.eq (i32.load offset=16 (call $cont)) (global.get $d)) (i32.const 458)) (return)))
    (if (i32.or (i32.eq (local.get $id) (i32.const 15)) (i32.eq (local.get $id) (i32.const 16))) (then
      (call $compile (global.get $F_unique) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $validate (global.get $F_uniqueDoc) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 8)) (call $expect (i32.const 2))
      (call $check (i32.ge_u (global.get $shortages) (i32.const 2)) (i32.const 460))
      (call $check (i64.gt_u (global.get $last_work) (global.get $first_work)) (i32.const 461))
      (call $check (i32.gt_u (i32.load offset=40 (global.get $s)) (i32.const 8)) (i32.const 462))
      (local.set $cost (call $work)) (local.set $debt (global.get $last_work))
      (call $validate (global.get $F_uniqueDoc)
        (select (local.get $cost) (local.get $debt) (i32.eq (local.get $id) (i32.const 15)))
        (i32.const 0) (i32.const 0) (i32.const 8))
      (call $expect (select (i32.const 2) (i32.const 11) (i32.eq (local.get $id) (i32.const 15))))
      (call $check (i64.eq (call $work)
        (select (local.get $cost) (local.get $debt) (i32.eq (local.get $id) (i32.const 15)))) (i32.const 463)) (return)))
    (if (i32.or (i32.eq (local.get $id) (i32.const 17)) (i32.eq (local.get $id) (i32.const 18))) (then
      (call $compile (global.get $F_missingSchema) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $validate (global.get $F_empty) (i64.const -2) (i32.const 0) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 3))
      (local.set $source_work (call $validation_work (call $cont)))
      (call $render) (call $expect (i32.const 0)) (call $diagnostic)
      (call $check (i32.gt_u (global.get $outcap) (i32.const 8192)) (i32.const 470))
      (call $check (i64.eq (call $validation_work (call $cont)) (local.get $source_work)) (i32.const 471))
      (call $check (i32.eq (call $verdict (call $cont)) (i32.const 3)) (i32.const 472))
      (local.set $debt (global.get $last_work))
      (if (i32.eq (local.get $id) (i32.const 17)) (then
        (local.set $cost (call $work))
        (call $render_direct (global.get $p) (global.get $pn) (global.get $s) (global.get $cap)
          (i32.const 0) (global.get $s) (i32.const 8192) (global.get $b))
        (drop) (global.set $status) (call $expect (i32.const 12))
        (call $check (i64.eq (call $work) (local.get $cost)) (i32.const 473))
        (return)))
      (call $validate (global.get $F_empty) (local.get $debt) (i32.const 0) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 3))
      (global.set $outcap (i32.const 8192)) (global.set $out (call $alloc (global.get $outcap)))
      (call $render_call) (call $expect (i32.const 11))
      (call $check (i64.eq (call $work) (local.get $debt)) (i32.const 474))
      (call $render_call) (call $expect (i32.const 11))
      (call $check (i64.eq (call $work) (local.get $debt)) (i32.const 475)) (return)))
    (if (i32.eq (local.get $id) (i32.const 19)) (then
      (global.set $input (call $fixture (global.get $F_route))) (global.set $inbytes (call $fixture_size (global.get $F_route)))
      (local.set $x (call $copy (global.get $input) (global.get $inbytes)))
      (call $new_budget (i64.const -2)) (call $new_scratch)
      (call $compile_call (i32.const 1)) (call $expect (i32.const 7))
      (call $check (call $grow_scratch) (i32.const 479))
      (local.set $y (global.get $heap)) (global.set $limit (global.get $heap))
      (call $compile_resources (i32.const 0)) (call $expect (i32.const 7))
      (call $check (i32.eq (global.get $heap) (local.get $y)) (i32.const 480))
      (call $check (i32.gt_u (global.get $required) (global.get $cap)) (i32.const 481))
      (call $check (call $same (local.get $x) (global.get $input) (global.get $inbytes)) (i32.const 482))
      (call $check (i64.gt_u (call $work) (i64.const 0)) (i32.const 483))
      (local.set $cost (call $work))
      (call $compile_call (i32.const 0)) (call $expect (i32.const 7))
      (call $check (i64.eq (call $work) (local.get $cost)) (i32.const 484)) (return)))
    (if (i32.eq (local.get $id) (i32.const 20)) (then
      (call $compile (global.get $F_one) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 4))
      (call $check (i32.eq (i32.load offset=132 (global.get $s)) (i32.const 1)) (i32.const 490))
      (call $check (i32.eqz (i32.load offset=136 (global.get $s))) (i32.const 493))
      (call $check (i32.eqz (i32.load offset=140 (global.get $s))) (i32.const 494))
      (call $check (i32.eqz (i32.load offset=204 (global.get $s))) (i32.const 495))
      (call $compile (global.get $F_truth) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (call $validate (global.get $F_malformed) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 9))
      (call $check (i64.ge_u (call $work) (i64.const 129)) (i32.const 491))
      (call $check (i32.eq (i32.load offset=32 (global.get $b)) (i32.const 5)) (i32.const 492))
      (call $validate (global.get $F_wrapped) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 9)) (return)))
    (if (i32.eq (local.get $id) (i32.const 21)) (then
      (call $compile (global.get $F_corruptible) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (local.set $x (global.get $p)) (local.set $n (global.get $pn))
      (loop $corruptions
        (global.set $p (call $copy (local.get $x) (local.get $n)))
        (if (i32.eqz (local.get $i)) (then (i32.store offset=80 (global.get $p) (i32.const -16))))
        (if (i32.eq (local.get $i) (i32.const 1)) (then (i32.store offset=28 (global.get $p) (i32.const -16))))
        (if (i32.eq (local.get $i) (i32.const 2)) (then (i32.store offset=40 (global.get $p) (i32.const -8))))
        (if (i32.eq (local.get $i) (i32.const 3)) (then
          (i32.store offset=4 (i32.add (global.get $p) (i32.load offset=40 (global.get $p))) (i32.const -16))))
        (if (i32.eq (local.get $i) (i32.const 4)) (then
          (local.set $pc (i32.add (global.get $p) (i32.load offset=24 (global.get $p))))
          (local.set $end (i32.add (local.get $pc) (i32.load offset=28 (global.get $p))))
          (block $found (loop $instructions
            (br_if $found (i32.ge_u (local.get $pc) (local.get $end)))
            (if (i32.eq (i32.load (local.get $pc)) (i32.const 18)) (then
              (i32.store (i32.add (global.get $p) (i32.load offset=4 (local.get $pc))) (i32.const 1073741824))
              (local.set $found (i32.const 1)) (br $found)))
            (local.set $pc (i32.add (local.get $pc) (i32.const 16))) (br $instructions)))
          (call $check (local.get $found) (i32.const 500))))
        (call $check (i32.eq (call $load (global.get $p) (global.get $pn)) (i32.const 8)) (i32.add (i32.const 501) (local.get $i)))
        ;; Strict mode checks internals even when the TRUSTED bit is asserted.
        (call $validate (global.get $F_one) (i64.const -2) (i32.const 0) (i32.const 2) (i32.const 16384)) (call $expect (i32.const 8))
        (call $check (i64.gt_u (call $work) (i64.const 0)) (i32.const 506))
        (call $check (i32.eq (i32.load offset=32 (global.get $b)) (i32.const 8)) (i32.const 507))
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br_if $corruptions (i32.lt_u (local.get $i) (i32.const 5))))
      (return)))
    (if (i32.eq (local.get $id) (i32.const 22)) (then
      (call $new_budget (i64.const -2)) (call $new_scratch)
      (local.set $x (call $alloc (i32.const 56)))
      (call $check (i32.eq (call $budget_init (local.get $x) (i32.const 48) (i64.const -1) (i32.const 0)) (i32.const 12)) (i32.const 510))
      (call $check (i32.eq (call $budget_init (i32.add (local.get $x) (i32.const 1)) (i32.const 48) (i64.const 10) (i32.const 0)) (i32.const 12)) (i32.const 511))
      (global.set $input (call $fixture (global.get $F_truth))) (global.set $inbytes (i32.const 1))
      (call $compile_direct (global.get $input) (i32.const 1) (i32.const 0)
        (global.get $input) (i32.const 64) (global.get $b) (i32.const 1) (i32.const 0))
      (drop) (global.set $status) (call $expect (i32.const 12))
      (call $compile_direct (global.get $b) (i32.const 1) (i32.const 0)
        (global.get $s) (global.get $cap) (global.get $b) (i32.const 1) (i32.const 0))
      (drop) (global.set $status) (call $expect (i32.const 12))
      (call $validate_direct (i32.const -8) (i32.const 80) (global.get $input) (i32.const 1)
        (i32.const 0) (i32.const 256) (i32.const 0) (i32.const 8) (global.get $s) (global.get $cap)
        (global.get $b) (i32.const 1) (i32.const 0))
      (drop) (global.set $status) (call $expect (i32.const 12))
      (call $check (i64.eqz (call $work)) (i32.const 512)) (return)))
    (if (i32.eq (local.get $id) (i32.const 23)) (then
      (call $compile (global.get $F_missingSchema) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (local.set $x (call $copy (global.get $p) (global.get $pn)))
      (local.set $cost (call $work))
      (memory.fill (global.get $s) (i32.const 193) (global.get $cap))
      (memory.fill (global.get $input) (i32.const 193) (global.get $inbytes))
      ;; Compile + validation + all diagnostic output attempts use ONE budget.
      (global.set $d (call $fixture (global.get $F_empty))) (global.set $dn (call $fixture_size (global.get $F_empty)))
      (global.set $mode (i32.const 1)) (call $new_scratch) (call $validate_resources (i32.const 1)) (call $expect (i32.const 3))
      (call $check (i64.gt_u (call $work) (local.get $cost)) (i32.const 520))
      (call $render) (call $expect (i32.const 0)) (call $diagnostic)
      (call $check (call $same (local.get $x) (global.get $p) (global.get $pn)) (i32.const 521))
      ;; Dependents are retired first; the independent portable copy remains.
      (memory.fill (global.get $out) (i32.const 193) (global.get $outcap))
      (memory.fill (global.get $s) (i32.const 193) (global.get $cap))
      (memory.fill (global.get $d) (i32.const 193) (global.get $dn))
      (memory.fill (global.get $p) (i32.const 193) (global.get $pn))
      (global.set $p (local.get $x))
      (call $check (i32.eqz (call $load (global.get $p) (global.get $pn))) (i32.const 522))
      (call $validate (global.get $F_empty) (i64.const -2) (i32.const 0) (i32.const 0) (i32.const 16384)) (call $expect (i32.const 3)) (return)))
    (if (i32.eq (local.get $id) (i32.const 24)) (then
      (call $compile (global.get $F_threeRequired) (i32.const 0) (i64.const -2) (i32.const 0)) (call $expect (i32.const 0))
      (global.set $errors (i32.const 1))
      (call $validate (global.get $F_empty) (i64.const -2) (i32.const 0) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 3))
      (call $check (i32.eq (call $error_count (call $cont)) (i32.const 3)) (i32.const 530))
      (call $check (i32.eq (call $error_stored (call $cont)) (i32.const 1)) (i32.const 531))
      (call $render) (call $expect (i32.const 0))
      (drop (call $find (global.get $F_firstMissingParam) (i32.const 1)))
      (global.set $errors (i32.const 0))
      (call $validate (global.get $F_empty) (i64.const -2) (i32.const 0) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 3))
      (call $check (i32.eq (call $error_count (call $cont)) (i32.const 3)) (i32.const 532))
      (call $check (i32.eqz (call $error_stored (call $cont))) (i32.const 533))
      (global.set $errors (i32.const 65537))
      (call $validate (global.get $F_empty) (i64.const -2) (i32.const 0) (i32.const 1) (i32.const 16384)) (call $expect (i32.const 6))
      (return)))
    (if (i32.eq (local.get $id) (i32.const 25)) (then
      (call $compile (global.get $F_unresolved) (i32.const 0) (i64.const 65536) (i32.const 0))
      (call $expect (i32.const 4))
      (local.set $cost (call $work))
      (global.set $outcap (i32.const 2048)) (global.set $out (call $alloc (global.get $outcap)))
      (call $render_failure (global.get $s) (global.get $cap) (global.get $out) (i32.const 8) (global.get $b))
      (global.set $outlen) (global.set $status) (call $expect (i32.const 7))
      (call $check (i32.eq (global.get $outlen) (i32.const 2048)) (i32.const 540))
      (call $check (i64.gt_u (call $work) (local.get $cost)) (i32.const 541))
      (call $render_failure (global.get $s) (global.get $cap) (global.get $out) (global.get $outcap) (global.get $b))
      (global.set $outlen) (global.set $status) (call $expect (i32.const 0))
      (drop (call $find (global.get $F_failureDiagnostic) (i32.const 0)))
      (drop (call $find (global.get $F_failureMessage) (i32.const 0)))
      (call $check (i32.eq (i32.load offset=16 (global.get $s)) (i32.const 4)) (i32.const 542))
      (return)))
    (if (i32.eq (local.get $id) (i32.const 26)) (then (call $number_text_case) (return)))
    (if (i32.eq (local.get $id) (i32.const 27)) (then (call $number_conversion_case (i32.const 0)) (return)))
    (if (i32.eq (local.get $id) (i32.const 28)) (then (call $number_conversion_case (i32.const 1)) (return)))
    (call $check (i32.const 0) (i32.const 999)))

  (func $number_text_case
    (local $data i32) (local $size i32) (local $at i32) (local $charged i64) (local $overflow i32)
    (local.set $data (call $fixture (global.get $F_numberText)))
    (local.set $size (call $fixture_size (global.get $F_numberText)))
    (global.set $s (call $alloc (i32.const 864)))
    (global.set $out (call $alloc (i32.const 32)))
    (global.set $last_work (i64.const 0))
    (block $done (loop $numbers
      (br_if $done (i32.ge_u (local.get $at) (local.get $size)))
      (memory.fill (global.get $out) (i32.const 165) (i32.const 32))
      (call $format_number (f64.load (i32.add (local.get $data) (local.get $at)))
        (global.get $out) (i32.const 32) (global.get $s) (i32.const 864))
      (local.set $overflow) (local.set $charged) (global.set $outlen) (global.set $status)
      (call $expect (i32.const 0))
      (call $check (i32.eqz (local.get $overflow)) (i32.const 550))
      (call $check (i64.gt_u (local.get $charged) (i64.const 0)) (i32.const 551))
      (call $check (i32.eq (global.get $outlen) (i32.load offset=8 (i32.add (local.get $data) (local.get $at)))) (i32.const 552))
      (call $check (call $same (global.get $out) (i32.add (i32.add (local.get $data) (local.get $at)) (i32.const 12)) (global.get $outlen)) (i32.const 553))
      (call $check (i32.eq (i32.load8_u (i32.add (global.get $out) (global.get $outlen))) (i32.const 165)) (i32.const 554))
      (global.set $last_work (i64.add (global.get $last_work) (local.get $charged)))
      (local.set $at (i32.add (local.get $at) (i32.const 48))) (br $numbers)))
    (memory.fill (global.get $out) (i32.const 165) (i32.const 32))
    (memory.fill (global.get $s) (i32.const 165) (i32.const 864))
    (call $format_number (f64.const -4.9406564584124654e-324) (global.get $out) (i32.const 31) (global.get $s) (i32.const 864))
    (local.set $overflow) (local.set $charged) (global.set $outlen) (global.set $status)
    (call $expect (i32.const 7))
    (call $check (i32.and (i32.eqz (global.get $outlen)) (i64.eqz (local.get $charged))) (i32.const 555))
    (call $check (i32.eq (i32.load8_u (global.get $s)) (i32.const 165)) (i32.const 556))
    (call $check (i32.eq (i32.load8_u (global.get $out)) (i32.const 165)) (i32.const 557))
    (call $format_number (f64.const 1) (global.get $s) (i32.const 32) (global.get $s) (i32.const 864))
    (local.set $overflow) (local.set $charged) (global.set $outlen) (global.set $status)
    (call $expect (i32.const 12))
    (call $check (i32.and (i32.eqz (global.get $outlen)) (i64.eqz (local.get $charged))) (i32.const 558))
    (call $check (i32.eq (i32.load8_u (global.get $s)) (i32.const 165)) (i32.const 559)))

  (func $number_conversion_case (param $hex i32)
    (local $data i32) (local $size i32) (local $at i32) (local $p i32)
    (local $length i32) (local $charged i64) (local $overflow i32) (local $value f64) (local $expected f64)
    (local.set $data (call $fixture (select (global.get $F_numberHex) (global.get $F_numberParse) (local.get $hex))))
    (local.set $size (call $fixture_size (select (global.get $F_numberHex) (global.get $F_numberParse) (local.get $hex))))
    (global.set $s (call $alloc (i32.const 320)))
    (global.set $last_work (i64.const 0))
    (block $done (loop $records
      (br_if $done (i32.ge_u (local.get $at) (local.get $size)))
      (local.set $p (i32.add (local.get $data) (local.get $at)))
      (local.set $length (i32.load offset=4 (local.get $p)))
      (local.set $expected (f64.load offset=8 (local.get $p)))
      (memory.fill (global.get $s) (i32.const 165) (i32.const 320))
      (if (local.get $hex)
        (then
          (call $format_number_hex (local.get $expected) (global.get $s) (i32.const 320))
          (local.set $overflow) (local.set $charged) (global.set $outlen) (global.set $status)
          (call $check (i32.eq (global.get $outlen) (local.get $length)) (i32.const 560))
          (call $check (call $same (global.get $s) (i32.add (local.get $p) (i32.const 16)) (local.get $length)) (i32.const 561))
          (call $check (i32.eq (i32.load8_u (i32.add (global.get $s) (local.get $length))) (i32.const 165)) (i32.const 562)))
        (else
          (call $parse_number_utf16 (i32.add (local.get $p) (i32.const 16)) (local.get $length) (global.get $s) (i32.const 320))
          (local.set $overflow) (local.set $charged) (local.set $value) (global.set $status)
          (call $check (i32.or
            (i64.eq (i64.reinterpret_f64 (local.get $value)) (i64.reinterpret_f64 (local.get $expected)))
            (i32.and (f64.ne (local.get $value) (local.get $value)) (f64.ne (local.get $expected) (local.get $expected)))) (i32.const 563))))
      (call $expect (i32.const 0))
      (call $check (i32.eqz (local.get $overflow)) (i32.const 564))
      (if (local.get $length) (then (call $check (i64.gt_u (local.get $charged) (i64.const 0)) (i32.const 565))))
      (global.set $last_work (i64.add (global.get $last_work) (local.get $charged)))
      (local.set $at (i32.add (local.get $at) (i32.load (local.get $p)))) (br $records)))
    (memory.fill (global.get $s) (i32.const 165) (i32.const 320))
    (if (local.get $hex)
      (then
        (call $format_number_hex (f64.const 0.1) (global.get $s) (i32.const 319))
        (local.set $overflow) (local.set $charged) (global.set $outlen) (global.set $status)
        (call $expect (i32.const 7)) (call $check (i32.eqz (global.get $outlen)) (i32.const 566)))
      (else
        (call $parse_number_utf16 (global.get $s) (i32.const 1) (global.get $s) (i32.const 320))
        (local.set $overflow) (local.set $charged) (local.set $value) (global.set $status)
        (call $expect (i32.const 12)) (call $check (f64.ne (local.get $value) (local.get $value)) (i32.const 567))))
    (call $check (i64.eqz (local.get $charged)) (i32.const 568))
    (call $check (i32.eqz (local.get $overflow)) (i32.const 569))
    (local.set $at (i32.const 0))
    (block $checked (loop $canaries
      (br_if $checked (i32.eq (local.get $at) (i32.const 320)))
      (call $check (i32.eq (i32.load8_u (i32.add (global.get $s) (local.get $at))) (i32.const 165)) (i32.const 570))
      (local.set $at (i32.add (local.get $at) (i32.const 1))) (br $canaries))))

  (func (export "case_count") (result i32) (i32.const @CASE_COUNT@))
  (func (export "result_pointer") (result i32) (i32.const 1024))
  (func (export "result_size") (result i32) (i32.const 32))
  (func (export "run_case") (param $id i32) (result i32)
    ;; Every invocation starts independent and finishes all its dependencies.
    (global.set $heap (i32.const 4096)) (global.set $limit (i32.const 1073741824))
    (global.set $failure (i32.const 0)) (global.set $status (i32.const 0)) (global.set $expected (i32.const 0))
    (global.set $b (i32.const 0)) (global.set $options (i32.const 0)) (global.set $grant (i32.const 0))
    (global.set $relocate (i32.const 0)) (global.set $arena (i32.const 16384))
    (global.set $errors (i32.const 8))
    (memory.fill (i32.const 1024) (i32.const 0) (i32.const 32))
    (call $scenario (local.get $id))
    (i32.store (i32.const 1024) (local.get $id))
    (i32.store (i32.const 1028) (global.get $status))
    (i32.store (i32.const 1032) (global.get $failure))
    (i32.store (i32.const 1036) (global.get $expected))
    (if (global.get $b) (then
      (i32.store (i32.const 1040) (i32.load offset=32 (global.get $b)))
      (i64.store (i32.const 1048) (call $work))))
    (if (i32.and (i32.ge_u (local.get $id) (i32.const 26)) (i32.le_u (local.get $id) (i32.const 28)))
      (then (i64.store (i32.const 1048) (global.get $last_work))))
    ;; Final lifetime boundary: output record is the ONLY retained owner.
    (memory.fill (i32.const 4096) (i32.const 193) (i32.sub (global.get $heap) (i32.const 4096)))
    (global.set $heap (i32.const 4096))
    (global.get $failure))
)
